### ISSUE TITLE
Instruction

### ISSUE THREAD

**Issue by Wombat2018** [MrOtherGuy/firefox-csshacks#1]
Hi,

I am beginner in CSS Hacks and do not know how to apply your example settings. I copied the chrome and content folder in my profile folder and the userContent.css and userConent.css directly in the profile folder, but nothing changes.

**Comment by MrOtherGuy** [comment]
When you find your profile folder you will first need to create `chrome` folder there. Then, put everything from this repository to that chrome folder. So then you'll have this:

```
<profile_folder>
|_chrome
|   |_chrome
|   |_content
|   |_userChrome.css
|   |_userContent.css
|_extensions
...
all other profile folders and files
...
```

I'll add this info to readme too

**Comment by Wombat2018** [comment]
Thank you!
