### ISSUE TITLE
multi-row_tabs.css - sort tabs not working

### ISSUE THREAD

**Issue by ltstereo** [MrOtherGuy/firefox-csshacks#103]
The csshack works great. Is there a way to sort your tabs if you have more than one row? As long as you only have one row, I can drag and drop to sort the tabs. As soon as I have 2 or more it doesn't work anymore. Did I miss a setting or is that not possible?

**Comment by MrOtherGuy** [comment]
It's not possible unfortunately.

Firefox tab-dragging/sorting logic only looks for the horizontal coordinate of the tab, and that yields totally incorrect results when multiple tabs have the same horizontal coordinate. There is nothing that can be done to that in css.
