### ISSUE TITLE
Toolbar below content with autohide not working on fullscreen

### ISSUE THREAD

**Issue by ngmoviedo** [MrOtherGuy/firefox-csshacks#107]
I'm using the following combination of scripts:
```
/* Import from hacks repo */
@import url(firefox-csshacks/chrome/autohide_toolbox.css);
@import url(firefox-csshacks/chrome/hide_tabs_toolbar.css);
@import url(firefox-csshacks/chrome/compact_urlbar_megabar.css);
@import url(firefox-csshacks/chrome/toolbars_below_content.css);
@import url(firefox-csshacks/chrome/autohide_sidebar.css);

/* Hide sidebar header, when using Tree Style Tab. */
#sidebar-box[sidebarcommand="treestyletab_piro_sakura_ne_jp-sidebar-action"] #sidebar-header {
    visibility: collapse;
}
/* Sidebar min and max width removal */
#sidebar {
    max-width: none !important;
    min-width: 0px !important;
}
```
I've also applied the suggested change to `toolbars_below_content.css`:
```
#urlbar[breakout][breakout-extend]{
    display: flex !important;
    flex-direction: column-reverse;
    bottom: 5px !important; /* Change to 3-5 px if using compact_urlbar_megabar.css depending on toolbar density */
    top: auto !important;
}

```
For the most part, it works like a charm, but when going fullscreen the toolbar seem to be out of bounds and doesn't show at all. Nor hovering nor pressing Ctrl+l or F6.

On Ctrl+l, the nav bar expands as expected, but its bottom remains invisible.

This has been happening for a while, since I decided to move to toolbar to the bottom, so it's not related to the latest Firefox UI rework.

I'm using i3-gaps on Arch Linux. I don't think it's related to the window manager, but I haven't had the occasion to test it in any other OS or WM.

Thanks for your attention and for this awesome collection of scripts.

**Comment by MrOtherGuy** [comment]
Damn. I never  anticipated that someone would use both toolbars below content AND autohide toolbox at the same time. Frankly, I'm extremely surprised they work at all together. I'll give this fullscreen interaction some thought tomorrow probably. I don't think it's going to be anything too complex since it works in windowed mode.

**Comment by jacksongoode** [comment]
I found a similar issue I believe with just the  `autoide_main_toolbar.css` - and it is a result of another configuration I have that removes GTK title bars (as a Gnome extension). When I re-enable the title bar from the FF customization toggle, it works properly.

**Comment by ngmoviedo** [comment]
I hadn't tried `autohide_main_toolbar.css` before. In my case using that works in full screen. But it doesn't work very well in general. The hiding animation becomes a bit clunky and there's some extra space under the toolbar.

Actually, I discovered this repo when looking for a way to move the toolbar to the bottom. I already had some code to hide tabs and autohide the toolbar. As I use Firefox with vi-like keybindings (tridactyl) I wanted to reduce the clutter.

**Comment by MrOtherGuy** [comment]
Good catch, but I don't think the issues are related. Interestingly the autohide_main_toolbar behaves very differently on Linux that it does on Windows. I honestly don't know why titlebar z-index causes problems with Linux but I was able to work around that.

So check if the latest version works, it seems to work for me with both Fedora linux and Windows 10 at least.

**Comment by MrOtherGuy** [comment]
Also, I think the main issue here is that toolbars_below_content.css just doesn't work properly in fullscreen mode. I see if I can figure something out to fix that. Then lets see how that affects the situation when used with other styles.

**Comment by ngmoviedo** [comment]
Anyway, although I don't know much css, I had an intuition and solved it.

I just added the following line:

```
#titlebar{ margin-bottom: -40px }
```
Appears to be working now.

**Comment by jacksongoode** [comment]
> Good catch, but I don't think the issues are related. Interestingly the autohide_main_toolbar behaves very differently on Linux that it does on Windows. I honestly don't know why titlebar z-index causes problems with Linux but I was able to work around that.
> 
> So check if the latest version works, it seems to work for me with both Fedora linux and Windows 10 at least.

Fixed!

**Comment by MrOtherGuy** [comment]
> 
> 
> Anyway, although I don't know much css, I had an intuition and solved it.
> 
> I just added the following line:
> 
> ```
> #titlebar{ margin-bottom: -40px }
> ```
> 
> Appears to be working now.

What did you apply that to? toolbars_below_content already does that, so I'm not sure what exactly you mean.

**Comment by ngmoviedo** [comment]
Here it is:
```
/* Import from hacks repo */
@import url(firefox-csshacks/chrome/autohide_toolbox.css);
@import url(firefox-csshacks/chrome/hide_tabs_toolbar.css);
@import url(firefox-csshacks/chrome/toolbars_below_content.css);
@import url(firefox-csshacks/chrome/autohide_sidebar.css);

/* Hide sidebar header, when using Tree Style Tab. */
#sidebar-box[sidebarcommand="treestyletab_piro_sakura_ne_jp-sidebar-action"] #sidebar-header {
    visibility: collapse;
}
/* Sidebar min and max width removal */
#sidebar {
    max-width: none !important;
    min-width: 0px !important;
}

/* Fix for autohide_toolbox + toolbars_below_content on full screen */
#titlebar{ margin-bottom: -40px }

/* Fix for navbar borders when using toolbars_below_content */
#urlbar[breakout][breakout-extend]{
    bottom: 3px !important; 
}
```
The imported scripts are unmodified.

**Comment by MrOtherGuy** [comment]
Thanks! I have an idea now what to do but it requires some thinking because this is essentially about how three styles - hide_tabs_toolbar, autohide_toolbox and toolbars_below_content interact together. I would rather not break any one of them in the process of fixing how they behave together.

**Comment by MrOtherGuy** [comment]
Alright folks, here's what I think about this issue.

1. toolbar_below_content.css is not compatible with fullscreen mode all by itself. I'll apply a patch to it shortly
2. The reason why hide_tabs_toolbar.css is as complex as it is, is because it tries to preserve window controls while hiding tabs. That probably isn't an issue if you have toolbars below content so you should use simple `#TabsToolbar{ visibility: collapse !important; }`  instead.
3. I need to apply a small compatibility rule to toolbars_below_content.css to make it work with autohide_toolbox.css.

This ordeal is a whole lot complicated so I hope I didn't mess something in process. But in the end, only toolbars_below_content.css needed some few changes, you just need to drop hide_tabs_toolbar.css from your styles list and use that short snippet above instead.

**Comment by ngmoviedo** [comment]
Great! I've replaced `hide_tabs_toobar.css` with the snippet you mentioned, and leaving the rest of my `userChrome.css` as it was. Can confirm that it works.

Having `#titlebar{ margin-bottom: -40px }` is still necessary, though, even when not in full screen now. If not added most of the toolbar remains hidden. Even if a better solution might be ideal, it's working very well for me.

Thanks for the help. It was really fast!

**Comment by MrOtherGuy** [comment]
So did you use the updated toolbars below content?

**Comment by ngmoviedo** [comment]
Oops. Sorry, I thought that you were still figuring it out. I've seen it now and it works. The line I mentioned is no longer necessary.

Thanks and kudos on the great work!

**Comment by MrOtherGuy** [comment]
Awesome, and thanks for testing!
