### ISSUE TITLE
non_floating_sharp_tabs has no outlines (FF 89)

### ISSUE THREAD

**Issue by mick-p1982** [MrOtherGuy/firefox-csshacks#109]
I think this (https://github.com/MrOtherGuy/firefox-csshacks/blob/master/chrome/non_floating_sharp_tabs.css) is probably supposed to have some outlines and/or separators between tabs. I'm trying to fix FF89 (modern tabs) and there's absolutely no black/dark outline, which I feel should run along the bottom (for unopened tabs) and separate the individual tabs. (It's all just text on an almost solid background.)

Edited: This page (https://www.howtogeek.com/334716/how-to-customize-firefoxs-user-interface-with-userchrome.css/) has images of outlined tabs. I would play with it but I don't know how `var(--tabs-border-color)` is changed/observed and have a sinking feeling I'd have to Exit/Run Firefox just to previous my changes... I swear I gotta just drop FF... I just hate the people at Mozilla too much to drop it.

Edited: The following change (don't like it's hard-coded color) restores the tab outline... I just noticed the "comment" that made it pretty clear how to change it. (A8A8A8 comes from taking a screenshot of the border between the toolbar and webpage content.)

```
/* This sets a color for border around tabs and between tabs & navigation toolbars. Set to transparent to remove the border.*/
#navigator-toolbox{
  //--tabs-border-color: color-mix(in srgb, currentcolor 30%, transparent) !important;
  --tabs-border-color: #A8A8A8 !important;
}
```

More: On separators... maybe they never did exist before? They don't seem as necessary as the bottom border and opened tab border.

**Comment by MrOtherGuy** [comment]
This is essentially the same as #108 - so you'll need to set `layout.css.color-mix.enabled` to true and they should just start working properly.
