### ISSUE TITLE
Issue adding a new page to existing browser window

### ISSUE THREAD

**Issue by donathorgz** [MrOtherGuy/firefox-csshacks#11]
Hey,
Is it me, but once I try opening a webpage (let say from my email, outlook or other app),
I receive a message - "Firefox is already running, but is not responding. The old Firefox process must be closed to open a new window".
So I am forced to close existing session window - an reopen window with this new page added.
It is little bit annoying and a fix would be appreciated.
Or maybe I need to tweak my css in some way?

Regards

**Comment by MrOtherGuy** [comment]
I honestly don't think that this has anything to do with custom CSS.

Most likely cause is that the first Firefox instance you have is launched with `-no-remote` flag. This flag prevents further messages from window manager to be received and in effect causes the message you describe to be shown.
