### ISSUE TITLE
autohide_bookmarks_toolbar no longer showing bookmarks toolbar on non empty tabs

### ISSUE THREAD

**Issue by windalin** [MrOtherGuy/firefox-csshacks#114]
I'm currently on Firefox 89 but this broke in an earlier update (don't remember which one).  The bookmarks toolbar shows itself just fine on a new tab, but on non empty tabs the bookmarks toolbar no longer shows upon selecting the address bar.

**Comment by MrOtherGuy** [comment]
The default behavior of Firefox has been chamged to only show bookmarks toolbar on new tabs. So, right click the toolbar area and set bookmarks toolbar to "always show" - after that this style should work like you expect.

**Comment by windalin** [comment]
Thank you.
