### ISSUE TITLE
Remove Tab Top Line in non_floating_sharp_tabs.css

### ISSUE THREAD

**Issue by Wombat2018** [MrOtherGuy/firefox-csshacks#115]
Hi,

I would like to remove the line on top of all tabs in the non_floating_sharp_tabs.css, but I do not know how. I think the code could be the following, but it does not work.

.tab-line { display: none !important; }

**Comment by MrOtherGuy** [comment]
I think simplest way to remove it would be `.tab-background::before{ display: none !important; }`

**Comment by Wombat2018** [comment]
Perfect, thank you.
