### ISSUE TITLE
autohide bookmarks bar + nav bar

### ISSUE THREAD

**Issue by JffLcrx** [MrOtherGuy/firefox-csshacks#116]
Hello.
I really like your autohide_bookmarks_toolbar.css, and I wanted to know if it's possible to do exactly what this css do, but also hide the main toolbars (nav-bar, I believe), so that both will be visible when hovering on the tab bar?

I also have 0 knowledge on css and that I tried the autohide_bookmarks_and_main_toolbars.css, but for some reason did nothing on my ff.

Thank you for your time

**Comment by MrOtherGuy** [comment]
Yes, `autohide_bookmarks_and_main_toolbars.css` is supposed to do just that. Just to be sure, you did you **replace**  autohide_bookmarks_toolbar.css with that one?

I don't know why it doesn't work for you. All I can say that it appears to work totally fine for me i´with Firefox 89 and also Nightly 91.

**Comment by JffLcrx** [comment]
Thanks for the reply. Yes, I replaced it. Just to be sure I created a new userChrome.css with just autohide_bookmarks_and_main_toolbars.css, for a test, and it's not doing anything. The weird thing is that it's the only css that's not doing anything from your Collection of random CSS hacks and other sites. Firefox is also v. 89.

**Comment by MrOtherGuy** [comment]
> with just the namespace line

Well, that would explain it. Nowadays, you should not add any namespace unless you know specifically what you would need it for.

 Its sole purpose is to limit the rules in that file (userChrome.css in this case) to specific kinds of elements. Historically how its been used and what you will find all over the web it limits the rules to only xul elements, but nowadays Firefox UI is built as mixture of xul and html elements. So, if ypu include xul namespace line, then all the rules that would match html elements will be "ignored" thus not do anything.

**Comment by JffLcrx** [comment]
Wow, thank you so much for you help and time. It definitely work now!
Hope this will eventually help someone in the future with the same error I had.

Thanks again!
