### ISSUE TITLE
Tab Color while moving Selected Tab in non_floating_sharp_tabs.css

### ISSUE THREAD

**Issue by Wombat2018** [MrOtherGuy/firefox-csshacks#117]
Hi,

one further thing which I would like to change in non_floating_sharp_tabs.css:

When I move a selected tab with the mouse, it gets a color like all the other tabs, but it should keep the color that marks it actively. 

I would appreciate an answer.

**Comment by MrOtherGuy** [comment]
Nice catch! Should be fixed with 683bdce

**Comment by Wombat2018** [comment]
Thank you, now it works.
