### ISSUE TITLE
combining autohide tabbar/url/bookmarks

### ISSUE THREAD

**Issue by amaryniuk** [MrOtherGuy/firefox-csshacks#120]
No issue, sorry if posting question is frowned upon. 

Is there a file that combines auto-hiding of all the firefox UI (tab bar, url bar, bookmarks bar), either on hover or keypress (like alt like it's done for menu) for a completely minimal browsing experience?
I tried combining autohide_bookmarks_and_main_toolbars.css and autohide_tabstoolbar.css, which sort of works, but the mouse hover to expand everything is really jittery and unusable like that. 
Thanks. great repo.

**Comment by MrOtherGuy** [comment]
Try [autohide_toolbox.css](https://github.com/MrOtherGuy/firefox-csshacks/blob/master/chrome/autohide_toolbox.css)

**Comment by amaryniuk** [comment]
oh, perfect, thank you.
