### ISSUE TITLE
multi-row_tabs.css and dragging tabs

### ISSUE THREAD

**Issue by lDeNl** [MrOtherGuy/firefox-csshacks#123]
Hello! 
For many years I have been using FF55 with Tabmix plus, thanks for your script, I was able to do a convenient work with tabs like in old version, and there is a question, is it possible to make the tabs on the second and third lines drag true?
Now tabs are normally dragged only on the first line, on the rest everything is random.

i Use script like this 
```
.tabbrowser-tab[fadein]:not([pinned]){
  min-width: var(--multirow-tab-min-width) !important;
  flex-grow: var(--multirow-tab-dynamic-width);
  /*
  Uncomment to enable full-width tabs, also makes tab dragging a tiny bit more sensible
  Don't set to none or you'll see errors in console when closing tabs
  */
  max-width: 100vw !important;
}
```

**Comment by MrOtherGuy** [comment]
No - it's not possible, unfortunately. Not with CSS.

The tab dragging logic (in javascript) only considers the horizontal coordinate of tabs to determine where they should be dropped to. And you can see that if you try to move a tab on second and third rows they will be moved somewhere on the first row.

If you want to modify that logic then you will need to modify the javascript logic for tab dragging. So, it's possible by abusing autoconfig to inject custom script, but at that point you should just create the whole multi-row layout with javascript. I think I've seen some implementation somewhere but can't remember where and if it was recently or not.

**Comment by j1warren** [comment]
Is it possible to completely disable tab dragging by mouse?
Every time I accidentally do this, the tabs move to some strange places and I have to find it and put it back by ctrl+shift+pgup-down.
