### ISSUE TITLE
Question about status_inside_urlbar_v2.css

### ISSUE THREAD

**Issue by Lepefe** [MrOtherGuy/firefox-csshacks#126]
Hi there, congrats for your repo. Please a question:

In status_inside_urlbar.css the zoom icon is always visible.
In status_inside_urlbar_v2.css, when status panel appears, the zoom icon is not visible.

I tried to apply different kind of z-index to zoom icon, but it's not visible when status_inside_urlbar_v2.css is active.
My question is about status_inside_urlbar_v2.css and zoom icon visible **always**, even when I hover a link. Please, how can I make that?

Thks

**Comment by MrOtherGuy** [comment]
I think you should be able to make the zoom button overlap the statusbar overlay by adding this:

    #urlbar-zoom-button{ position: relative; z-index: 3 }
