### ISSUE TITLE
Multi-Row not working firefox 90.0.2

### ISSUE THREAD

**Issue by artistwantab** [MrOtherGuy/firefox-csshacks#131]
Not sure whats wrong but I can't seem to get this to work now.

Windows 10
Firefox 90.0.2

I created the UserChrome in the Chrome folder.   

Set toolkit.legacyUserProfileCustomizations.stylesheets to TRUE.  

Not sure what to try next.

**Comment by MrOtherGuy** [comment]
Are you sure your userChrome.css is in the correct location? Do you have anything else in your userChrome.css file, and if so does *that* other thing work?

multi-row_tabs.css should work fine as far as I know.

**Comment by artistwantab** [comment]
userChrome.css is in the chrome folder in the profiles folder.   Nothing else in the file.   

All my profiles are an external drive if that matters.

**Comment by MrOtherGuy** [comment]
"profiles" folder sounds wrong. It should be inside *a specific* profile folder, so the same folder should contain files like prefs.js and places.sqlite

**Comment by artistwantab** [comment]
Yes...Sorry I should have made it more clear

On an external drive over the network.

There is a profile folder.  

Inside the profile folder -  there are multiple firefox profiles

\\NIGHTCRAWLER\Havok\myProfiles\games\chrome\userChrome.css

Above is one example.  

I cut and pasted the code directly from here...

https://github.com/MrOtherGuy/firefox-csshacks/blob/master/chrome/multi-row_tabs.css

I used dreamweaver so the file was not renamed

**Comment by artistwantab** [comment]
I decided to test if the it worked on the local drive and created a profile there.

Still no go.

**Comment by MrOtherGuy** [comment]
Hmm, perhaps you should test with just this as the file content:

    #nav-bar{ background: red !important }

Now, if that makes the main toolbar red, then at least you know that the file is indeed loaded.

**Comment by artistwantab** [comment]
Well it works.    The toolbar turned red.  

No idea what it could be but I will try anything suggested.

**Comment by MrOtherGuy** [comment]
Interesting... The only other thing I can think of is that I can think of is that it indeed won't work if you start you userChrome.css file with `@namespace url(http://www.mozilla.org/keymaster/gatekeeper/there.is.only.xul)` . The red nav-bar rule would work even if you have namespace defined so that's kinda plausible explanation.

**Comment by artistwantab** [comment]
I did try creating a profile on the local drive and it still didn't work for me.

**Comment by artistwantab** [comment]
well.  

I uninstalled firefox completely.   Reinstalled it with no add-ons and no profile. 

Uploaded userChrome into the default profile. 

Added bookmarks and still no multibar.

**Comment by MrOtherGuy** [comment]
> Added bookmarks to see if the multi-row works and still no multi-row.

Wait, the style you mentioned is for multi-row **tabs**, not bookmarks. Multi-row bookmarks style [is this one](https://github.com/MrOtherGuy/firefox-csshacks/blob/master/chrome/multi-row_bookmarks.css)

**Comment by artistwantab** [comment]
Well.

Now I feel like an idiot.  Thank you so much.   

I didn't even know there was a multi-row tabs so I never looked beyond the word multi-row.

Sorry again.  Be well.
