### ISSUE TITLE
Moving tabs not possible

### ISSUE THREAD

**Issue by dumstrut512** [MrOtherGuy/firefox-csshacks#132]
In Firefox 90 using the latest multi-row_tabs.css i've set --multirow-tab-min-width: 40px and --multirow-n-rows: 2. For example I don't seem to able to drag the farthest left tab in the upper row any more right beyond the border of the last tab on the second row.

It's hard to explain but i can try to clarify if needed.

**Comment by MrOtherGuy** [comment]
Yeah, like the style mentions it's a known problem and impossible to fix with CSS. There's really only two options you have if you require ability to reorder tabs:

1. Use some extension like TST and do the reordering in its sidebar.
2. Implement custom multi-row layout and all the functionality it needs by injecting javascript to Firefox main process using autocofig,

**Comment by MrOtherGuy** [comment]
Yes, reordering will be broken with this style, unfortunately.

I'm not sure what the use-case would be for --multirow-n-rows: 1 but I can check later if it's broken. There is supposed to be a scrollbar there if tabs are on multiple rows though, so if that what you see then replace `scrollbar-width: thin` with `scrollbar-width: none`

**Comment by MrOtherGuy** [comment]
Right, so as far as I can tell, `--multirow-n-rows: 1` behaves exactly like it is supposed to. The scrollbar is indeed visible, and if you want to remove it you can set `scrollbar-width` to `none` on line 45

I'll close this issue since fixing the reordering will be impossible to fix.

**Comment by sonofevil** [comment]
Potentially interesting observation: Firefox seems to determine in which row normal tabs are draggable based on where the first normal tab is, and in which row pinned tabs are draggable based on where the first pinned tab is. Hence as long as all pinned tabs are in the first row, dragging works fine, and as long as all normal tabs are in the same row, even if it is the second row, dragging works fine too.

Possible application: My use case is that I have too many pinned tabs and needed more space for normal tabs. If all my pinned tabs were in the first row and all my normal tabs in the second row, then that would already solve my use case. In that case, dragging would work perfectly fine.

I will try to implement this in my fork. I'm working with Waterfox which required a few tweaks but is mostly identical. It should be possible to make pinned tabs use the full width of the first row.
