### ISSUE TITLE
FF91 changed non_floating_sharp_tabs.css again, any chance for update?

### ISSUE THREAD

**Issue by mick-p1982** [MrOtherGuy/firefox-csshacks#133]
FF91 has added fat margins above and below tabs. I think there were separators between the inactive tabs, if so there's not anymore. Maybe they've become fully transparent. Anyway, with these margins the vertical divider on the active tab no longer touches the bottom, so it looks like it's emerging out of thin air.

**Comment by MrOtherGuy** [comment]
non_floating_sharp_tabs.css should work perfectly fine with Firefox 91, are you sure your version of the style is up to date? Well at least I can't find any issues on any system I have tried it.

If you want vertical separators then add tab_separator_lines.css for that. You will need to enable `layout.css.color-mix.enabled` in about config for the separators to show up though.

**Comment by mick-p1982** [comment]
I think this (https://www.reddit.com/r/FirefoxCSS/comments/p3p8rh/how_to_keep_outline_around_url_bar_and_search_bar/) is related. I just noticed there's no outline around the address bar and search bar text input element.

It seems like 91 doesn't like clearly delineated input elements and is achieving this by overriding or ignoring some colors in the CSS.

**Comment by mick-p1982** [comment]
Please see my two edits. It seems apart from padding, going by the Reddit link, that the change in UI policy is to link outlining to hovering for some reason. When not hovering all this CSS is disabled, probably anything not marked `!important` is overruled or something like this.

**Comment by MrOtherGuy** [comment]
I don't see how the link you posted is in any way relevant here because it's just to set some border for urlbar but the style in question is about the shape of tabs.

> Also, what about the extra added padding?

What padding are you talking about? The style itself removes empty space around tabs so they are "connected" to the main toolbar.

**Comment by mick-p1982** [comment]
After 91's update there's 4px padding above tabs (above the outline) and 3px padding below (below the side outlines, there's no bottom on the outline.) BTW here (https://www.reddit.com/r/FirefoxCSS/comments/p3yvo7/ff91_can_we_disable_busy_hover_chrome_stuff_in/h8vjjra/?context=3) was my post too, you seem to have replied to it (similar name.)

FWIW it seems clear to me FF has introduced a new style where outlines aren't present until hovered over. That makes sense since they added the "super address bar" or whatever they call it, that bugs out when it's focused or hovered over. If that seems fine, then why not make FF as spazzy as it can be? There might be some underlying assumption, like that the text boxes will be a different color from the background (not white on light gray) or that the outline may not be high contrast (e.g. white on dark gray) and so won't be so noticeable. I have no idea what the default them in FF is like nowadays, I try to make it remain generic best I can.

**Comment by mick-p1982** [comment]
FYI after 92 I'm still having this chunky padding. Any idea what is the CSS to try to get it under control? BTW, I waited for 92 since in the Reddit link you said before, "Anyhow, the issue seems to be fixed in 92 so there's that. But if you want outline on urlbar, then you should use a theme that does have a border on urlbar."

**Comment by MrOtherGuy** [comment]
Could you describe clearly what exact things you experience to be broken? Preferably with images. In addition, if it's aboyt some of the stylesheets in this repository, then please only test with that stylesheet and do not include any other custom CSS (or js files if you have such). There is no way I can guarantee any arbitrary custom CSS to work with these styles.

Also, it would be useful to know which Firefox theme you are using so I can try to reproduce the problem.

**Comment by mick-p1982** [comment]
Okay, sorry, FF makes this difficult, so I didn't casually try it. It looks like `--tab-block-margin: 0px !important;` was added to the script, which fixes this problem. I recently applied the script so wasn't expecting it to already be updated.

Can you suggest anything to add an outline back to the address bar and search bar please? Since this script is called "sharp" maybe you could amend the script to bring sharpness back to these elements to match the tabs? (I wish I could remember the ridiculous buzz word Mozilla came up with when it rolled out these "soft" elements, like they thought their previous UI was triggering or  something like that, because it was so aggressive, I can't remember what they called it, it was funny though.)

**Comment by MrOtherGuy** [comment]
Your theme is the one responsible on adding always visible outline to urlbar, so I'm not going to force it with this style. If you search AMO, you'll find that some themes add that outline to urlbar but others do not. Besides, restyling urlbar is not in the scope of this style, tab shape is.

But, if you want to add that to any theme you can add `:root{ --toolbar-field-border-color: #f00 !important; }`

**Comment by mick-p1982** [comment]
Thanks again, although FWIW this style doesn't seem to fix the address/search bar outlines. I wonder if they're set to be 0px instead? Or something that would hide the outline altogether?

The theme I use is the built-in one that says it's supposed to be close to a generic gray desktop, i.e. not the white or black defaults.

**Comment by MrOtherGuy** [comment]
None of the built-in themes have that kind of description I think. Built-in are only Dark, Light, System (which selects between Dark and Light depending on OS color scheme) and Alpenglow. But regradless, I doubt the exact theme matters here. I tried that line on about 15 random themes and all built-in ones and it seems to work out fine. I can't think of any reason why it wouldn't work for you - unless you are on old Firefox version (doesn't seem to be the case) or using custom CSS that sets the outline to something else itself.

**Comment by mick-p1982** [comment]
I don't want to monopolize your time, but if you're curious why the border doesn't work, this (https://addons.mozilla.org/en-US/firefox/addon/simple-def/) is my theme, and attached is my script. It seems to have three sections, 1) adding X to tabs, 2) "megabar" removal, and 3) your script (although I just copy/pasted that one line instead of doing an update because I'd tweaked it a little.) [userChrome.zip](https://github.com/MrOtherGuy/firefox-csshacks/files/7270863/userChrome.zip)

**Comment by MrOtherGuy** [comment]
I just tested this on Firefox 92 and Nightly 94. I Installed the theme you linked and used that userChrome.css file of yours. The only thing I added to the end was that `:root{ --toolbar-field-border-color: #f00 !important; }`. The result I get is that in both Firefox 92 and Nightly, the urlbar now has a red outline when it is not selected - which I assume is what you were aiming to get.

I honestly can't think of anything that would explain why the behavior is different on your system.

**Comment by mick-p1982** [comment]
That works for me too, except that style is already in the file, and it doesn't work in place where it's already at in the file. I've done a lot of web design (not so much lately) and I can't see a reason for the position of the rule to matter in this case, knowing what I know of CSS (and can remember.) I would have suggested narrowing the rule but didn't want to make you read more words since you know what you're doing.

Please let me know what you find out. TBH I wish it was so straightforward to "query" (and edit) the stylesheet rules in the "chrome" in FF as it is in the page content. I don't understand why they differ to that degree. I really appreciate your hand holding in this. BTW, I am pretty certain that there was outline when I raised this Issue. I had a new PC that hadn't yet applied the update and I'm pretty sure that the permanent outline was one of the changes. I like this simple style with a regular window titlebar, I don't get it why browsers (companies) mess with everything, especially when the changes make the elements visually distracting and hard to make out.

**Comment by MrOtherGuy** [comment]
> and it doesn't work in place where it's already at in the file.

Okay I see what you mean now. Your syntax is just broken. CSS does NOT support "line comments" with `//` - that just leads to syntax error in adjacent lines. CSS only has block comments starting with `/*` and ending with `*/`

**Comment by MrOtherGuy** [comment]
But yes, I think you are right, in 91 the outline could have been changing on hover when using some specific themes.

**Comment by mick-p1982** [comment]
Seriously? I wonder why my syntax highlighter changes //comments... although not to the same color. I swear I probably have CSS files on my websites where I've written slash comments in the past, I wonder what is the effect. Plus I'm miffed that's really dumb/evil design where C-style comments are used, especially since C++ predated CSS, and C now uses slash comments.

**Comment by MrOtherGuy** [comment]
I think it's mostly because of backwards compatibility and because line-breaks don't have a a meaning in CSS - they are just white-space. Besides many pre-processors do have `//` support so you could use them as long as you compile them to block-comments for distribution.

**Comment by mick-p1982** [comment]
I get it, of course, it's just bad programmer/design instincts to create such a source of mistakes that could be missed in sites and requires everyone writing CSS to learn this hard rule firsthand by falling into its trap, and wastes our time having conversations like this one. It feels like bad faith (antisocial behavior) from its design committee, especially to not correct this by now.

**Comment by mick-p1982** [comment]
P.S. Just for the record, I still don't get it why the //comments had a side-effect of disabling the code on the next line, but leaving following lines in play.

**Comment by MrOtherGuy** [comment]
I think that's about the line-breaks having no meaning bit and also error-tolerance. IIRC a `//` token would make the browser ignore everything until the next semi-colon or next block-comment whichever comes first. But I could be wrong about that.
