### ISSUE TITLE
Fullscreen hovering issue with `autohide_toolbox.css`

### ISSUE THREAD

**Issue by QuantumStatement** [MrOtherGuy/firefox-csshacks#137]
In fullscreen (F11) mode toolbox dissapears when cursor leaves tabs area

Cursor position in which toolbox dissapears
![cursor1](https://user-images.githubusercontent.com/35406698/130333514-c335f1d9-7f82-45cf-ba27-f6a5f8d04a43.png)

Expected cursor position
![cursor2](https://user-images.githubusercontent.com/35406698/130333515-033ecf71-b0d4-4075-aaaa-0d2fdbe06c05.png)

**Comment by MrOtherGuy** [comment]
Thanks for reporting. This was easy to fix.
