### ISSUE TITLE
Active tab background colour - non_floating_sharp_tabs.css

### ISSUE THREAD

**Issue by corobin** [MrOtherGuy/firefox-csshacks#139]
The active tab bg on the default theme is white and the rest of the chrome is off-white.

non_floating_sharp_tabs inherits this and it creates a hard edge where the colours change abruptly.

I think it looks better to make the active tab background match the rest of the chrome.

https://i.imgur.com/wSdpTqk.png

Thanks!

**Comment by corobin** [comment]
@MrOtherGuy 

It looks like your patch for this does not work anymore,

I don't think this is actually new with Fx 154, I just only noticed...

<img width="376" height="270" alt="Image" src="https://github.com/user-attachments/assets/9c2b31f9-a315-4b57-a4fb-98f4d04a4b63" />

Re-reading your last comment, if you don't feel like maintaining this theme specific workaround perhaps it's ok to just remove this portion

**Comment by MrOtherGuy** [comment]
On my system at least, the default (i.e. system-auto theme) actually works correctly, but built in dark and light ones have the issue as shown in your screenshot. This is easy to fix since it appear that at some point the built in dark and light themes don't have a `lwtheme` attribute on window root, but `builtintheme` instead.

**Comment by corobin** [comment]
oh interesting difference, my last screenshot was using a new profile and it defaulted to the "System" theme.  i think the system theme just auto selects either the light or dark theme based on system preferences right? weird that it behaves differently on our systems.

edit: i just saw [this commit](https://github.com/MrOtherGuy/firefox-csshacks/commit/67842f9655b83c8e58d09d88b134ccade806f4b3), using this version of the file, it looks like this:

<img width="260" height="86" alt="Image" src="https://github.com/user-attachments/assets/f5ebe4fe-dc78-4ed7-ab61-06c62ec1fac1" />
