### ISSUE TITLE
8px padding on top when using tabs_on_bottom.css

### ISSUE THREAD

**Issue by blakkkk** [MrOtherGuy/firefox-csshacks#140]
I'm using to Aerial keep spaces of my desktop empty when maximizing windows. When I maximize Firefox there is 8px of padding that overflows into the space.

![firefox_K3EfNtHpsl](https://user-images.githubusercontent.com/23288358/131212053-d3985297-9924-48f9-9b59-832026e6733c.png)

The above space should be 25px but due to the 8px it only comes to 17px. I've done some investigating and found it comes from line 40 of `tabs_on_bottom.css`:
`#navigator-toolbox { padding-top: var(--uc-titlebar-padding,0px) !important; }`

Thanks in advance for any help!

**Comment by MrOtherGuy** [comment]
Ok, so normally on Windows when Firefox is maximized the top edge is ~8px "outside" the top edge. So, I don't think this is really an issue with the style. I believe you would find out that if you don't use any custom CSS the top edge is only that 17px from the top of your monitor - assuming that you meant that you have set Aerial to create a 25px margin around windows.

If my above assumption is correct, then you could just add `:root{ --uc-titlebar-padding: 0px !important }` and that would remove that empty black space. But the window would still be only 17px away from the top edge and there's nothing you can do with CSS to change that.
