### ISSUE TITLE
window controls in shown in fullscreen using window_control_placeholder_support

### ISSUE THREAD

**Issue by JTBrinkmann** [MrOtherGuy/firefox-csshacks#146]
When window_control_placeholder_support is used, going fullscreen (using F11) will cause the window controls to be displayed in the top-right corner of the page. I confirmed this with a userChrome.css containing only

```css
@import url(chrome/hide_tabs_toolbar.css);
@import url(chrome/window_control_placeholder_support.css);
```

**Screenshots**:
![firefox_MzqmLn9Nf8](https://user-images.githubusercontent.com/1379744/133926929-cf2618bf-8673-4665-acf6-0fdec7146800.png)

when hovering the toolbar
![cdIo1ML8n4](https://user-images.githubusercontent.com/1379744/133926931-0a202bdb-1547-4ca7-bd30-953bdbc66e66.png)

**Comment by MrOtherGuy** [comment]
What OS do you have? I can't seem to reproduce this issue. Judging by the icon it looks like you are using Win10 (like me) so maybe something external triggers this problem. Quite odd I think.

At any rate, I tested your patch with all the styles I could think of that could be affected by it and couldn't find any problems so I'll gladly merge if it indeed fixes a problem that you are experiencing.

**Comment by JTBrinkmann** [comment]
Right, I consistently observed this using Windows 10 and Firefox 92.0 (64-Bit), even on a clean profile with no addons or settings changed, except for enabling userChrome.css and using 2a3c116 of your repo with **both** hide_tabs_toolbar and window_control_placeholder_support. Did you try to reproduce with both?

I would guess [hide_tabs_toolbar.css:18](https://github.com/MrOtherGuy/firefox-csshacks/blob/6214f6e/chrome/hide_tabs_toolbar.css#L18) is causing it. But changing this line would make it not being shown at all in fullscreen.

As far as I can tell, the `#navigator-toolbox` is hidden in fullscreen by Firefox setting `margin-top: -44px;` (depending on it's own height) which moves it offscreen. If `#window-controls` is set to `position: fixed`, it gets positioned at the top of the viewport regardless of the margin-top, which causes it to be shown on top of the page in my case. By changing it to `absolute` and making `#navigator-toolbox` a positioned element, `#window-controls` gets moved offscreen along with the rest of the toolbox.

Putting `position: relative` on #navigator-toolbox might have some unintended side effects, but I can't think of a legitimate use case and if there are some, users of _autohide_tabstoolbar_ or _autohide_toolbox_ would also notice them.
