### ISSUE TITLE
Some bugs in `navbar_tabs_oneliner_menu_buttons_on_right.css`

### ISSUE THREAD

**Issue by QuantumStatement** [MrOtherGuy/firefox-csshacks#149]
1. Tabs overflow menu button in fullscreen mode
![tabs-fullscreen](https://user-images.githubusercontent.com/35406698/136625655-23f988bd-8046-49e4-bb11-6b042be5a3d9.png)
2. Maybe it's not a bug, but some strange empty space appears when Overflow button is active
![empty](https://user-images.githubusercontent.com/35406698/136625695-266a09b9-b89f-4876-853e-8ac476678eed.png)

**Comment by MrOtherGuy** [comment]
Yeah, the first one is definitely a problem. But I'm not sure what's going on in the second. There is supposed to be *some* space there, but in your screenshot that looks kinda lot.

**Comment by MrOtherGuy** [comment]
I made some changes in [5cf3467](https://github.com/MrOtherGuy/firefox-csshacks/commit/5cf3467964f1f391934149ebfd60474465654873) to navbar_tabs_oneliner_menu_buttons_on_right.css which hopefully should fix fullscreen and private-browsing modes. I'm unsure what the deal with overflow button is though.
