### ISSUE TITLE
Multirow don't work anymore with F71 beta

### ISSUE THREAD

**Issue by onesolo** [MrOtherGuy/firefox-csshacks#15]
I even tried the latest multirow css from here but it doesn't work on latest beta. Can u fix that please?

**Comment by MrOtherGuy** [comment]
I'm not certain if the style itself is the problem. It still works on both - latest Developer Edition 71.0b3 and latest Nightly 72.0a1

**Comment by onesolo** [comment]
Sorry, I didn't appy right the code on userchrome.css file
