### ISSUE TITLE
non_floating_sharp_tabs interaction with tab_separator_lines

### ISSUE THREAD

**Issue by corobin** [MrOtherGuy/firefox-csshacks#151]
the current version of `non_floating_sharp_tabs` (#150) interacts suboptimally with `tab_separator_lines`

specifically, the area where the separator lines are located now stick out like a sore thumb in and around selected tabs

3 tabs selected:

![select-tabsep](https://user-images.githubusercontent.com/15662785/137068765-39d0fe3e-6c36-4a11-9551-2458b044a74f.PNG)

3 tabs selected, hover over middle selected tab:

![select-tabsep-hover](https://user-images.githubusercontent.com/15662785/137068867-4e461394-3868-432f-b7c0-6c64ec352582.PNG)

note the the separator lines do not appear around  hovered tabs so this leaves two thin lines of the background colour.

(both screenshots are on Fx93 default light theme)

unfortunately, i don't really have a good suggestion for how to improve this. it would probably involve either playing around with the selected tab colour (which is difficult since it should be constrained to the palette that the theme already has), or doing something to alter the tab separators to fit in more, or both.

sorry for the unhelpful suggestion, maybe just something to keep in mind to see if an elegant solution appears in the future.

thanks.

**Comment by MrOtherGuy** [comment]
Yeah. It's not very pretty. I don't really want to make things too complicated here because multiselecting tabs doesn't happen all the time. But I'll think about it if there is some clean solution to this.

I suppose the same issue happens on the previous version of the non_floating_sharp_tabs too right? It just isn't as visible?

**Comment by corobin** [comment]
Yes, i went back to check and with zoomed in and a colour picker you can see it existed in the previous version too, but wasn't very noticeable on the default theme.

7801318 looks fine with the tab separators, however, it now adds a 1px border between selected tabs when tab separators is not used.

using only non_floating_sharp_tabs

9ad96bb

![nfst_old_no_tsl](https://user-images.githubusercontent.com/15662785/137275310-c460d0e5-eb61-4cf2-963e-b565b13445ba.PNG)

7801318

![nfst_new_no_tsl](https://user-images.githubusercontent.com/15662785/137275349-1a999758-520f-40eb-91ec-c0c234227260.PNG)

if you revert non floating tabs to 9ad96bb, and then add the new lines (69-71) from 7801318 into the tab separator file, then it makes it look fine with only non floating tabs, or both non floating tabs and tab separator. however, it then adds an extraneous line if you only use tab separator, like this:

![modified_only_tsl](https://user-images.githubusercontent.com/15662785/137276668-ac57be13-1e04-4239-85c7-ea41a51a2709.png)

so that's not a solution either.

this is getting overly complicated. ultimately it's your decision what use cases you want to support. thanks for all your effort no matter what!

**Comment by MrOtherGuy** [comment]
Note, I went with this route partly because it also adds those borders without separator lines. So it is completely intentional, and IMO necessary because it adds some further contrast to multiselected tabs.
