### ISSUE TITLE
Tabs not appearing using multi-row_tabs.css

### ISSUE THREAD

**Issue by mimteatr** [MrOtherGuy/firefox-csshacks#153]
Hi!

As you can see in the image some tabs don't appear (top or bottom).

While adding tabs, the bottom ones don't appear completely but clicking in any of them, then strangely after a few seconds it scrolls down by itself and them the top ones don't appear completely and vice-versa.

![tabs not appearing](https://user-images.githubusercontent.com/36078037/139663050-f06f9d5b-06ab-4cdd-a546-761bf46eb40b.PNG)

**Comment by MrOtherGuy** [comment]
That will happen if you modify the height of tabs in some manner. Specifically, if you modify it in some way that the style isn't aware of. If you just modify `--tab-block-margin` and `--tab-min-height` then the style can adjust. But if you directly modify tab `min-height` or `margin-block` of tab-background, then you need to modify the style as well. 

The style computes the visible height of the rows like this: ` max-height: calc((var(--tab-min-height) + 2 * var(--tab-block-margin,0px)) * var(--multirow-n-rows))` so if the value of the variables does not match the actual size of the tabs, then you will face exactly the scenario that you have.

**Comment by MrOtherGuy** [comment]
Although, Slightly separate issue can happen if the newtab-button is inside the tabs strip like you seem to have. It may cause the rows to be 1px taller than they should be so the row height might not be exactly correct. I made a patch b6ae559 to remove bottom margin from the #tabs-newtab-button which fixes that issue.

**Comment by mimteatr** [comment]
The patch solved it, hurrah! Thanks again 🙏🌹

**Comment by mimteatr** [comment]
Hey, although I closed it yesterday, and since it's still related to **multi-row_tabs.css**, I thought you could help me a couple of questions?

How do I eliminate the extra space showing at the beginning and at the end of the Tab Bar?

![extra space tabbar](https://user-images.githubusercontent.com/36078037/139860743-a1293e42-f8a0-44b5-a917-2d9148cf1e20.PNG)

Also, you wrote inside the css ` /* You might want to move tabs-new-tab-button outside tabs toolbar for smoother behavior */`.  How do I do it?

Thanks!

**Comment by MrOtherGuy** [comment]
Normally you would just use `.titlebar-spacer{ display:none !important }` but I have a feeling it might not work with your custom setup.

> Also, you wrote inside the css /* You might want to move tabs-new-tab-button outside tabs toolbar for smoother behavior */. How do I do it?

Just go to customize mode and drag that button to some other location, like the main toolbar for example.

**Comment by mimteatr** [comment]
You're right, no change. 

So what do you propose to change the setup? I mean, I'd like to have the toolbars below the content still...

Here's my userChrome.css:
```
@import "./css/iconized_menubar_items.css"; /**/
@import "./css/vertical_popup_menubar.css"; /**/
@import "./css/autohide_menubar.css"; /**/
@import "./css/curved_tabs.css"; /**/
@import "./css/toolbars_below_content.css"; /**/
@import "./css/tab_close_show_on_hover_only.css"; /**/
@import "./css/multi-row_tabs.css"; /**/
/*@import "./css/aboutconfig_compact_appearance.css"; /**/

 findbar:not(:focus-within) {
  height: 0px !important;
  overflow: hidden !important;
}
#urlbar-container{ padding-block: 0px !important }

.titlebar-spacer{ display:none !important }
```


Also, strangely, the issue of yesterday still persists.

> Normally you would just use .titlebar-spacer{ display:none !important } but I have a feeling it might not work with your custom setup.

**Comment by MrOtherGuy** [comment]
I see. Yeah, because of autohide_menubar.css you need to increase specificity of your mod. So adding this to the end of all that should work:

```css
#TabsToolbar > .titlebar-spacer{ display: none !important; }
```

**Comment by mimteatr** [comment]
Solved! You're the champ! 👌🎉✌
