### ISSUE TITLE
Show page actions on URL bar hover

### ISSUE THREAD

**Issue by BWPanda** [MrOtherGuy/firefox-csshacks#159]
Currently with `page_action_buttons_on_hover.css` you need to hover over the area on the right to show the button(s). However I much prefer the solution used in the new `urlbar_icons_on_hover.css` where hovering over any part of the URL bar shows the icons. Can we do that here too?

**Comment by BWPanda** [comment]
Here's a PR: https://github.com/MrOtherGuy/firefox-csshacks/pull/160

**Comment by MrOtherGuy** [comment]
This is handled in 3246a70
