### ISSUE TITLE
[Suggestion]Tabs_on_Bottom

### ISSUE THREAD

**Issue by storm119** [MrOtherGuy/firefox-csshacks#16]
How about change the "toolbar order" in line 44 of Fx65_tabs_on_bottom.css to "0"...this will force "menubar" to stay on top...and we don't need this patch anymore Fx65_tabs_on_bottom_menubar_on_top_patch.css...? 
```
#titlebar{
-moz-box-ordinal-group: 2;
-moz-appearance: none !important;
}
```
to
```
#titlebar{
-moz-box-ordinal-group: 0;
-moz-appearance: none !important;
}
```
Or probably adding complete order rules....
```
print-preview-toolbar,
#printedit-toolbar,
#titlebar {
  -moz-box-ordinal-group: 0;
}
#navigator-toolbox #toolbar-menubar {
  -moz-box-ordinal-group: 1;
}
/* navigation toolbar */
#navigator-toolbox #nav-bar {
  -moz-box-ordinal-group: 2;
}
/* bookmarks toolbar */
#navigator-toolbox #PersonalToolbar {
  -moz-box-ordinal-group: 3;
}
/* 3rd party toolbars */
#navigator-toolbox toolbar {
  -moz-box-ordinal-group: 10;
}
/* tabs toolbar */
#navigator-toolbox #TabsToolbar {
  -moz-box-ordinal-group: 100;
}
````
Ps: tested on my Linux (Manjaro 18.1.2 Arch Gnome Testing branch) with FF70 + FF71 Developer Edition and worked just fine...at least on my side

Ps2: the complete order rules codes above inspired by Aris2-t2 (CTR) works

**Comment by storm119** [comment]
Edit: Sorry...spoke to soon need another codes to make em works right...I had alot customization codes which actually make above codes working on my side...my bad!

**Comment by storm119** [comment]
Update: after a little investigation...this code need to add to make above codes working correctly...
```
 #TabsToolbar {
  position: absolute !important;
  display: block !important;
  bottom: -2px !important;
  width: 100vw !important;
  border-bottom: none !important;
}
#tabbrowser-tabs {
  width: 100vw !important;
  margin-bottom: -1px !important;
  /* tabs gib me some space at left|right screen */
  -moz-margin-start: 4px !important;
  -moz-margin-end: 4px !important;
}

:root {
  --tab-min-height: 32px !important;
}
:root[uidensity="compact"] {
  --tab-min-height: 28px !important;
}
:root[uidensity="touch"] {
  --tab-min-height: 40px !important;
}

/* tab height */
#tabbrowser-tabs,
#TabsToolbar :-moz-any(.tabs-newtab-button,#tabs-newtab-button),
#tabbrowser-tabs > .tabbrowser-arrowscrollbox,
#tabbrowser-tabs[positionpinnedtabs] > .tabbrowser-arrowscrollbox > .tabbrowser-tab[pinned] {
  min-height: var(--tab-min-height) !important;
}
#main-window:not([chromehidden*="toolbar"]) #navigator-toolbox {
  padding-bottom: calc(0px + var(--tab-min-height)) !important;
}
.tabbrowser-tab {
  min-height: var(--tab-min-height) !important;
  border: none !important;
  -moz-box-sizing: border-box !important;
}
```

**Comment by MrOtherGuy** [comment]
Since you are doing basically ` #TabsToolbar { display: block !important; }` the -moz-box-oridinal-group on it will do absolutely nothing. If you are using the code in your last post then the whole code where you listed bunch of -moz-box-ordinal groups is totally irrelevant.

I would rather keep `#TabsToolbar` displayed as -moz-box (like it is currently) for easier compatibility with other modifications. Then, if someone really wants to have menubar shown on top it can be relatively easily hacked there with the menubar on top patch. And that should not have too many compatibility problems.
