### ISSUE TITLE
Remove top and bottom padding around tabs

### ISSUE THREAD

**Issue by FloppyDance** [MrOtherGuy/firefox-csshacks#163]
Hello!
Is there a CSS to remove the top and bottom padding around the tabs? 

![Screenshot (1311)_LI](https://user-images.githubusercontent.com/96717060/148363653-54e45cb2-2497-4a2d-9c9e-ef6ceae26f9b.jpg)

**Comment by MrOtherGuy** [comment]
A simple like `:root{ --tab-block-margin: 0 !important }` works for that.
