### ISSUE TITLE
curved_tabs.css black corners issue

### ISSUE THREAD

**Issue by FloppyDance** [MrOtherGuy/firefox-csshacks#164]
Hello!
I have a problem with curved_tabs.css. As you can see from the screenshot attached, the corners appear black instead of the same color of the tabs. How can I solve this problem?

![Screenshot (1312)](https://user-images.githubusercontent.com/96717060/148398708-b548252e-e193-48ed-a93f-2b50c045f48b.png)

**Comment by MrOtherGuy** [comment]
Go to about:config and set `layout.css.color-mix.enabled` to true.

**Comment by FloppyDance** [comment]
> layout.css.color-mix.enabled

Same result. They're black

**Comment by MrOtherGuy** [comment]
Hmmm... What Firefox theme are you using? And what OS?

**Comment by FloppyDance** [comment]
It's working! Is svg.context-properties.content.enabled resource consuming?

What should I do if I want to enable to separator between tabs?

Thank you!

**Comment by MrOtherGuy** [comment]
Resource consuming? No, Firefox internally uses it everywhere, but the pref needs to be flipped for other sources to use it.

It does make context-properties available for web-content too though which kinda opens a small fingerprinting vector. I doubt any websites *actually* abuse that, but it's theoretically possible.

For separators you can use [this style](https://github.com/MrOtherGuy/firefox-csshacks/blob/master/chrome/tab_separator_lines.css) which will require that color-mix pref that was mentioned earlier - or make that style not use color-mix and just hard-code the color to something you want. Color-mix is used to make the style derive the color of the line from the tab text-color of whatever theme you are using.
