### ISSUE TITLE
Tab color variable naming changes in FF96

### ISSUE THREAD

**Issue by Lahe** [MrOtherGuy/firefox-csshacks#165]
FF96 introduced some variable naming changes for tab line/border colors. Affects top line color of selected tabs in `non_floating_sharp_tabs.css`.

https://hg.mozilla.org/mozilla-central/diff/965bf155a9db49ce7ec1533b3b8eee2901a79d4e/browser/themes/ThemeVariableMap.jsm
```diff
-    "--tab-line-color",
+    "--lwt-tab-line-color",

-    "--tabs-border-color",
+    "--lwt-tabs-border-color",
```

**Comment by MrOtherGuy** [comment]
Indeed, good catch - thank you! This is done in 19fa8eb
