### ISSUE TITLE
autohide_main_toolbar.css: don't collapse the toolbar if appMenu-popup or other popups is open

### ISSUE THREAD

**Issue by oren64** [MrOtherGuy/firefox-csshacks#168]
When I press the hamburger button to open menu-popup, the toolbar collapse and move the menu-popup move up, making me press the wrong button on menu-popup.

Edit: if you can make that, it will not collapse on other popups like download button.

**Comment by MrOtherGuy** [comment]
Yeah, that would be great but can't really be done. Not unless you also accept that the toolbars will be shown when a website context menu is hovered.

**Comment by oren64** [comment]
Ok. Thanks
