### ISSUE TITLE
Using latest "autohide_menubar" - menubar not showing on maximized and covering top page when not maximized

### ISSUE THREAD

**Issue by mimteatr** [MrOtherGuy/firefox-csshacks#178]
Hello,

As the title says, using latest "[autohide_menubar.css](https://github.com/MrOtherGuy/firefox-csshacks/commit/0bc77cc51583133ff8279a286f5eae939d13f3e0)" 

The menubar covers the top of the page when the window is NOT maximized (mostly can't even see all text there):
https://imgur.com/a/460mgZn

Although there's a great thick bar on the top, but there's No menubar when window is maximized:
https://imgur.com/a/AHYyHJn

Can you please help?

Thanks

**Comment by MrOtherGuy** [comment]
I would guess the cause is that you are using several different styles that just are not compatible with each other. autohide_menubar.css is not supposed to hide other toolbars like in your screenshot.

**Comment by mimteatr** [comment]
I suppose you can't remember everyone that writes you, but I wrote you already in the past concerning other issues and told you that I'm using  YOUR css scripts, so how can they be incompatible???

My userChrome.css:
```
/* MrOtherGuy CSS */
@import "./iconized_menubar_items.css"; /**/
@import "./vertical_popup_menubar.css"; /**/
@import "./autohide_menubar.css"; /**/
@import "./compact_urlbar_megabar.css"; /**/
@import "./curved_tabs.css"; /**/
@import "./tab_close_button_always_on_hover.css"; /**/
@import "./toolbars_below_content.css"; /**/
@import "./multi-row_bookmarks.css"; /**/

/* MrOtherGuy: Remove bookmark star button on Page Actions/URL */
#star-button-box { display:none !important; }

/* MrOtherGuy: Make status bar draggable */
#status-text{ -moz-window-dragging: drag !important }

/* It_Was_The_Other_Guy: Reduce vertical size of menus */
:root{  --arrowpanel-menuitem-padding: 0.2em !important; }

/* Remove Facebook Container on Page Actions/URL */
#userContext-icons { display:none !important; }

/* Iconize bookmarks */
toolbarbutton.bookmark-item:not(.subviewbutton){ margin-inline: 0 !important; border-inline: 2px solid transparent }
toolbarbutton.bookmark-item:not(.subviewbutton):not(:hover) > .toolbarbutton-text{ display: none !important; }
```

**Comment by MrOtherGuy** [comment]
Yeah, it's better to list the styles you are using when opening a new issue, just to sure. I do remember you but I cannot remember what styles everyone is using and of course the set of styles one uses might be entirely different that it was is the past.

But anyway, on the topic of style compatibility. I do try to make the styles such they would be compatible with each other if possible and if adding such "compatibility layer" doesn't itself complicate things too much. That being said, there's no guarantee that styles will actually be compatible, and some styles are even fundamentally incompatible like for example multi-row_tabs.css and toolbars_below_content.css. And multi-row_tabs.css + nav-bar_tabs_oneliner.css probably won't work too well either together. I'm sure there are others too.

For your specific issue though. First, I updated autohide_menubar.css and toolbars_below_content.css for another reason - to make you able to drag the menubar to move the window. Though unrelated, you should still update the style. Then, uncomment [line 83](https://github.com/MrOtherGuy/firefox-csshacks/blob/master/chrome/toolbars_below_content.css#L83) in toolbars_below_content.css. It's more or less intended for this scenario even if now the menubar is not "static".

If the menubar still doesn't show up for you when in maximized windows, then you'd probably want to increase the value in [line 9 of autohide_menubar.css](https://github.com/MrOtherGuy/firefox-csshacks/blob/master/chrome/autohide_menubar.css#L9).

**Comment by mimteatr** [comment]
Your updated files actually solved it! 
Thank you 😊

BTW, is there a way to be informed of updates? An add-on or something like that? Although I'm subscribed to you, I don't get any mail about updates...

**Comment by MrOtherGuy** [comment]
Great! Although, the updates should not have changed the behavior at all, except to make it possible to drag the window from menubar. Thus, uncommenting line 83 should be necessary I would think. Then again, if it works then maybe don't touch it :) But it is odd...

I don't really know how you can get notified about changes to particular files though. Maybe github itself has some controls for it somewhere, but I don't know about it. I suppose you could certainly write an extension to do that, and maybe one already exists, but I didn't find anything on a quick search at addons store.

**Comment by mimteatr** [comment]
Thank you 😊
