### ISSUE TITLE
Thank you, thank you, thank you!!!

### ISSUE THREAD

**Issue by SanderBouwhuis** [MrOtherGuy/firefox-csshacks#18]
Dear MrOtherGuy,

I just had a scare after Firefox updated to v71 and I lost my multi-row tabs!
I went (back) to this repository and found updated versions. Now it works again!

THANK YOU, THANK YOU, THANK YOU!!!

PS
I use the following in my userChrome.css file:
```
window_control__placeholder_support.css
overlay_menubar.css
Fx65_tabs_on_bottom.css
multi-row_tabs.css
```

**Comment by MrOtherGuy** [comment]
You're welcome. Though I'm not sure how overlay menubar.css is supposed to work for you (perhaps you have native titlebar enabled?). It's busted and I can't think of a good proper fix for it.

**Comment by SanderBouwhuis** [comment]
Well, it does work for me.
However, I just tried it without and the only difference is that the menu now appears between addressbar line and the tabs line. Since that is fine for me, I have removed it.

My settings file: [userChrome.txt](https://github.com/MrOtherGuy/firefox-csshacks/files/3931896/userChrome.txt)

This is the result of that settings file:
![Screenshot](https://user-images.githubusercontent.com/10495173/70319639-0ed54000-1823-11ea-9a5a-79168917e9ab.png)

**Comment by MrOtherGuy** [comment]
Closing since the one issue I noted (broken overlay_menubar) should now be fixed

**Comment by patfla** [comment]
Hi - FF 71.0.

I have the userChrome.txt set up as userChrome.css in my profile folder, for FF 71.0, but multirow isn't working.  My file is verbatim the file above but I'll attach it anyway.

[userChrome.txt](https://github.com/MrOtherGuy/firefox-csshacks/files/3947402/userChrome.txt)

**Comment by SanderBouwhuis** [comment]
@patfla 
Maybe a silly question, but you did name the file userChrome.css right? The .txt is only because this stupid forum doesn't allow *.css files.

**Comment by MrOtherGuy** [comment]
Only thing that is obvious to me is that the first portion if the code - ...placeholder_support.css - is not up to date. Being out of date shouldn't cause multi-row to stop working though.

**Comment by MrOtherGuy** [comment]
Tested again. I literally copied everything from the file you linked straight to (empty) userChrome.css file and hit save and the ran Firefox. 

Multi-row tabs seems to work like it is supposed to and bookmarks toolbar is in correct place. I honestly can't think of anything why it wouldn't work for you, assuming that Firefox is reading the file in the first place.

**Comment by patfla** [comment]
Yes, the file is correctly named (.css - not .txt).  And in the correct location - as given by about:support.

Is there some way of figuring out if the file is getting properly loaded at startup?  Thanks.

**Comment by patfla** [comment]
A question: extensions.legacy.enabled (= true) is the one about:config param that one needs to set?

https://imgur.com/a/HbcAHk0

**Comment by MrOtherGuy** [comment]
No, the one pref that needs to be set is `toolkit.legacyUserProfileCustomizations.stylesheets`

Also note that about:support does not link you to the correct folder. It does open the profile folder. But you need to create a folder called `chrome` to that golder and then put userChrome.css inside the newly created chrome folder.

**Comment by patfla** [comment]
I set toolkit.legacyUserProfileCustomizations.stylesheets to true and now I have multirows.

Thanks for your help - and the code.
