### ISSUE TITLE
autohide_toolbox.css not working on version 99.0 anymore

### ISSUE THREAD

**Issue by Itamiii** [MrOtherGuy/firefox-csshacks#185]
Sadly, the autohide toolbox doesn't seem to work on Firefox version 99.0 anymore.
While it still hides the toolbox, moving the mouse to the top of the screen / browser window does not trigger the toobox to reappear anymore. Causing it to stay hidden, which makes browsing impossible.

As this tool has become aesthetically essential for me, I hope that this can be fixed. 
Thank you for your time and excellent work.

**Comment by MrOtherGuy** [comment]
What OS do you have? And just to be sure, does the issue persist with latest version of autohide_toolbox.css?

**Comment by Itamiii** [comment]
> 

I'm on the latest Windows 10 x64 enterprise. 
The issue does persist in the latest version of autohide_toolbox.css as well as a previous legacy version I tested.
Also, this issue is new, and I have never experienced it before today.

**Comment by MrOtherGuy** [comment]
Alright, I'll check later if I can reproduce it somehow.

 One other that can be pretty important with that style; what is your Windows dpi or scaling set to? 100% 125% 150% or something like that in Windows options.

**Comment by Itamiii** [comment]
My scale is set to 200% as I'm on a 3840 x 2160 display. 
I have no other options enabled which affect the display scaling behavior.

**Comment by MrOtherGuy** [comment]
Thanks for the information. Yes, I can reproduce with 175% and 200% scaling when bookmarks toolbar is hidden. 3241bdb fixes that issue - at least on my system, please test the latest version and see how it goes.

**Comment by Sobakaa** [comment]
Stopped working for me today (guess firefox updated), but after downloading latest toolbox it now works as it should. 175% scale, 3840x2160 display settings. 
That was even prior to the latest updates couple minutes ago, though, so cannot confirm whether these changes do anything.

**Comment by MrOtherGuy** [comment]
@Sobakaa that might be explained by the fact that if bookmarks toolbar was shown (it's by default shown in newtab page) then the "activation area" of the toolbox is just big enough to trigger. So if you tested on newtab page it might have worked. Or, at least on my tests the activation actually does work fine even without bookmarks toolbar, but the area is 1px below the top of the screen. So you may have just hit it by accident.

Or something like that. Anyway, this style is very dpi dependent since the activation is more or less pixel perfect on maximized windows.

**Comment by Itamiii** [comment]
My scale is set to 200% as I'm on a 3840 x 2160 display. 
I have no other options enabled which affect the display scaling behavior.

> Thanks for the information. Yes, I can reproduce with 175% and 200% scaling when bookmarks toolbar is hidden. [3241bdb](https://github.com/MrOtherGuy/firefox-csshacks/commit/3241bdbfe1f9f0a04238cc3a90c5bab3469c1a21) fixes that issue - at least on my system, please test the latest version and see how it goes.

Yes, I have just tested the latest version, and it is fixed now.
I forgot I also had the bookmark's toolbar hidden.

Thank you so much for your time and work.
You are a life saver!

**Comment by MrOtherGuy** [comment]
Alright, thanks for confirming!
