### ISSUE TITLE
privatemode_indicator_as_menu_button.css doesn't show icon

### ISSUE THREAD

**Issue by BWPanda** [MrOtherGuy/firefox-csshacks#189]
When using `privatemode_indicator_as_menu_button.css`, it's not showing the icon:

![image](https://user-images.githubusercontent.com/2385329/167251153-593ecb82-f7ca-401e-8586-de5c199b1288.png)

This is the same issue as [previously reported](https://github.com/MrOtherGuy/firefox-csshacks/issues/142#issuecomment-915470853), but that was apparently fixed...

I'm using the latest (as of the time of writing) version of the git repo in Librewolf v100.0 on Manjaro Linux.

**Comment by MrOtherGuy** [comment]
Thanks for reporting, this is now fixed with 7d08324
