### ISSUE TITLE
autohide_toolbox.css not working in Firefox 101.0 

### ISSUE THREAD

**Issue by venkatav1** [MrOtherGuy/firefox-csshacks#191]
The toolbox does not appear when the mouse is hovered at the top of the firefox window. It works in the full screen mode though. I think there is an addition of new empty space in the new version of firefox 101.0

Can any body please fix it?

**Comment by MrOtherGuy** [comment]
This is actually very awesome. I can now remove whole bunch of Windows only cody from bunch of stylesheets.

**Comment by venkatav1** [comment]
> 

I did not understand. Is it possible to fix it back to the previous working mode?

**Comment by MrOtherGuy** [comment]
Sure. I'll fix it shortly - The same change applies to dozens of other styles so I'm going to fix them all at once.

**Comment by MrOtherGuy** [comment]
This should now be fixed. Just grab the latest version and report how it goes please.

**Comment by venkatav1** [comment]
> This should now be fixed. Just grab the latest version and report how it goes please.

Working flawlessly. Thanks a lot!
