### ISSUE TITLE
[Improvement] Add images and GIFs of userChrome.css tweaks in action

### ISSUE THREAD

**Issue by SocietasEvanescentes** [MrOtherGuy/firefox-csshacks#193]
While a lot of these have clear intentions, some are a little vague in terms of UI, and I'd think it would benefit those who use this repo to add images and GIFs of userChrome.css in action.

**Comment by MrOtherGuy** [comment]
What kind of presentation you imagine those images would have? As in, a page with long list of images in readme or separate page linked from readme? Or just image files in a folder? I suppose I could add previews to tag browser page.

I'm not against such images in principle, but I'm not sure if they would provide enough value to be worth the effort.

**Comment by Rex501st** [comment]
> What kind of presentation you imagine those images would have? As in, a page with long list of images in readme or separate page linked from readme? Or just image files in a folder? I suppose I could add previews to tag browser page.
> 
> I'm not against such images in principle, but I'm not sure if they would provide enough value to be worth the effort.

Apologies, never got a notification for this; I'd add them right under the .css file of each.
