### ISSUE TITLE
transparent buttons On custom backgrounds Themes

### ISSUE THREAD

**Issue by YoungDDick** [MrOtherGuy/firefox-csshacks#195]
![NgI0upiSVM](https://user-images.githubusercontent.com/74034556/176680669-bb911cdc-4fbc-4d0b-b26e-0a6873622516.png)

**Comment by YoungDDick** [comment]
How Can I Fix It?

**Comment by MrOtherGuy** [comment]
Uhh, what am I looking here? Is that caused by some specific style or on specific theme or what?

And what do you mean by "transparent buttons"?

**Comment by YoungDDick** [comment]
![ICHlGDCqsS](https://user-images.githubusercontent.com/74034556/176719721-88b5c538-71a7-4ea9-81b9-67e768d3d6c4.gif)

**Comment by MrOtherGuy** [comment]
Okay. But is that caused by some specific style from this repository or is your Firefox normally like that even without any custom styles? 

And what OS do you have? And what is the theme you see that happen with? Although, if that issue happens even without any custom styles then this issue tracker isn't really a correct place to fix it.

**Comment by YoungDDick** [comment]
I Have Win 11 With Custom Theme And I Using Your Css UserChrome.
If I Apply Theme Without Custom Background Button Is Normal. But When I Applying Any Theme With Custom BG Button Is Invisible

**Comment by MrOtherGuy** [comment]
Right, but do notice that this repository has over 150 styles, so which one is the causing the issue?

**Comment by MrOtherGuy** [comment]
Sorry, but if you are saying that any theme you install from addons store which has background-image causes that issue then that is not related to this repository.

But, if the issue only happens when you use some style from this repository then I need you to tell me which style that is.

**Comment by YoungDDick** [comment]
I Install This Theme : https://addons.mozilla.org/en-GB/firefox/addon/beautiful-gx-fantasy/

**Comment by YoungDDick** [comment]
Some Themes Didnt Have This Issue

**Comment by MrOtherGuy** [comment]
Okay, so it happens only with some themes. Still, you need to tell me which specific style from this repository you are using.

**Comment by YoungDDick** [comment]
![image](https://user-images.githubusercontent.com/74034556/176731729-4aa69a51-e643-4ccf-b039-16382fd69e67.png)

**Comment by MrOtherGuy** [comment]
Okay. Your style is just outdated, update it to [current version.](https://github.com/MrOtherGuy/firefox-csshacks/blob/master/chrome/window_control_fallback_for_custom_windows_theme.css)

**Comment by YoungDDick** [comment]
Fixed
