### ISSUE TITLE
Multi-row tabs pinned tab width

### ISSUE THREAD

**Issue by sonofevil** [MrOtherGuy/firefox-csshacks#197]
Regarding https://github.com/MrOtherGuy/firefox-csshacks/blob/master/chrome/multi-row_tabs.css

Since dragging stops working once pinned tabs go to multiple rows, it makes sense to me to attempt to delay that point.

Now, since pinned tabs only need to display the favicon, in theory they don't need to be much wider than the favicon.

So I wrote this:

```
/*Make pinned tab width behave similar to unpinned tab width. Preserves draggability for longer.*/

.tabbrowser-tab[pinned] {
  flex-grow: var(--multirow-tab-dynamic-width);
  max-width: 32px;
}

.tab-content[pinned] {
  padding: 0px !important;
  
}

.tab-label-container[pinned] {
  display: none;
}
```

Now the width starts shrinking once the tabs fill the row, just like normal tabs, to delay line-breaking.

My only problem with this solution is that I cannot figure out how to center the favicon.

**Comment by MrOtherGuy** [comment]
You can make the icon centered by applying -moz-box-pack: center to tab content. So:

```css
.tab-content[pinned] {
  padding: 0px !important;
  -moz-box-pack: center;
}
``` 

But I don't really want to apply to include this toe to multi-row_tabs.css because it is not supposed to actually alter the size of tabs.

**Comment by sonofevil** [comment]
Thank you. I guess I'll release a patch then.
