### ISSUE TITLE
navbar_tabs_oneliner.css problems on MacOS Firefox

### ISSUE THREAD

**Issue by fsangel** [MrOtherGuy/firefox-csshacks#2]
Hello, 

I have a problem with navbar_tabs_oneliner.css on MacOS (Firefox 65.0). After applying in normal view (not full screen) buttons "Close", "Min" and "Full" located in the middle of navbar (should be on the left corner). But when in full screen - there is no problem. Pics are attached.

How i can solve the issue? Thanks!

Normal <img width="1144" alt="normal" src="https://user-images.githubusercontent.com/47364899/52295671-fbf9a100-29ae-11e9-9f65-c8adab510bd7.png">
Full <img width="1038" alt="full" src="https://user-images.githubusercontent.com/47364899/52295684-0451dc00-29af-11e9-8195-37e9b3bd71ff.png">

**Comment by MrOtherGuy** [comment]
I can only guess but this might work:

    :root:not([sizemode=fullscreen]) #nav-bar{ padding-left: calc(138px + var(--window-drag-space-width)) }
    .titlebar-buttonbox-container{ position: fixed; left: 0px; z-index: 3; }

Unfortunately I have no way to test this since I don't have Mac system available. I will add this as something like mac_window_control_patch.css if it works since several stylesheets expect window controls to be on the right-hand side like on Windows.

**Comment by fsangel** [comment]
From now the controls on the left, but hiding the <-> buttons 

<img width="421" alt="2019-02-06 19 19 44" src="https://user-images.githubusercontent.com/47364899/52341483-40d01700-2a45-11e9-999a-d5d9f17819ab.png">

**Comment by fsangel** [comment]
@MrOtherGuy Thank you. After this code the controls on the left now. But with big space. 
<img width="409" alt="2019-02-06 19 37 31" src="https://user-images.githubusercontent.com/47364899/52342127-17b08600-2a47-11e9-8e36-47af1325a516.png">

I tried replace
`--window-drag-space-width: 20px}
`
with
`--window-drag-space-width: -65px}
`
so now 
<img width="293" alt="2019-02-06 19 41 12" src="https://user-images.githubusercontent.com/47364899/52342149-2f880a00-2a47-11e9-97c8-59a18ad6cb85.png">

but it works with glitches
![ezgif com-video-to-gif](https://user-images.githubusercontent.com/47364899/52342449-02882700-2a48-11e9-88da-89b967907a3a.gif)

**Comment by MrOtherGuy** [comment]
You should rather modify the `138px` bit inside the calc function. I just picked 138px since that's how wide window controls are on Win10 but that's obviously way too much for Mac. So change that to something like 60px but keep the `--window-drag-space-width` at 0px or positive. There isn't a technical reason for this, the drag space meaning is  just more clear this way.

But I don't really have a good idea why nav-bar padding changes are "delayed" like that. It sort of looks like what would happen if nav-bar had delayed padding transition - but I really doubt that this is the case. I would guess that Firefox instead sets the sizemode attribute shortly after the animations have finished. So  in that case you might have better luck by replacing `:root:not([sizemode="fullscreen"])` with `:root:not([inFullscreen])`

**Comment by fsangel** [comment]
Just set for `--window-drag-space-width` 0px, replaced `:root:not([sizemode="fullscreen"])` with `:root:not([inFullscreen])` and set to 72px `#nav-bar{ padding-left: calc(72px` and now it's perfect as should be!

<img width="277" alt="2019-02-07 13 44 32" src="https://user-images.githubusercontent.com/47364899/52394982-fc915500-2ade-11e9-8413-bffd9b0cdb69.png">

Thank you!

**Comment by MrOtherGuy** [comment]
Alright, I rewrote bunch of stylesheets to hopefully handle Mac-style window controls on left - including navbar_tabs_oneliner.css

They now require a shared stylesheet, `window_control_placeholder_support.css` which should handle window-controls on left and right rules. I've done some extensive testing on windows and things seem to behave just like before (with some minor edge case fixes) but I would like to know if it causes trouble on Mac.

**Comment by fsangel** [comment]
After applying `window_control_placeholder_support.css` and `navbar_tabs_oneliner.css` the window is look like on pic:

<img width="537" alt="2019-02-10 20 42 11" src="https://user-images.githubusercontent.com/47364899/52534503-d8e73c80-2d74-11e9-85a8-5ce8686d1669.png">

**Comment by MrOtherGuy** [comment]
Right, Two things I would like to know about:

What is the pref "layout.css.osx-font-smoothing.enabled" set to?

And what if you remove this bit from window control support file: `[tabsintitlebar="true"]`

**Comment by fsangel** [comment]
pref "layout.css.osx-font-smoothing.enabled" set to "true" by default

Nothing changed after removing [tabsintitlebar="true"] from window control support file.

**Comment by MrOtherGuy** [comment]
Turns out that I had failed to delete all the old window placeholder codes from navbar_tabs_oneliner.css
So it overrode the rules with Windows/window-controls-on-right style.

Should be all good (well, better at least) now.

**Comment by fsangel** [comment]
Looks better now, but need less free space between controls and <-

<img width="341" alt="2019-02-13 21 05 12" src="https://user-images.githubusercontent.com/47364899/52717238-409ac300-2fd3-11e9-960d-9ca065711f86.png">

**Comment by MrOtherGuy** [comment]
Great! The ...placeholder_support.css defaults to 24px space between but you are free to modify it. I think no-extra-space is not a good default since that space is pretty useful most of the time.
