### ISSUE TITLE
[Question] How to use Autohide Main Toolbar only when there's one tab.

### ISSUE THREAD

**Issue by Adityashaw** [MrOtherGuy/firefox-csshacks#204]
All the components work great but I have this one doubt:

I want to hide the main toolbar when there is *only one tab* in the window (much like how the hide tab with one tab works). I am not interested in hiding when there are more than one tabs.

Is this achievable? Can you guide on how to do so?

My current `userChrome.css`:
```css

/* Import your desired components first */

/*@import url(chrome/window_control_force_linux_system_style.css);
*/
@import url(chrome/linux_gtk_window_control_patch.css);

@import url(chrome/window_control_fallback_for_custom_windows_theme.css);
@import url(chrome/autohide_main_toolbar.css); /* want to do this for one tab only*/
@import url(chrome/tab_close_button_always_on_hover.css);
@import url(chrome/tab_loading_progress_throbber.css);
@import url(chrome/button_effect_scale_onclick.css);
@import url(chrome/hide_toolbox_top_bottom_borders.css);
@import url(chrome/hide_tabs_with_one_tab.css);
/* Apply your custom modifications after imports */
```

PS: I have disabled title bar as well.

**Comment by Adityashaw** [comment]
Can you please suggest what would be the `css` for selecting `nav-bar` if we assume the title content start with, say, `View`?

I understand this would select any `nav-bar` which starts with `View` but that's fine.

**Comment by MrOtherGuy** [comment]
You can't use the title content directly because of the way the window title is stored. But you can use the title prefix which can be set with extensions. (Firefox doesn't normally use the prefix by itself).

You would use the prefix like so:

```css
:root[titlepreface="View"] #nav-bar{
  background: #f00 !important;
}
```

**Comment by Adityashaw** [comment]
Thanks a lot! I will look into it.
