### ISSUE TITLE
hide_tabs_with_one_tab - Not working on FF Dev v106 b6

### ISSUE THREAD

**Issue by TraceGroot** [MrOtherGuy/firefox-csshacks#210]
On FF Dev Edition v106 b6, hide_tabs_with_one_tab does not work properly.

While the tabs themselves are hidden, the new tab button remains on its own empty line on the toolbar.

**Comment by MrOtherGuy** [comment]
I feel thia may actually be related to Firefox View-button and its associated hidden "tab" as [descrided here](https://github.com/MrOtherGuy/firefox-csshacks/issues/207#issuecomment-1257511354)

**Comment by TraceGroot** [comment]
Aha!  Yes, you are absolutely correct.

Thank you!

**Comment by MrOtherGuy** [comment]
Thanks for confirming. 

Lets leave this issue open for now, since it would be ideal to let this work even if Firefox View is enabled. Not sure if that is possible though.

**Comment by FeralHedgehog** [comment]
There's a similar issue with the new Private Browsing indicator:
![image](https://user-images.githubusercontent.com/24353657/196816566-07022516-a606-44aa-8337-081a2d21f671.png)
It can be disabled by setting `browser.privatebrowsing.enable-new-indicator` to false in about:config

Sorry if this is the wrong place to post this - just wanted to save others some time.

**Comment by MrOtherGuy** [comment]
Thanks. On related note, that style may have to be completely rewritten for 108 - and I'm not sure if it's even possible to make it work there.
