### ISSUE TITLE
multi-row_tabs not working on Waterfox G5.0

### ISSUE THREAD

**Issue by TheDutchJewel** [MrOtherGuy/firefox-csshacks#211]
[multi-row_tabs](https://github.com/MrOtherGuy/firefox-csshacks/tree/master/chrome/multi-row_tabs.css) works fine with Firefox and Waterfox G4.x.

But it doesn't work with the new [Waterfox G5.0](https://www.waterfox.net/download/).

Is this an issue to be solved by the csshack, or by Waterfox?

**Comment by MrOtherGuy** [comment]
I don't test compatibility with any third-party Firefox builds, but generally the styles should work if said build is sufficiently similar to Firefox. That being said, in [Waterfox changelog](https://www.waterfox.net/docs/releases/G5.0) there's this bit:

> If you use custom CSS and JS, you will want to disable Waterfox theme changes by toggling userChrome.theme.enable to false.

So presumbly multi-row_tabs.css would work if you set that pref to false.

**Comment by TheDutchJewel** [comment]
Thanks for this solution, it works fine!
