### ISSUE TITLE
`autohide_sidebar`: Header does not expand

### ISSUE THREAD

**Issue by jtagcat** [MrOtherGuy/firefox-csshacks#213]
![image](https://user-images.githubusercontent.com/38327267/194594308-bdfa3e9d-8580-40b1-b1b9-ecdb1d055623.png)

since september

**Comment by MrOtherGuy** [comment]
I pushed a fix for this in [53526aa](https://github.com/MrOtherGuy/firefox-csshacks/commit/53526aa76eb8774e413226a98e701dbddaa5b1f8)
