### ISSUE TITLE
vertical_bookmarks_toolbar.css does not work properly in full screen

### ISSUE THREAD

**Issue by sahinakkayadev** [MrOtherGuy/firefox-csshacks#218]
I am using `vertical_bookmarks_toolbar.css` and when I go to full screen, it looks like the items in the toolbar disappears as it should but it leaves an empty space. Here are 2 screenshots for you to see the problem:

![normal](https://user-images.githubusercontent.com/32161460/197243140-f91eacb9-e66b-4110-9f00-4bc2b63ea926.png)
![full](https://user-images.githubusercontent.com/32161460/197243160-e93ee805-e827-4b29-a674-aa2cbb879923.png)

Can this be fixed?

**Comment by MrOtherGuy** [comment]
Yeah, thanks for reporting. This should be fixed with 9d90aab which also fixes the layout for Firefox 107+ which was completely broken.

**Comment by sahinakkayadev** [comment]
It works, thanks! 

Just for the records, the toolbar disappears after transition to fullscreen animation finished (i.e. after the top bar completely disappears) This is OK for me, especially with #217, I don't notice anything at all.
