### ISSUE TITLE
Multi-Row Bookmark css Stopped working after new Firefox Update

### ISSUE THREAD

**Issue by xbabyx** [MrOtherGuy/firefox-csshacks#22]
Hello,

Is there anything we can do to update the code to get it to work again? they just updated Firefox and suddenly it's not working anymore.

I have literally 72 Bookmarks on 4x Rows in total :( it's too much to go through.

Love this feature, hope you can help.

Thank you.

**Comment by MrOtherGuy** [comment]
That style appears to work just fine on both Firefox 71 and even latest Nightlies for me.

Is it possible that Firefox isn't loading your userChrome.css file at all? Such as if your profile got reset or the pref `toolkit.legacyUserProfileCustomizations.stylesheets` is set to false?

**Comment by xbabyx** [comment]
> 
> 
> That style appears to work just fine on both Firefox 71 and even latest Nightlies for me.
> 
> Is it possible that Firefox isn't loading your userChrome.css file at all? Such as if your profile got reset or the pref `toolkit.legacyUserProfileCustomizations.stylesheets` is set to false?

Thanks for replying, after the update I was logged out of Firefox and you're correct _toolkit.legacyUserProfileCustomizations.stylesheet_ was set to "False". I have logged in to Firefox now and made "toolkit.legacyUserProfileCustomizations.stylesheet" TRUE.

However that removed the arrows on the side and did not give me extra lines even though the bookmarks exist. (As I mentioned I've got about 70+ so it's about 4 lines.)

Here's a screenshot
![Screenshot_1](https://user-images.githubusercontent.com/45896748/70805229-18315000-1dc1-11ea-82c2-76a333baeb5c.png)

I tried restarting Firefox, deleting Bookmarks, creating new one it didn't  fix the issue. 
![Screenshot_2](https://user-images.githubusercontent.com/45896748/70805292-3e56f000-1dc1-11ea-9e69-2ca31980ff5f.png)

**Comment by MrOtherGuy** [comment]
Unfortunately I don't really have any further ideas. I mean, the arrow (all bookmarks button) is hidden on purpose since it's not supposed to be used when all your bookmarks expand to multiple rows - or so they should.

I tested with about 40 bookmarks and a narrow window which creates just over 7 (3 of which are visible and the rest appear on scroll) rows and they worked fine.

I suppose there could be some win7 specific rules in Firefox that causes behavior to be different for you but honestly I find that hard to believe.

Just to be clear, does your userChrome.css file contain anything except the contents of multi_row_bookmarks.css file?

**Comment by xbabyx** [comment]
I've had some different lines, went to your code and updated mine and it's now working perfectly. Thank you for the fast response <3 love this feature!

**Comment by xbabyx** [comment]
Sorry to re-open this, but apperantly on my laptop, it's only showing 3 lines and I have to scroll down for the 4th. Where on my PC 3x lines is more than enough to have all Bookmarks in them.

Is there a way to make the 4th line display without the need of scrolling down for it? possible to edit something with the code to make that happen?

**Comment by MrOtherGuy** [comment]
That is literally the purpose of line 4 - which says:

    --multirow-bmb-n-rows: 3; /* Control how many rows are shown before scrolling */

**Comment by MrOtherGuy** [comment]
I'm closing this, feel free to re-open if the `--multirow-bmb-n-rows` variable does not work for some reason.
