### ISSUE TITLE
Firefox 88 vi Firefox 108 or106

### ISSUE THREAD

**Issue by kolor33** [MrOtherGuy/firefox-csshacks#220]
Hi Team 
I would like ask if is possible put for Firefox 108 or106 tab like was in Firefox 88.
Only tab connect split area .Also the same color.

Firefox 88 has ---4,5cm 
Firefox 106-108 has --5.5cm 

Picture show it .
![1](https://user-images.githubusercontent.com/32041737/200129899-9072cca5-3206-4db8-a999-5d7760a46339.jpg)

**Comment by MrOtherGuy** [comment]
There is [this style](https://github.com/MrOtherGuy/firefox-csshacks/blob/master/chrome/non_floating_sharp_tabs.css)

If you want to change size of things then you can go to about:config and set `browser.compactmode.show` to true and then activate compact density from customization mode. 

As for colors, you can use any theme you like from addons store. [This one looks pretty close to what you have in your screenshot](https://addons.mozilla.org/en-US/firefox/addon/windows-10-default-blue/)

**Comment by kolor33** [comment]
Yes this is works nice .May I ask you last question .It is possible fill my icon in new Firefox for black color only icon .

![2](https://user-images.githubusercontent.com/32041737/200132553-db9f2175-6cc9-436e-8bd9-58bc3608ebfa.jpg)

**Comment by MrOtherGuy** [comment]
> It is possible fill my icon in new Firefox for black color only icon .

Sorry, but I don't understand what you are asking.

**Comment by kolor33** [comment]
You see small folders into tab new Firefox has white inside.I want to fill with black .This small icon.Do you see different .??

![3](https://user-images.githubusercontent.com/32041737/200132747-1526b09b-1c97-442c-b9a5-55c26f4bc935.jpg)

**Comment by kolor33** [comment]
![4](https://user-images.githubusercontent.com/32041737/200132809-23ef6fa3-8265-4178-8c1f-e94ac28f3021.jpg)

**Comment by MrOtherGuy** [comment]
You would need to find a custom icon you want to use. But once you have that then you can use this CSS to make Firefox use it:

```css
.bookmark-item[container]{
  list-style-image: url("icon.svg") !important;
}
```

In this case you would have your custom icon saved as "icon.svg" int the same folder where your userChrome.css is.

**Comment by kolor33** [comment]
This code can I also use for green padlock ssl fill all icon .????? not as new Firefox has .

**Comment by MrOtherGuy** [comment]
You cam make the verified padlock green like this:

```css
#identity-box[pageproxystate="valid"].verifiedDomain #identity-icon{
  fill: green;
}
```

But similarly to bookmark icons, since the icons have different visual style nowadays, you can't use CSS to make the insides of that padlock green. Again you need to create your custom icon for that.

**Comment by kolor33** [comment]
Thanks you a lot but really I do not know where I find that small icon icon.svg.The old firefox 88 do not have this inside .Location ???

**Comment by MrOtherGuy** [comment]
I don't have old Firefox installed, so if you want to use that same old icon file then you need to find it yourself. You can use [browser toolbox](https://firefox-source-docs.mozilla.org/devtools-user/browser_toolbox/index.html) to inspect the UI document and find its `chrome://` address, then input that address to urlbar to open it and then save the image. But I can't do that for you.

In the off-chance that the old image is stored in same address than what it is currently then the address would be `chrome://global/skin/icons/security.svg`

**Comment by kolor33** [comment]
Yes this works But icon not full of back color inside .??
jar:file:///C:/Program%20Files/Firefox%2088/omni.ja!/chrome/toolkit/skin/classic/global/icons/folder.svg

![5](https://user-images.githubusercontent.com/32041737/200134179-84144303-a399-4d72-ae45-a1c33f17773c.jpg)

**Comment by MrOtherGuy** [comment]
Open the file and save a copy of it into your chrome folder. I doubt Firefox allows you to link to *another* jar archive.

Also, you must use `!important` tag in your userChrome.css when trying to override the original list-style-image.

**Comment by kolor33** [comment]
Thanks you a lot .This is amazing support.Respects !!!
