### ISSUE TITLE
Close button needs reformatting | floating_findbar_on_top.css | FF Nightly [108]

### ISSUE THREAD

**Issue by yokoffing** [MrOtherGuy/firefox-csshacks#223]
https://github.com/MrOtherGuy/firefox-csshacks/blob/master/chrome/floating_findbar_on_top.css

![find_close](https://user-images.githubusercontent.com/11689349/201947780-af8c9cdf-8127-4549-bbaa-ac33fedf7840.png)

**Comment by MrOtherGuy** [comment]
Thanks for heads-up, this should be fixed in bf81ba7

**Comment by yokoffing** [comment]
Thank you for the quick work!
