### ISSUE TITLE
autohide_sidebar Header at the top of the sidebar firefox 107

### ISSUE THREAD

**Issue by chavely1** [MrOtherGuy/firefox-csshacks#224]
I've just updated firefox from 106 to 107 
I have enabled only two .css files:
- autohide_sidebar.css
- autohide_toolbox.css

And this ugly bug happens

https://user-images.githubusercontent.com/118322114/202065911-6a7e84a8-4e21-45d0-85c6-b76671a50e2c.mp4

**Comment by MrOtherGuy** [comment]
This should be fixed with b088051
