### ISSUE TITLE
hide_tabs_with_one_tab.css issues on Firefox 108.0b3

### ISSUE THREAD

**Issue by MiliAxe** [MrOtherGuy/firefox-csshacks#228]
I'm sorry if this is a duplicate but I'm experiencing issues with my userChrome.css from https://github.com/rockofox/firefox-minima which uses hide_tabs_with_one_tab.css
Note that this issue appeared after upgrading to Firefox 108.0b3 and was fine on 107.0b3

# Description
It seems as if there is some sort of padding added to the bottom of my tabs:
![image](https://user-images.githubusercontent.com/55515322/202846177-ce892b3f-1c92-482e-b9f0-9fa88f00dcc6.png)
note that I have manually increased `max-height` in `#TabsToolBar` to find this issue, with the default values, the bar would be empty and would only appear when alt was pressed:
![image](https://user-images.githubusercontent.com/55515322/202846234-5307ea01-8d99-4baa-8ad5-2986c8cc782e.png)

# What I have tried
- Setting `browser.tabs.tabmanager.enabled` to false
- Setting `layout.css.moz-box-flexbox-emulation.enabled` to true

Thanks for the great CSS

**Comment by MrOtherGuy** [comment]
Try using [hide_tabs_with_one_tab_w_window_controls.css](https://github.com/MrOtherGuy/firefox-csshacks/tree/master/chrome/hide_tabs_with_one_tab_w_window_controls.css) instead. I don't know how to or if it's even possible to make base hide_tabs_with_one_tab.css work in 108.

**Comment by MiliAxe** [comment]
Thanks for the reply, after doing some tinkering. I think this is not an issue of hide_tabs_with_one_tab.css and I managed to fix it with setting the --tab-min-height variable to the desired value in :root

I will close this issue right now but I would appreciate it if you help me out with this little issue I have now:

When I close tabs, my tabs seem to have added some sort of margin and they get disoriented: 
![out](https://user-images.githubusercontent.com/55515322/202848070-af9162b0-c143-403f-aff8-9338cea271ae.gif)
_(The GIF is sped up, the margins disappear after a few seconds of closing the tabs)_

I noticed that his happens with this CSS:
```css
.tabbrowser-tab[fadein]:not([pinned]) {
	max-width: var(--max-tab-width) !important;
}
```
