### ISSUE TITLE
autohide_sidebar, not hiding

### ISSUE THREAD

**Issue by HerbertHermann** [MrOtherGuy/firefox-csshacks#229]
The show state of the sidebar works like always, the hidden state however doesn´t hide the complete sidebar anymore.
It was working in Firefox 106, after the update to 107 it didn´t. I use the latest version of autohide_sidebar. Deactivating all addons doesn´t help. 
I adjusted the values 
--uc-sidebar-width: 40px;  --uc-sidebar-hover-width: 210px;  --uc-autohide-sidebar-delay: 600ms;
to
--uc-sidebar-width: 5px;  --uc-sidebar-hover-width: 600px;  --uc-autohide-sidebar-delay: 250ms;
But this souldn´t break anything?

Sidebar "hidden":
![hide](https://user-images.githubusercontent.com/119172084/204138851-fc0cf24a-dea5-41f6-9198-f94f760d0484.jpg)

Sidebar shown:
![show](https://user-images.githubusercontent.com/119172084/204138854-0b797acf-1107-47cc-8efa-2ab621e71e80.jpg)

**Comment by MrOtherGuy** [comment]
Hmm, I cannot seem to reproduce this issue on either Firefox 107 or Nightly 109 on Windows. And I also cannot reproduce with Nightly 109 on Linux (I don't have 107 installed there).

Are you sure you tried with just that style so no other style you might have is interfering?

**Comment by HerbertHermann** [comment]
> Hmm, I cannot seem to reproduce this issue on either Firefox 107 or Nightly 109 on Windows. And I also cannot reproduce with Nightly 109 on Linux (I don't have 107 installed there).
> 
> Are you sure you tried with just that style so no other style you might have is interfering?

Tested it again without addons. No other userchrome stuff active. No themes.
This is my userChrome.css:
`
/* Source file https://github.com/MrOtherGuy/firefox-csshacks/tree/master/chrome/autohide_sidebar.css made available under Mozilla Public License v. 2.0
See the above repository for updates as well as full license text. - 20221116- */

/* Show sidebar only when the cursor is over it  */
/* The border controlling sidebar width will be removed so you'll need to modify these values to change width */

#sidebar-box{
  --uc-sidebar-width: 5px;
  --uc-sidebar-hover-width: 600px;
  --uc-autohide-sidebar-delay: 250ms; /* Wait 0.6s before hiding sidebar */
  position: relative;
  min-width: var(--uc-sidebar-width) !important;
  width: var(--uc-sidebar-width) !important;
  max-width: var(--uc-sidebar-width) !important;
  z-index:1;
}

#sidebar-box[positionend]{ direction: rtl }
#sidebar-box[positionend] > *{ direction: ltr }

#sidebar-box[positionend]:-moz-locale-dir(rtl){ direction: ltr }
#sidebar-box[positionend]:-moz-locale-dir(rtl) > *{ direction: rtl }

#main-window[sizemode="fullscreen"] #sidebar-box{ --uc-sidebar-width: 1px; }

#sidebar-splitter{ display: none }

#sidebar-header{
  overflow: hidden;
  color: var(--chrome-color, inherit) !important;
  padding-inline: 0 !important;
}

#sidebar-header::before,
#sidebar-header::after{
  content: "";
  display: -moz-box;
  padding-left: 8px;
}

#sidebar-switcher-target{
  -moz-box-pack: start !important;
}

#sidebar-header,
#sidebar{
  transition: min-width 115ms linear var(--uc-autohide-sidebar-delay) !important;
  min-width: var(--uc-sidebar-width) !important;
  will-change: min-width;
}
#sidebar-box:hover > #sidebar-header,
#sidebar-box:hover > #sidebar{
  min-width: var(--uc-sidebar-hover-width) !important;
  transition-delay: 0ms !important;
}

.sidebar-panel{
  background-color: transparent !important;
  color: var(--newtab-text-primary-color) !important;
}

.sidebar-panel #search-box{
  -moz-appearance: none !important;
  background-color: rgba(249,249,250,0.1) !important; 
  color: inherit !important;
}

/* Add sidebar divider and give it background */

#sidebar,
#sidebar-header{
  background-color: inherit !important;
  border-inline: 1px solid rgb(80,80,80);
  border-inline-width: 0px 1px;
}

#sidebar-box:not([positionend]) > :-moz-locale-dir(rtl),
#sidebar-box[positionend] > *{
  border-inline-width: 1px 0px;
}

/* Move statuspanel to the other side when sidebar is hovered so it doesn't get covered by sidebar */

#sidebar-box:not([positionend]):hover ~ #appcontent #statuspanel{
  inset-inline: auto 0px !important;
}
#sidebar-box:not([positionend]):hover ~ #appcontent #statuspanel-label{
  margin-inline: 0px !important;
  border-left-style: solid !important; 
}`

**Comment by MrOtherGuy** [comment]
What OS do you use?

**Comment by HerbertHermann** [comment]
Win 10 Pro, 22H2

**Comment by MrOtherGuy** [comment]
Would it be possible for you to test that style on brand new Firefox profile with no other changes?

If it works on new profile for you, then there's most likely some configuration option in Firefox that is causing the style to not work correctly, but I can't think of anything. On the other hand, if it doesn't work on new profile for you then it's probably caused by some OS level setting which is causing Firefox to behave differently to mine.

So, if you could test that then we would at least have some idea about what could be going wrong.

**Comment by HerbertHermann** [comment]
I think it´s a good reason to start with a new profile and migrate my bookmarks and stuff.
I found changes in my about:config from addons from about 7 yeas ago... time for a restart :)

**Comment by HerbertHermann** [comment]
But thanks for the help :)
