### ISSUE TITLE
Multi-row tabs shifted right

### ISSUE THREAD

**Issue by klee1611** [MrOtherGuy/firefox-csshacks#23]
I got this on my macbook pro after I put `@import url(chrome/multi-row_tabs.css);` into the `userChrome.css`. Not sure if this is an issue or I've made some mistake?

<img width="1280" alt="Screen Shot 2019-12-17 at 19 08 03" src="https://user-images.githubusercontent.com/9849212/70990509-a464af80-2100-11ea-8410-c42deefba85d.png">

**Comment by MrOtherGuy** [comment]
You should probably try if it works correctly with only the multi_row_tabs.css

I can't really think of anything that would cause such a massive empty space on side of tabs.

**Comment by klee1611** [comment]
It works with only the multi_row_tabs. 

In fact I tried every .css to see which one of them cause this problem, and it seems like it is cause by `chrome/menubar_in_toolbar.css` since it happened again when I import only that file in `userChrome.css`.

The version is `71.0 (64-bit)` by the way.

**Comment by MrOtherGuy** [comment]
I was under impression that Firefox on OSX doesn't even have menubar (except the native one) so it's not surprising that you will face issues with that style.

**Comment by klee1611** [comment]
Understood.
Everything works find after I remove `menubar_in_toolbar.css`. This hack is really amazing. Thank you for providing this.
