### ISSUE TITLE
autohide_bookmarks_toolbar.css leaves an empty space

### ISSUE THREAD

**Issue by Elaws** [MrOtherGuy/firefox-csshacks#230]
# Problem description

Not sure if the following is the expected behavior, once bookmarks are hidden : 

![image](https://user-images.githubusercontent.com/52013479/204152882-31627db8-06ea-45e6-9c54-e7f2677ad274.png)

# Environment

- Windows 11
- FF 107 with this applied [this](https://github.com/MrOtherGuy/firefox-csshacks/issues/215#issuecomment-1283490393) applied.

Thank you

**Comment by MrOtherGuy** [comment]
Notice if you use both multi-row_bookmarks.css and autohide_bookmarks_toolbar.css then you need to enable [compatibility rules here](https://github.com/MrOtherGuy/firefox-csshacks/blob/master/chrome/autohide_bookmarks_toolbar.css#L55-L71)

**Comment by Elaws** [comment]
Thanks a lot for your responsiveness, everything works fine now ! I will take time to read instructions in the `.css` from now on.
