### ISSUE TITLE
hide_tabs_toolbar.css : extensions icons not properly displayed and clickable

### ISSUE THREAD

**Issue by Elaws** [MrOtherGuy/firefox-csshacks#231]
# Problem description

Firefox extensions icons are not displayed properly after using `hide_tabs_toolbar.css` : 

![image](https://user-images.githubusercontent.com/52013479/204153127-f09ab2d0-1e2a-40c7-8592-9236dd6e67e6.png)

# Environment

- Windows 11
- FF 107 with [this](https://github.com/MrOtherGuy/firefox-csshacks/issues/215#issuecomment-1283490393) applied.

**Comment by MrOtherGuy** [comment]
That is to be expected. [Read instructions in hide_tabs_toolbar.css lines 11-15](https://github.com/MrOtherGuy/firefox-csshacks/blob/master/chrome/hide_tabs_toolbar.css#L11-L15)
