### ISSUE TITLE
Not able to get this to run.

### ISSUE THREAD

**Issue by SteffJay** [MrOtherGuy/firefox-csshacks#233]
I have followed the tutorial of how to make double bookmark lines in the new FF update 107 to no avail. Is this actualy working in this version?
Any advice would be greatly apreciated.]
Thanks in advance.

**Comment by MrOtherGuy** [comment]
Are you referring to [multi-row_bookmarks.css?](https://github.com/MrOtherGuy/firefox-csshacks/blob/master/chrome/multi-row_bookmarks.css)

Yes, that style does work in Firefox 107 and above. However, for 107 specifically you need to set pref `layout.css.moz-box-flexbox-emulation.enabled` to true in about:config (not necessary in 108+) for the style to work correctly.

If you have trouble getting it to work then the most likely reason is that Firefox is not reading you userChrome.css file - maybe it is in incorrect folder or named incorrectly or you have not set `toolkit.legacyUserProfileCustomizations.stylesheets` to true.

**Comment by SteffJay** [comment]
Many thanks for your reply.

Yes, I am referring to multi-row_bookmarks.css.

I have now set to true: layout.css.moz-box-flexbox-emulation.enabled but this is not working either.

In my "Profile" folder, i have a "crome" folder, inside that there is another folder called "userContent" also with files called "multi-row_bookmarks.css", "UserCrome.css", "UserCrome-example.css" and "UserContent-example.css".

Inside he "UserContent" folder there are two files; "multi-row-bookmarks.css" and "UserChrome.css".
Please can you confirm that all these files are where they should be?

Many thanks.
________________________________

**Comment by MrOtherGuy** [comment]
Well that isn't right. `userChrome.css` and `userContent.css` must be directly inside a folder called `chrome` folder. And if you store multi-row_bookmarks.css as separate file, then you must import it from userChrome.css using an import statement like:

```css
@import url("multi-row_bookmarks.css");
```

Note that all import statements need to be before anything else in the file.

Notice also the casing of all files and folders. Additionally, make sure that you "chrome" folder is inside a specific profile folder, sometimes people erroneously create it inside "profiles" folder where all profiles are stored.  Specifically, the chrome folder should end up in a same folder where there are

**Comment by SteffJay** [comment]
You Sir, are a bloody star!
Thank you very much.
I shall click to "Follow" you (but i'm not stalking" 🤣🤣
Regards.
________________________________
