### ISSUE TITLE
Dragging addressline's link (the lock symbol) makes the frist raw of the multiline bookmarksbar unresponsive

### ISSUE THREAD

**Issue by litaprog** [MrOtherGuy/firefox-csshacks#236]
New issue in 108.0.1 (maybe in 108.0.0 as well)

multi-row_tabs.css and multiple_tab_lines.css are used for handling many tabs and bookmark folders on bookmark toolbar (compact view)

When I try to drag the current site's address link to a folder on the bookmark toolbar, the first (upper) row of the bookmark bar will be inaccessible, which means cannot drop the link, the folder does not open. After the first attempt, the first raw do not respond to mouse as well so it is completely inaccessible. This can be solved by restart.

This issue appears when I start to drag the link to the first raw. If I do not enter first raw with the dragging mouse (dropping the link back to the address bar for example), then no issue.

2nd and 3rd row not affected.

**Comment by MrOtherGuy** [comment]
This sounds like an old issue with multi-row_bookmarks.css which was fixed in add8f8c1eb799ff9457e6d79b6adc23d1a6ecae7

Does the issue still happen with the latest version of multi-row_bookmarks.css?

**Comment by litaprog** [comment]
Yep, this fix solves the problem. I updated to the latest multi-row_bookmarks.css and it works nicely. It worked without issue with the older css (without the fix) in the 107x.
I just need to update in my 25+ profiles...
Thanks!
