### ISSUE TITLE
chrome/tab_separator_lines.css not working on macOS

### ISSUE THREAD

**Issue by Rhys-T** [MrOtherGuy/firefox-csshacks#239]
`chrome/tab_separator_lines.css` doesn't create any (visible) separators on macOS - even with `layout.css.color-mix.enabled` turned on. As far as I can tell, what's happening is that its `border-image` declaration is getting overridden by `border: none` in [this rule in Firefox's `browser/themes/osx/browser.css`](https://searchfox.org/mozilla-central/rev/cef96316b3643720769dec96542604c3209f1877/browser/themes/osx/browser.css#361-364) (a.k.a. `chrome://browser/skin/browser.css`). Changing the `tab_separator_lines` rule to use `!important` for `border-image` like it does for everything else seems to fix this, but I don't know for sure whether it breaks anything else.

**Comment by MrOtherGuy** [comment]
Yeah that is indeed the case. I had thought that border: none doesn't remove border-image, but apparently it does.
