### ISSUE TITLE
multi-row_tabs_window_control_patch.css does not seem working well.

### ISSUE THREAD

**Issue by Magicloud** [MrOtherGuy/firefox-csshacks#24]
Latest stable Firefox, Linux system.

The 3 rows of tabs works. Then I appended the window control patch.

The window control did not seem to be moved. And the third row of tabs was covered by address bar (and extensions), which was at row 4 position without this patch.

**Comment by MrOtherGuy** [comment]
You have made menubar permanently enabled right? Not that I have tested this with any linux, but the symptoms match exactly what would happen if menubar is not enabled.

**Comment by Magicloud** [comment]
No, I do not have menubar shown. But I do have bookmark bar shown.

**Comment by MrOtherGuy** [comment]
Then "not working" is completely expected. There may be some other possible ways to do this, but in current form, the stylesheet relies on menubar to be enabled - to use the window controls within menubar (there are two sets of window controls in Firefox, one in menubar and one in tabs toolbar but only one set is visible at given time)

I can't promise that the behavior will be totally intended on Linux even after you have made menubar enabled, but it will certainly not work if it isn't.

**Comment by Magicloud** [comment]
I see. Thanks.
