### ISSUE TITLE
Curved tabs overlaped

### ISSUE THREAD

**Issue by kaos-55** [MrOtherGuy/firefox-csshacks#243]
I am using the nightly version of Firefox with the curved tabs css, but when I hover over the tab, the corner of the back tab overlaps the front one.

Nightly
![nightly-fx](https://user-images.githubusercontent.com/86812371/209626701-cd849f23-1f47-48e7-9da2-aa8a4cb5f7cd.png)

However, this does not occur in the Developer and Stable versions.

Developer
![developer-fx](https://user-images.githubusercontent.com/86812371/209626771-314e90f0-7efb-4088-8cc4-d0132ae666e2.png)

Stable
![stable-fx](https://user-images.githubusercontent.com/86812371/209626779-79e98f97-e8b6-4551-8dec-b6c7cc7e3363.png)

I don't know if it can be fixed right now, since the changes implemented in nightly will sooner or later reach the stable version.

**Comment by MrOtherGuy** [comment]
Yeah indeed. [f9b3e20](https://github.com/MrOtherGuy/firefox-csshacks/commit/f9b3e201634dba5ec7810a1b9653c9ec213e8225) should fix this problem. It also changes how the optional sections of that style are enabled. You would now create a new pref(s) to enable them - see the modified file for the pref name.

**Comment by kaos-55** [comment]
Thanks, i activated the optional sections of the modified file and this fixes the problem.

![nightly2-fx](https://user-images.githubusercontent.com/86812371/209686521-ee7f0456-f365-4b58-99b7-10d3fe4fa97e.png)
