### ISSUE TITLE
[Question] Sidebar autohide with sidebar on the left

### ISSUE THREAD

**Issue by Mentis** [MrOtherGuy/firefox-csshacks#25]
Hi! Thank you for the awesome repository!

Is it possible to modify autohide sidebar css to make it work with sidebar on the left? If so what need to be changed to make it work?

Thank you in advance.

**Comment by MrOtherGuy** [comment]
Certainly you mean sidebar on the right (left is the default position and is supposed to work). Or perhaps you are on RTL locale in which case I really can't be sure how it would behave.

At any rate, I added some compatibility rules to that make it work with sidebar on right for LTR locales. It will also now hopefully work for RTL locales, but as I have no way to test this I really can't be sure.

**Comment by Mentis** [comment]
Yes, sorry, I mean sidebar on the right. Thank you, works flawlessly!
