### ISSUE TITLE
autohide_toolbox.css - Tabs unintentionally autohiding as well

### ISSUE THREAD

**Issue by Asinin3** [MrOtherGuy/firefox-csshacks#250]
I already tried uncommenting this: `#titlebar{ margin-bottom: -9px }` which was stated to fix the problem, but it didn't work for me.

**Comment by MrOtherGuy** [comment]
The purpose of that style is to autohide all toolbars in the toolbox, so the whole toolbox. Try one of the other autohide styles which would only hide some subset of toolbars.
