### ISSUE TITLE
Disable Tab Dragging ?

### ISSUE THREAD

**Issue by RichardGe** [MrOtherGuy/firefox-csshacks#252]
Hi, I'm using this multi-row tabs CSS for years, thanks for maintaining it with latest versions of FF.
I have a question about tab dragging:
When I work on several lines of tabs, I often intentionally move tabs of a few pixels, and for any reasons this tab jumps to a totally different location.
Is there a way to disable tab dragging ( that would be the easiest solution I guess, and that would be good enough for me )...
Or even better, is there a fix that allows to correctly drag the tabs when using multiple lines ?
Thanks.

**Comment by MrOtherGuy** [comment]
Firefox' tab re-ordering function works by checking the horizontal coordinate of the tab to determine where you are dragging it to. But with multiple tab rows the horizontal coordinate doesn't just "always increase" when you iterate through them.

What you would need to do is to write custom tab reordering function which you certainly cannot do with CSS. Thus you can't make re-ordering it work correctly with CSS.

But, apparently you can "break" the dragging function like this:

```css
#tabbrowser-tabs[movingtab] .tabbrowser-tab{
  transform: none !important;
}
```

It's not a complete success though - when you drag the first tab of a given row then that one is still thrown to some new place.

**Comment by RichardGe** [comment]
Thanks for the answer. However I have added your suggested in my CSS, restarted FF, and it seems I'm still able to drag any tab

**Comment by RichardGe** [comment]
your code is working exactly as I want, thanks !

**Comment by RichardGe** [comment]
Oh Wait - actually with this code, if I slightly (intentionally) move a tab the address bar becomes impossible to interact with.

**Comment by MrOtherGuy** [comment]
Oh shoot, I suppose that *really* breaks re-ordering function then. You could work around that issue by adding: `#nav-bar{ pointer-events: auto !important; }` but there might be all sorts of other things broken.

**Comment by RichardGe** [comment]
With that new additional line, I feel it improves it.
it disables dragging for ~50% of time on my tabs ( which is better than nothing ).  And I see no bad side effect for now.
I'll keep it and report here if I see any bad behavior.
Thanks!

**Comment by RichardGe** [comment]
actually I disabled this code.  As after some hours of usage, my close button on tab was not working anymore for unkonwn reason
