### ISSUE TITLE
autohide_toolbox.css: mimic full-screen behavior on drag/drop?

### ISSUE THREAD

**Issue by Kenifornication** [MrOtherGuy/firefox-csshacks#254]
Hi

First of all thank you for making and maintaining this useful repo. I've been using autohide_toolbox for a while now and I love using Firefox in full screen while retaining access to the taskbar. However one thing that is missing for me is the ability to drag/drop things into the tab/bookmark bar. In the regular fullscreen mode, if you drag something up to the top of the screen, once the top of the page is reached, the top bar scrolls down giving you access to the normal drag/drop behavior there.

If this is not possible to replicate, I would like to know how to limit the autohide_toolbox features to only windowed mode while retaining the customizations in maximized mode so I can have best of both worlds.

Thanks in advance.

**Comment by MrOtherGuy** [comment]
Sadly I don't think it can be made to receive drag events. Hover state doesn't trigger when you are dragging stuff, and Firefox has another kind of mechanism to show the toolbox when something is being dragged over it in normal fullscreen mode. But we can't use it for our purposes.

To limit autohiding to only windowed mode you would need to change a bunch of rules:
Replace `#navigator-toolbox` with `:root[sizemode="normal"] #navigator-toolbox` on lines:

* 22
* 28
* 45
* 46
* 52
* 54 
* 55
