### ISSUE TITLE
add to right click context

### ISSUE THREAD

**Issue by ACR-Jeff** [MrOtherGuy/firefox-csshacks#256]
Sorry this isn't an issue, Yet a preference.
Is it possible to add an icon to the right click context menu "context-navigation"?, What I would like to accomplish is adding the Home button to the icon section.
I am using the "vertical_context_navigation.css" which gives enough space for another icon. Yet I am unsure if it's possible, Or how to perform this. 
Thank you

**Comment by MrOtherGuy** [comment]
No, that is impossible.

I mean, you can probably add a button for it, but it won't do anything because CSS cannot add new functional features.

**Comment by ACR-Jeff** [comment]
> No, that is impossible.
> 
> I mean, you can probably add a button for it, but it won't do anything because CSS cannot add new functional features.

Ok I understand, Thank you
