### ISSUE TITLE
non_floating_sharp_tabs.css Firefox 110 extraneous line

### ISSUE THREAD

**Issue by corobin** [MrOtherGuy/firefox-csshacks#258]
Firefox 110 just introduced a line below the tab:

![Untitled](https://user-images.githubusercontent.com/15662785/218870834-da81198d-2acb-4ee7-a8d3-c90c50d1653e.png)

**Comment by MrOtherGuy** [comment]
Yeah, Firefox 110 removed relative positioning from selected tab which we relied on to draw it over the line.

But this is now fixed in 5facc2e
