### ISSUE TITLE
autohide_menubar.css Scrolling does not work until you tap menubar with mouse.

### ISSUE THREAD

**Issue by ihavenopie** [MrOtherGuy/firefox-csshacks#26]
As above. Happens when you refresh a tab or perform actions like typing in a tab.

**Comment by MrOtherGuy** [comment]
Uhm, what? Do you mean like you can't scroll the web page unless you interact with menubar?

Sounds like that might be so OS related problem. What OS do you have?

Another long shot: Do you have webrender enabled AND have set `gfx.webrender.picture-caching` to true AND you are on Release Firefox 72? If yes to all then I suppose it might be possible that you are experiencing a bug (that is fixed in Firefox 73) where webrender thinks that nothing on the page changed and doesn't re-render the window. So you can't see the scrolling take effect although the page did scroll in reality. I've seen this happen if scrollbars were hidden - in that case it didn't have anything to do with autohide menubar.

**Comment by ihavenopie** [comment]
windows 10/ ff72 webrender was disabled, I've also tried it enabled to see what that did. picture-caching was disabled.

Problem occurs sometimes on a new tab, when a tab refreshes, or when i hover cursor over elements, like a link,  video preview on google search page, etc.

unhiding the menubar or clicking middle mouse button (scroll) breaks the curse.

It does seem to be related to the autohide_menubar.css. other scripts I'm using are the tab bar hide script and a a treestyletabs autohide script, but i can remove them from userchrome and isolate the autohide_menubar.css script and it still has the problem, if that makes sense.

Here's my full userchrome.

`@-moz-document url(chrome://browser/content/browser.xul), url(chrome://browser/content/browser.xhtml) {
/*
 * This style will hide the tab bar and merge the title bar with the navigation bar. For Windows
 * Make sure "Title Bar" is unchecked in customize menu.
 *
 * Contributor(s): Ivan0xFF
 */

.tabbrowser-tab {
  visibility: collapse !important;
}

.titlebar-button {
  height: 40px !important;
}

#nav-bar {
  margin-top: -42px;
  margin-right: 140px;
  box-shadow: none !important;
}

[uidensity="compact"]:root .titlebar-button {
  height: 32px !important;
}

[uidensity="compact"]:root #nav-bar {
  margin-top: -32px;
}

#titlebar-spacer {
  background-color: var(--chrome-secondary-background-color);
}

#titlebar-buttonbox-container {
  background-color: var(--chrome-secondary-background-color);
}

/* Compact tab layout */
#sidebar-box[sidebarcommand="treestyletab_piro_sakura_ne_jp-sidebar-action"] #sidebar-header {
  display: none;
}
:root { --tab-height: 20px !important; }
.tab { height: 20px !important; }
/* Shrink space between pinned tabs and tab bar, only when pins are present */
#tabbar[style*="margin"] { margin-top: 20px !important; }

/* Show title of unread tabs with red font */
.tab.unread .label {
  color: red !important;
}

/* Add private browsing indicator per tab */
.tab.private-browsing .label:before {
  content: " ";
}
/*navbar autohide*/
/* Hide the whole toolbar area unless urlbar is focused or cursor is over the toolbar */
/* Dimensions on non-Win10 OS probably needs to be adjusted */

@media (-moz-os-version: windows-win10){

  :root[sizemode="maximized"]:not([inDOMFullscreen]){ margin-top: 10px !important; }
  :root[sizemode="maximized"] #navigator-toolbox{ margin-top: -2px }

  @media screen and (min-resolution: 1.25dppx){
    :root[sizemode="maximized"]:not([inDOMFullscreen]){ margin-top: 9px !important; }
  }
  @media screen and (min-resolution: 1.5dppx){
    :root[sizemode="maximized"]:not([inDOMFullscreen]){ margin-top: 8px !important; }
    :root[sizemode="maximized"] #navigator-toolbox{ margin-top: -1px }
  }
  @media screen and (min-resolution: 2dppx){
    :root[sizemode="maximized"]:not([inDOMFullscreen]){ margin-top: 7px !important; }
  }
}

#navigator-toolbox{
  position: fixed !important;
  display: block;
  background-color: var(--lwt-accent-color,black) !important;
  transition: transform 82ms 33ms linear, opacity 82ms 33ms linear !important;
  transform-origin: top;
  line-height: 0;
  z-index: 1;
}

#navigator-toolbox > *{ line-height: normal }

#navigator-toolbox,
#navigator-toolbox > *{
  width: 100vw;
  -moz-appearance: none !important;
}

#navigator-toolbox:not(:focus-within):not(:hover){
  transform: rotateX(86deg);
  opacity: 0;
}

:root[sizemode="maximized"] #navigator-toolbox:not(:focus-within):not(:hover){ transform: rotateX(89.5deg) }

:root[customizing] #navigator-toolbox{
  position: relative !important;
  transform: none !important;
  opacity: 1 !important;
}

#PersonalToolbar[collapsed]{ margin-block-end: -7px }

/* Uncomment this if tabs toolbar is hidden with hide_tabs_toolbar.css */
#titlebar{ margin-bottom: -9px }*
}
/* Show sidebar only when the cursor is over it  */
/* The border controlling sidebar width will be removed so you'll need to modify these values to change width */

#sidebar-box{
  --uc-sidebar-width: 40px;
  --uc-sidebar-hover-width: 210px;
  position: relative;
  min-width: var(--uc-sidebar-width) !important;
  width: var(--uc-sidebar-width) !important;
  max-width: var(--uc-sidebar-width) !important;
  z-index:1;
}

#sidebar-box[positionend]{ direction: rtl }
#sidebar-box[positionend] > *{ direction: ltr }

#sidebar-box[positionend]:-moz-locale-dir(rtl){ direction: ltr }
#sidebar-box[positionend]:-moz-locale-dir(rtl) > *{ direction: rtl }

#main-window[sizemode="fullscreen"] #sidebar-box{ --uc-sidebar-width: 1px; }

#sidebar-splitter{ display: none }

#sidebar-header{ overflow: hidden; color: var(--chrome-color, inherit) !important}

#sidebar{
  transition: min-width 115ms linear !important;
  min-width: var(--uc-sidebar-width) !important;
  will-change: min-width;
}

#sidebar-box:hover > #sidebar{ min-width: var(--uc-sidebar-hover-width) !important; }

.sidebar-panel{
  background-color: transparent !important;
  color: var(--newtab-text-primary-color) !important;
}

.sidebar-panel #search-box{
  -moz-appearance: none !important;
  background-color: rgba(249,249,250,0.1) !important; 
  color: inherit !important;
}

/* Add sidebar divider and give it background */

#sidebar,
#sidebar-header{
  background-color: var(--toolbar-bgcolor) !important;
  border-inline: 1px solid rgb(80,80,80);
  border-inline-width: 0px 1px;
}

#sidebar-box:not([positionend]) > :-moz-locale-dir(rtl),
#sidebar-box[positionend] > *{
  border-inline-width: 1px 0px;
}`

**Comment by MrOtherGuy** [comment]
Are youreally talking about autohide_menubar.css? I can't see any part of it in the code you posted.

**Comment by ihavenopie** [comment]
I am a moron. I must have taken a wrong turn with my copy/pasting.
