### ISSUE TITLE
normal_pinned_tabs.css broken in Firefox Nightly x64 for Windows

### ISSUE THREAD

**Issue by appyface** [MrOtherGuy/firefox-csshacks#263]
Have been using normal_pinned_tabs.css in Firefox Nightly x64 Windows edition for quite some months, working well. As of yesterday's (3/9/23) update to Nightly, it does not work correctly any more.  I experimented and commented out all but two lines from this part, and while the result doesn't look or act quite the same as before it works OK. If there is anything I can do to help troubleshoot and fix this to get the original functionality back please let me know and I'll try. Sorry I don't have any knowledge of CSS or how this works so can't troubleshoot myself :-( 

```
.tabbrowser-tab{
/*  -moz-box-flex: 100; */
  max-width: 225px;
  min-width: var(--tab-min-width);
/*  width: 0; */
/*  transition: min-width 100ms ease-out, max-width 100ms ease-out; */
/*  margin-inline-start: 0px !important; */
/*  position: initial !important; */
/*  display: -moz-box !important */
}
```

How it looked before I commented out the above parts:

<img width="773" alt="2023-03-10_09-58-37" src="https://user-images.githubusercontent.com/7108153/224457266-d2ffe19d-742a-4113-a511-5b0c017f31c7.png">

**Comment by MrOtherGuy** [comment]
Thanks for heads-up. Yeah, so the thing is that the default display model for *everything* has been changed to modern flexbox from the old xul box (-moz-box). So this changes a lot of things. I'll push an update later, hopefully today, for normal_pinned_tabs.css and about 40 other affected styles :)

**Comment by MrOtherGuy** [comment]
Yeah, so I've changed this style as part of one huge patch - 0ff12e0 - which fixed 47 styles.

There's still a few which I couldn't figure out how to fix - notably vertical_bookmarks_toolbar.css which. Trouble with that is that there's an agent style `[orient="horizontal"]{ flex-direction: row !important }` which we can't override.

Still, normal_pinned_tabs.css should work now.

**Comment by appyface** [comment]
Yes, this update works! Thanks.
