### ISSUE TITLE
How can you show the tab bar on fullscreen and not hide content?

### ISSUE THREAD

**Issue by joshpetit** [MrOtherGuy/firefox-csshacks#266]
Hey! I'm using [tabs_below_content](https://github.com/MrOtherGuy/firefox-csshacks/blob/0ff12e01fe18bc86ca68291c88c6dcf027cb9d83/chrome/tabs_below_content.css) and am wondering if it's possible to show the tabs even while in fullscreen. I modified the `#TabsToolbar` element and added `z-index: 2` which makes the tabbar show up even while in fullscreen, but it causes content to be blocked, like in the image bellow:

![image](https://user-images.githubusercontent.com/59021155/227488638-140bf43d-7f9e-4b18-9e72-06aba3b9abe4.png)

Is there a way to make this work?

**Comment by MrOtherGuy** [comment]
You copy line 44 and replace line 47 with it, that should do it.

**Comment by joshpetit** [comment]
Oh wow you responded so quickly I didn't even see the message haha! Thanks a lot that worked!! Is this something that should be changed universally?

**Comment by MrOtherGuy** [comment]
Great!

> Is this something that should be changed in the repository?

No, at least not for the style in question. The purpose of tabs_below_content.css is to reorder toolbars such that tabs are below content. It's purpose is not to "make tabs toolbar visible when on fullscreen"

Although now that you mention it, fullscreen mode does also have an option to show toolbars while in fullscreen mode. So actually yes, if that option is enabled then the current behavior is wrong and what you propose should be the correct behavior.

I have added support for showing toolbars in fullscreen option in 05ad86a - though Firefox needs to be restarted if you change the option.

**Comment by joshpetit** [comment]
Awesome!
