### ISSUE TITLE
hide_tabs_toolbar.css not  working on Windows

### ISSUE THREAD

**Issue by AntDavidLima** [MrOtherGuy/firefox-csshacks#270]
FF ver 111.0.1 (64 bit)
Windows 10 ver 22H2 build 19045.2728

Hello! I don't even know if this should work on Windows, but since I didn't find any information about it not working I'm creating this issue.

I applied the styles in the userChrome.css file but after restarting the browser nothing changed. When I did the exact same steps on my Fedora installation it worked perfectly. Does anyone know what could be going on?

Thank you for your help.

**Comment by MrOtherGuy** [comment]
It should work totally fine on Windows, in fact I just tried it and it does what it is supposed to.

Just to confirm, did you make Firefox load the userChrome.css file by setting `toolkit.legacyUserProfileCustomizations.stylesheets` to `true`?

**Comment by AntDavidLima** [comment]
This is strange, I set it to true, I was even wondering if I would have to change some other setting.

I deleted profiles that weren't what I was using in Firefox to ensure I was configuring the correct profile.

**Comment by MrOtherGuy** [comment]
One other thing that comes to mind is that Windows (unfortunately) hides file extensions by default. So there is a chance that you actually have created a file named `userChrome.css.txt` but it will show as `userChrome.css` in file manager because Windows is hiding the actual `.txt` extension.

**Comment by AntDavidLima** [comment]
I had thought about that, I even tried downloading the hide_tabs_toolbar.css file directly into my chrome directory and renaming it userChrome.

But now that you mention it, I went to check again and there it was, userChrome.css.css, thanks a lot Windows.

And thanks for your help, @MrOtherGuy .
