### ISSUE TITLE
Toolbar only woks in homepage

### ISSUE THREAD

**Issue by thrila** [MrOtherGuy/firefox-csshacks#272]
when i'm at my homepage the toolbar with all my bookmarks is visible when i go to a website it disapears .
Does anyone know how to fix this?

**Comment by MrOtherGuy** [comment]
This issue doesn't sound like it concerns this repository at all.

But I believe the default behavior of Firefox is to only show bookmarks toolbar on new tabs. To change that just right-click the toolbar area, select "Bookmarks Toolbar" and from the sub-menu set it to "Always show" instead.
