### ISSUE TITLE
combined_favicon_and_tab_close_button.css now has a slow motion animation

### ISSUE THREAD

**Issue by deevroman** [MrOtherGuy/firefox-csshacks#273]
Since Firefox 112, the close button doesn't appear immediately when you hover over it, but with an animation. This is a bit confusing.

**Comment by MrOtherGuy** [comment]
I cannot reproduce this with Firefox 112 nor with Nightly 114.

`combined_favicon_and_tab_close_button.css` doesn't create any transition or animation - so if the close-button has some animation then it is created by something else. Firefox itself doesn't have such animation for tab close button either (at least on Windows) so chances are that one of your other styles is adding transition to it.

**Comment by 0Raik** [comment]
Tried this with Librewolf 111.0.1 in Linux Manjaro. Didn't work for me.
Using the default theme and the only change I got is about:config browser.compactmode.show to true.
