### ISSUE TITLE
Autohide main toolbar + autohide bookmarks toolbar issue

### ISSUE THREAD

**Issue by 0Raik** [MrOtherGuy/firefox-csshacks#277]
First, thank you so much for the awesome work you made. The CSS hacks and the easy to implement each hack with an easy list.

As you can see

[Screencast from 2023-05-01 02-17-41.webm](https://user-images.githubusercontent.com/5239948/235427990-5ed52934-7969-4a63-a9ae-a0c0426e2927.webm)

Using both autohide yields a not so good looking experience. I would like for both to autohide at the same time. I dug thru the css code but I'm no programmer so my changes didn't do anything `  --uc-autohide-toolbar-delay: 600ms; /* The toolbar is hidden after 0.6s */` changed this to 500 to match the bookmarks autohide timing but no luck.

Also the main toolbar goes away while using the bookmarks toolbar. Any way I can change that to keep it until the pointer leaves the bookmarks?

Thank you for your time and have a great day!

**Comment by MrOtherGuy** [comment]
Simply don't use those two together. There is a combo style if you want to autohide both: [autohide_bookmarks_and_main_toolbars.css](https://github.com/MrOtherGuy/firefox-csshacks/blob/master/chrome/autohide_bookmarks_and_main_toolbars.css)

**Comment by 0Raik** [comment]
Thank you so much! Didn't saw that CCS. Worked like a charm!
