### ISSUE TITLE
Different delays for show and hide bookmarks bar?

### ISSUE THREAD

**Issue by aleqx** [MrOtherGuy/firefox-csshacks#28]
Many thanks for the code in https://github.com/MrOtherGuy/firefox-csshacks/blob/master/chrome/autohide_bookmarks_toolbar.css (I was struggling to make it work again in FF 72).

I'd like a lower (or even 0) delay when hovering in (showing) the bookmarks toolbar, but a longer delays for hovering out (hiding) the toolbar. Is that possible?

EDIT: I fixed it myself and created a PR that you can merge in: https://github.com/MrOtherGuy/firefox-csshacks/pull/29

**Comment by MrOtherGuy** [comment]
This is now merged, thanks!
