### ISSUE TITLE
FF 113 and multi-row_tabs.css : lower line of tabs doesn't respect fixed tab width

### ISSUE THREAD

**Issue by rphlrmblt** [MrOtherGuy/firefox-csshacks#283]
With the Firefox 113 update, the multi-row_tabs.css seems to not respect the fixed-width tab set to 0.

![image](https://github.com/MrOtherGuy/firefox-csshacks/assets/4006281/3cfd59ee-647a-4b53-b5b8-2fae55cc3f81)

I've updated to the latest release with commit 76f260269d153e82c8a444cada5fb569739d957a done the 9th April but no luck :(

Can you have a look ? Thanks in advance !

Best regards.

**Comment by MrOtherGuy** [comment]
Good catch, thanks! This should be fixed with c09e848

**Comment by rphlrmblt** [comment]
I can confirm that the fix (add  ```!important;```) works !

Thanks.

**Comment by MrOtherGuy** [comment]
Sweet, thanks for confirming!
