### ISSUE TITLE
Menubar showing up when it shouldn't

### ISSUE THREAD

**Issue by barelyelectric** [MrOtherGuy/firefox-csshacks#286]
![tabsonbottom](https://github.com/MrOtherGuy/firefox-csshacks/assets/71984727/de15d476-ee72-410d-b043-e86bcda0fe96)

Using FF 113.0.1, came here because my old patches broke with this update (probably the same story with the other guy here).

tabs_on_bottom.css works fine but when I add tabs_on_bottom_menubar_on_top_patch and click on a link that opens a popup window that isn't supposed to have the menubar (or nav buttons, etc) - it's still forcing it to be there. Not sure if there's a setting for this or if something has changed because I don't recall having that bug with these .css files. Removing the window_control_placeholder_support has no effect.

Using a basic userChrome:
@import url(chrome/tabs_on_bottom.css);
@import url(chrome/tabs_on_bottom_menubar_on_top_patch.css);
@import url(chrome/window_control_placeholder_support.css);

**Comment by MrOtherGuy** [comment]
Well that's an oversight, oops. Thanks for reporting - this should be fixed with 2a6e95b

**Comment by barelyelectric** [comment]
Fastest bug fix I ever saw in my life, you're the best!
