### ISSUE TITLE
Issue with minimize/maximize/close buttons

### ISSUE THREAD

**Issue by alexschrod** [MrOtherGuy/firefox-csshacks#288]
Hey. I'm using the following userChrome.css:
```css
@import url(toolbars_below_content.css);
@import url(tabs_below_content.css);
```
and it gives me this odd buttons-on-top-of-page-content behavior:
![image](https://github.com/MrOtherGuy/firefox-csshacks/assets/767490/57670284-51bf-4ae3-acfe-4e209e4ecc3e)

(I can't click the page elements below the `- □ X` bit as they're... on top of the page.)

I tried adding in the `window_control_placeholder_support.css` file, since the `tabs_below_content.css` file says I should, but it just made things worse in a way, as it adds this wide gap between the edge of the browser and the menu button, but doesn't affect the minimize/maximize/close buttons in any way. I'm guessing the point is to make room for said buttons, but it doesn't help if they remain up top, over the page content:
![image](https://github.com/MrOtherGuy/firefox-csshacks/assets/767490/04fa51f8-6d1c-4cc3-af8f-e9b2bbf7d0ab)
as well as this slightly smaller, but still noticeable gap on the left:
![image](https://github.com/MrOtherGuy/firefox-csshacks/assets/767490/24cbd0f2-3285-402c-ab4c-c50c788781a6)

**Comment by MrOtherGuy** [comment]
Hi, don't try to use toolbars_below_content.css and tabs_toolbar_below_content.css together. The former already moves tabs toolbar below content along with other toolbars, excluding menubar.

So, just use:

```css
@import url(toolbars_below_content.css);
```

**Comment by alexschrod** [comment]
Ah, thank you. That does indeed fix it. I guess I ended up in this situation because I first added `tabs_below_content.css` and then decided I also wanted the toolbars down there, and didn't realize they had overlapping behavior.
