### ISSUE TITLE
Menubar clipped by tabs on bottom code after updating from 111.0.1 to 114.0.1

### ISSUE THREAD

**Issue by iwnb** [MrOtherGuy/firefox-csshacks#292]
On June 18, 2023 I updated from Firefox 111.0.1 to Firefox 114.0.1.  When I launched Firefox after updating, the left end of the menubar (the topmost bar) was clipped as shown in the attached image.  The short end of the story is that the problem was caused by a stylesheet tabbar.css imported into userChrome.css which contains the latest code from the following sources in the order listed.  It makes no difference whether the stylesheet is imported first or later and removing the last two sections also makes no difference.

https://github.com/MrOtherGuy/firefox-csshacks/tree/master/chrome/tabs_on_bottom.css
https://github.com/MrOtherGuy/firefox-csshacks/tree/master/chrome/tabs_on_bottom_menubar_on_top_patch.css
https://github.com/MrOtherGuy/firefox-csshacks/tree/master/chrome/window_control_placeholder_support.css
https://github.com/MrOtherGuy/firefox-csshacks/tree/master/chrome/linux_gtk_window_control_patch.css
![ztabbarcss](https://github.com/MrOtherGuy/firefox-csshacks/assets/130413281/09768df2-9133-4191-b661-084edd428e88)

**Comment by MrOtherGuy** [comment]
Does your userChrome.css contain anything else in addition to those four styles? I.e. does the issue manifest if you only use those four styles?

**Comment by iwnb** [comment]
Yes.  I tested everything else in userChrome.css and removed the import of all but one other stylesheet (which tweaks the tab bar).  The menu bar returned to normal when I removed the first two of those styles.
![wotabbarcss](https://github.com/MrOtherGuy/firefox-csshacks/assets/130413281/fd0aa3e1-1daf-453e-a5b5-3941e8ac2dcf)

**Comment by MrOtherGuy** [comment]
The only real place where menubar height is specified should be [lines 9-16](https://github.com/MrOtherGuy/firefox-csshacks/blob/master/chrome/tabs_on_bottom_menubar_on_top_patch.css#L9-L16) in tabs_on_bottom_menubar_on_top_patch.css

So it would look like you hit the first case, where native titlebar is enabled. In such case the style makes the menubar only 20px tall, but the text size you have seems to be too big for that. So, you can probably just make the value on line 11 also 29px - or any value that you like.

**Comment by iwnb** [comment]
Thanks.  I believed I tried that but that has fixed it.
