### ISSUE TITLE
"Hide tabs with one tab" stops working after Firefox update

### ISSUE THREAD

**Issue by demas** [MrOtherGuy/firefox-csshacks#30]
Firefox 72.0.1 
OS - Linux

https://github.com/MrOtherGuy/firefox-csshacks/blob/master/chrome/hide_tabs_with_one_tab.css

![Screenshot_20200109_193459](https://user-images.githubusercontent.com/45047/72085911-09758480-32fe-11ea-8cec-cc0672fed621.png)

**Comment by MrOtherGuy** [comment]
Can you confirm that it does indeed not work with the latest version of that style?

I think I tried few weeks back on then Nightly 73 and it worked fine.

**Comment by demas** [comment]
It doesn't work even with standard Firefox style for me:

![Screenshot_20200109_202324](https://user-images.githubusercontent.com/45047/72089971-003be600-3305-11ea-945f-c826c3c4ad56.png)

**Comment by MrOtherGuy** [comment]
Hmm. Actually, I think that it's working just fine, but you have probably moved the newtab button to be on the left side of tabs which essentially makes it a regular button in the toolbar (and which the style warns about).

I added some rules to slightly modify the button sizes - any button sizes. This makes all such buttons slightly smaller than normal, but it should also allow placing them on the toolbar without breaking this style.

Try the latest version to see if it works.

**Comment by demas** [comment]
Thank you. You gave me idea that there is something in my `userChrome.css` that brokes this modification and I have found what is it. This line in my `userChrome.css` makes modification not working:

`
@namespace url("http://www.mozilla.org/keymaster/gatekeeper/there.is.only.xul");
`

Do I need to remove it or change for something different?

**Comment by MrOtherGuy** [comment]
Just remove it altogether.

If you find  that you DO need it for some specific rules, then you can move those rules to separate stylesheet, apply the namespace in that file only, and then use @import to load that file.
