### ISSUE TITLE
chrome/tabs_on_bottom.css dosen't work with FF 115.3.0esr (64-bit)

### ISSUE THREAD

**Issue by DrakeJones** [MrOtherGuy/firefox-csshacks#307]
chrome/tabs_on_bottom.css dosen't work with FF 115.3.0esr (64-bit)

I have nothing but contempt for the FF dev team.  Lots of disaffected users feel just the same way.

**Comment by MrOtherGuy** [comment]
So, I take it the style does actually work fine?
