### ISSUE TITLE
tabs_on_bottom.css makes tabs invisible since upgrade to 115.3.1esr

### ISSUE THREAD

**Issue by Aquila1nz** [MrOtherGuy/firefox-csshacks#308]
I use tabs_on_bottom.css and window_control_placeholder_suppost.css and my tabs suddenly disappeared from the bottom of the browser  two days ago. I can still tab through them (ctrl+tab), and they reappear briefly if I go to customise toolbar, but disappear again once I leave that tab.

Setting toolkit.legacyUserProfileCustomizations.stylesheets to false works to make them visible at the top of the browser again. 

I have updated my tabs_below_content.css and window_control_placeholder_support.css files to the latest versions from here, but it didn't make any difference. I don't know what else could be effecting it.

**Comment by MrOtherGuy** [comment]
Are you talking about tabs_on_bottom.css or tabs_below_content.css?

**Comment by Aquila1nz** [comment]
It was tabs_below_content, but I think I failed to save a file correctly, because I've got it working now!
