### ISSUE TITLE
[iconized_main_menu] Add icons for Translate and Zoom items

### ISSUE THREAD

**Issue by xmha97** [MrOtherGuy/firefox-csshacks#311]
I have feedback for `iconized_main_menu.css`
Please add icons for Translate and Zoom items

![image](https://github.com/MrOtherGuy/firefox-csshacks/assets/23485114/00969515-ed9d-49c6-aa0d-3016aea68b7d)

Thanks.

**Comment by MrOtherGuy** [comment]
Yeah, I suppose they should have something as well
