### ISSUE TITLE
non_floating_sharp_tabs.css - transparent tab background

### ISSUE THREAD

**Issue by corobin** [MrOtherGuy/firefox-csshacks#314]
Firefox 119

when dragging tabs it can be seen that there is no background so the text overlaps with inactive tabs:

![overlap](https://github.com/MrOtherGuy/firefox-csshacks/assets/15662785/5c4540cb-5766-48e5-8693-a03848b14c92)

**Comment by MrOtherGuy** [comment]
Yeah, so what's happening here is that when you use system auto theme (the default theme) then selected tab is just missing background color. Exactly the same causes #313 since no background was covering the line.

**Comment by corobin** [comment]
thank you for the quick fix and explanation!

**Comment by MrOtherGuy** [comment]
There's some further changes coming in Firefox 120, but I have "fixed" this style in 65ee216 in advace. Also, the changes I've made should improve the style for folks that use themes with image backgrounds - although there is few edge cases where the change would actually make the compatibility worse for certain themes. It should be a net-win regardless.
