### ISSUE TITLE
Text within tabs is not aligned properly when reducing tab height

### ISSUE THREAD

**Issue by Rufferly** [MrOtherGuy/firefox-csshacks#318]
Hi folks,

I'm using the latest version of:
https://github.com/MrOtherGuy/firefox-csshacks/blob/master/chrome/multi-row_tabs_below_content.css

(I cannot say enough "thanks" to this btw since I cannot live without having tabs at the bottom ;-))

One issue I discovered with the latest version (any hint on this appreciated):

- I'm using a lower tab-height by adding the following code lines (otherwise tabs are just too big):

```
    --multirow-tab-min-height: 22px;  (as a new variable right at the top)

and the following in:   .tabbrowser-tab[fadein]:not([pinned])

    min-height: var(--multirow-tab-min-height) !important;
    max-height: var(--multirow-tab-min-height) !important;
```

- When having multiple rows the text is somehow aligned at the bottom and not centrally - and this way the text is cut off a bit

[https://imgur.com/a/g9zgImB](https://imgur.com/a/g9zgImB)

I just updated from Firefox 116 to 119 and in the 116 version this was still working properly without the behaviour that the picture shows.

Thanks for any help!

**Comment by MrOtherGuy** [comment]
I'm pretty sure you don't have to do anything else than to add this somewhere:

```css
:root{
  --tab-min-height: 22px !important;
}
```

**Comment by Rufferly** [comment]
Well... so many things I tried in the CSS and nothing worked properly.

And then the solution can be so simple
Works without a flaw - thanks - much appreciated
