### ISSUE TITLE
Window control buttons are overlapping when hiding the tab bar on Linux

### ISSUE THREAD

**Issue by Yasand123** [MrOtherGuy/firefox-csshacks#319]
Window control buttons i.e. minimize, maximize and close buttons are appearing on top of the toolbar(?).
![image](https://github.com/MrOtherGuy/firefox-csshacks/assets/14009700/47a2e09d-2079-412c-bf8e-99bb2e6a2972)

- Using [Hide tabs toolbar](https://mrotherguy.github.io/firefox-csshacks/?file=hide_tabs_toolbar.css).
- Firefox v119.0 on ArchLinux.

Current workaround is to right click on the toolbar and check `Menu Bar` which will move the control buttons to the menu bar above, but that takes vertical space which defeats the purpose of hiding the tab bar in the first place.

**Comment by MrOtherGuy** [comment]
Hide tabs toolbar and some other styles as well are supoosed to be used with [window_control_placeholder_support.css](https://github.com/MrOtherGuy/firefox-csshacks/blob/master/chrome/window_control_placeholder_support.css) which adds placeholder space for them.
