### ISSUE TITLE
autohide_bookmarks_and_main_toolbars conflicts with Open Page as Popup extension

### ISSUE THREAD

**Issue by sn0utss** [MrOtherGuy/firefox-csshacks#325]
Seems to pick up any toolbars on the webpage itself (eg Gmail search box or Tweetdeck list headers) as well as just the browser toolbars. (Firefox Developer Edition 121.0b2)

**Comment by MrOtherGuy** [comment]
Could you clarify what exactly is happening? Preferably with images.

**Comment by sn0utss** [comment]
Sure, sorry. In these images the top part is in browser and the lower in popup mode - as you can see top toolbars are absent in popup (hence my assumption it's picking up page elements and not simply truncating fixed pixel distances). I have checked to confirm the popup displays correctly without the autohide css.

![firefox_4Mb5VOfM5T_proc](https://github.com/MrOtherGuy/firefox-csshacks/assets/61940039/25d1f59d-94f1-4a33-91d1-7a23a9a1b895)
![firefox_tQNblgi16F](https://github.com/MrOtherGuy/firefox-csshacks/assets/61940039/60f24e42-89ec-48ed-9ee3-da939fb909e9)

**Comment by MrOtherGuy** [comment]
All right, good call. For this and couple of other styles this issue shoud be fixed in f42c760

**Comment by sn0utss** [comment]
Works as expected now, thanks again
