### ISSUE TITLE
autohide_bookmarks stays hidden when trying to add a bookmark by dragging & dropping a link.

### ISSUE THREAD

**Issue by Elaws** [MrOtherGuy/firefox-csshacks#328]
When we want to add a bookmark by dragging and dropping a link, it's impossible because the bookmarks menu stays hidden.

**Comment by MrOtherGuy** [comment]
Unfortunately that is impossible to fix. It doesn't really have anything to do with bookmarks toolbar, it's just that `:hover` states are sort of "frozen" when a drag session is active - and that cannot be changed with CSS. The same issue would manifest with a simple style like this:

```css
#nav-bar:hover{
  background: #f00 !important;
}
```

The nav-bar doesn't become hovered when you are dragging anything over it.

**Comment by Elaws** [comment]
Thanks for your explanation.
