### ISSUE TITLE
Both nav-bar and multirow tabs below content (FF 72).

### ISSUE THREAD

**Issue by nulltab** [MrOtherGuy/firefox-csshacks#33]
Hi. 

I am trying to find a way to do something like this on FF 72:
![screen](https://user-images.githubusercontent.com/28522111/72469876-34c20d00-37f1-11ea-88a7-35c9bdbb1092.png)

So basically it is:
- main content
- multi-row tabs
- nav-bar

Currently I am using https://github.com/MrOtherGuy/firefox-csshacks/blob/master/chrome/multi-row_tabs_below_content_Fx66%2B.css , but can't find a way to also move a nav-bar below tabs...

Could you please help?

Thanks.

**Comment by MrOtherGuy** [comment]
I believe you can just use the multi-row_tabs_below_content_Fx66+.css but change:

* `--multirow-top-padding` to `0px`
* `--multirow-toolbar-height` to `0px`
* Delete or comment out lines 27-42 and 46-54

Bunch of other stuff will be unnecessary for you too, especially on mac but this should get you started I think.

**Comment by nulltab** [comment]
@MrOtherGuy  Thanks a lot! It works on both OSX and Linux.
