### ISSUE TITLE
tabs_on_bottom.css: bookmarks displayed only for fresh "New Tab"

### ISSUE THREAD

**Issue by mcweeny** [MrOtherGuy/firefox-csshacks#332]
I was a happy user of tabs_on_bottom.css and tabs_on_bottom_menubar_on_top_patch.css on a debian system running bullseye.  Now I have upgraded to debian bookworm which gives me the strange behavior that the bookmarks come and go.  The bookmarks are displayed only when the current tab is a fresh "New Tab".  If the current tab displays a web page, the tabs move upwards and the bookmarks disappear.  If a tab becomes again a "New Tab" using about:blank, this won't bring back the bookmarks; only another fresh "New Tab" will do that. Very irritating.

I did not change any firefox configuration when I upgraded from bullseye to bookworm.  Before I had firefox 115 esr and I am back to firefox 115 esr.

**Comment by MrOtherGuy** [comment]
It sounds like you have set bookmarks toolbar to "only show on new tabs". That setting is supposed to be supported fine so maybe something is wrong. But nevertheless, could you check if the behavior is correct if you set bookmarks toolbar to "always show"?

**Comment by MrOtherGuy** [comment]
Actually, on second thought the behavior you describe sounds exactly correct if you have indeed set your bookmarks toolbar to appear only on new tabs and also have set new tabs to "blank tab". Navigating to blank tab is not the same as the blank tab that is opened when you create a new tab so it is expected that bookmarks toolbar stays hidden if you just navigate to about:blank.

In short, it sounds to me that you just want to set Firefox to always show bookmarks toolbar. You can do that by right-clicking the toolbar and set the behavior from the context-menu. Or Ctrl+Shift+B should also toggle between "never show" and "always show" I think.

**Comment by mcweeny** [comment]
Thank you so much, your diagnosis was absolutely right.  I don't know
how it happened firefox got misconfigured that way.
Sorry for the noise.
