### ISSUE TITLE
non_floating_sharp_tabs line when unfocused

### ISSUE THREAD

**Issue by corobin** [MrOtherGuy/firefox-csshacks#335]
New on Firefox 122

When the *application window* is not focused, the line between the tab and main toolbar appears

when the window is focused, it appears fine

focused:
![focused](https://github.com/MrOtherGuy/firefox-csshacks/assets/15662785/270128be-8903-4818-9665-295847bf6f6d)

unfocused:
![not focused](https://github.com/MrOtherGuy/firefox-csshacks/assets/15662785/65333c2b-dfcc-450e-9e01-91184f5772d2)

Thanks!

**Comment by MrOtherGuy** [comment]
Sounds like we also would need to apply a change similar to df4462f5d98266012569768ed570db5aa080030b to non_floating_sharp_tabs.css as well.
