### ISSUE TITLE
autohide_toolbox.css malfunctioning on linux i3wm

### ISSUE THREAD

**Issue by Jemi** [MrOtherGuy/firefox-csshacks#34]
On my Artix linux laptop with i3 window manager autohide_toolbox.css is malfunctioning. Specifically, when the url bar is selected with ctrl-l or with the mouse, it becomes obscured by the dropdown box such that it becomes very difficult to type in or modify a url. 

Additional info: This doesn't seem to happen if I paste the content of autohide_toolbox.css into userChrome.css within the browser console. In that case, it seems to work properly, but if I link in autohide_toolbox.css and then restart firefox then the malfunction starts to take effect.

**Comment by MrOtherGuy** [comment]
>  This doesn't seem to happen if I paste the content of autohide_toolbox.css into userChrome.css within the browser console

Damn. That sounds somewhat plausible but it would be quite annyoing to figure out the reason for.

Could it perhaps work if you add this bit:

    :root:not([sessionrestored]) #navigator-toolbox{ transform:none !important }

**Comment by Jemi** [comment]
Amazingly enough that worked. Is that the fix? What exactly is the issue?

**Comment by MrOtherGuy** [comment]
Wow. That would suggest that Firefox calculates some of the urlbar positioning values at runtime which happens early at startup but our css style still applies before it. But with this change the toolbar is initially visible as normal so it computes those values correctly and only then we apply those rules.

**Comment by Jemi** [comment]
Well thanks for the quick fix. I appreciate it.

**Comment by MrOtherGuy** [comment]
Could you please confirm that the latest version works and doesn't cause any annyoing behavior (not sure what that would be) at startup.

**Comment by Jemi** [comment]
It seems to work pretty well, although there is a bug. Not completely sure if it's related to this one. In fullscreen mode the toolbox doesn't consistently drop down upon mouse hover. In the last test it failed to dropdown the first time I tried in fullscreen, and then subsequently it started working.

**Comment by MrOtherGuy** [comment]
I believe it isn't related to this issue. I know fullscreen mode has some problems and I'm nit sure how to resolve them consistently though. But I'm closing this bug for now. Feel free to reopen if some other issues arise.
