### ISSUE TITLE
[centered_tab_content.css] Tab label shakes when mouse hovers on the tab

### ISSUE THREAD

**Issue by YunfangHou** [MrOtherGuy/firefox-csshacks#344]
After activating `centered_tab_content.css`, the tab label will shake once (move left for few pixels, exactly) when mouse hovers on the tab.

Is there any method to eliminate it?

Thanks.

**Comment by MrOtherGuy** [comment]
What OS do you have? I cannot seem to reproduce this issue with neither Win10 nor Linux (fedora 39). Also, did you try using *only* that particular style, or is it possible the issue is caused by some conflicting rules for different styles?

**Comment by YunfangHou** [comment]
> What OS do you have? I cannot seem to reproduce this issue with neither Win10 nor Linux (fedora 39). Also, did you try using _only_ that particular style, or is it possible the issue is caused by some conflicting rules for different styles?

Oh! Yes, it is caused by a confliction with a transition on the tab-close-button. I have modified and solved this.

Thank you. It's a great repo.
