### ISSUE TITLE
Centering text during typing when using urlbar_centered_text.css

### ISSUE THREAD

**Issue by RashiqAzhan** [MrOtherGuy/firefox-csshacks#349]
At rest.
![image](https://github.com/MrOtherGuy/firefox-csshacks/assets/7370540/23d6bdc1-39c7-43bd-af17-81be70d2b2b6)

When focused.
![image](https://github.com/MrOtherGuy/firefox-csshacks/assets/7370540/fe193dd6-3d56-4922-944c-f9ed2fe57bd0)

Is it possible to keep the text in the center even during typing?

**Comment by MrOtherGuy** [comment]
Yes, you can do that with just `#urlbar-input{ text-align: center !important; }`

**Comment by RashiqAzhan** [comment]
Thank you.

I couldn't figure out how to get the CSS selector for Firefox UI elements.

TLDR: Enable [Firefox browser toolbox](https://firefox-source-docs.mozilla.org/devtools-user/browser_toolbox/index.html) and [use the inspector to find the css id to hack up in userChrome.css](https://blog.tymek.dev/firefox-css/).
