### ISSUE TITLE
Please, need a little help with vertical_popup_menubar.css

### ISSUE THREAD

**Issue by Lepefe** [MrOtherGuy/firefox-csshacks#350]
Hi! I'm using:
[window_control_placeholder_support.css](https://raw.githubusercontent.com/MrOtherGuy/firefox-csshacks/master/chrome/window_control_placeholder_support.css)
[tabs_on_bottom.css](https://raw.githubusercontent.com/MrOtherGuy/firefox-csshacks/master/chrome/tabs_on_bottom.css)
[vertical_popup_menubar.css](https://raw.githubusercontent.com/MrOtherGuy/firefox-csshacks/master/chrome/vertical_popup_menubar.css)

And for the [vertical_popup_menubar.css](https://raw.githubusercontent.com/MrOtherGuy/firefox-csshacks/master/chrome/vertical_popup_menubar.css), I added few mods (below) in order to put the menubar on the right side of the navbar:

`:root:not([customizing]) #menubar-items{  inset-inline-start: 1394px;}`
`:root:not([sizemode="fullscreen"],[chromehidden~="menubar"]) #toolbar-menubar{  margin-bottom: -28px;}`
`#menubar-items{  margin-top: -34px;}`

However, on mouse-hovering menubar icon, it opens partially (just the first two items, until the bottom of the tabbar), I can't see the full menu.

if I change `{inset-inline-start: 0px}`, the menu works and is totally visible. In short, if I change menubar position, I can't totally open the menubar. I played with all the `{z-index}` possibilities, but the problem remains.

Hope you can help me.

Thks!

**Comment by MrOtherGuy** [comment]
Yeah, vertical menubar was apparently affected by #331 and nobody noticed until now. So, I've implemented the same workaround for this style as there (and fixed a couple of other issues as well).
