### ISSUE TITLE
[Question]Mixing side bar and multi bar

### ISSUE THREAD

**Issue by Itstatertots** [MrOtherGuy/firefox-csshacks#354]
Is it possible to have the side bar but keep the bookmark bar by using the multi bar

**Comment by MrOtherGuy** [comment]
What exactly do you mean? Neither multi-row_tabs.css or multi-row_bookmarks.css should affect sidebar.

**Comment by Itstatertots** [comment]
sorry i meant vertical bar im trying to make firefox Opera GX and I'm using ur vertical bookmark/toolbar CSS and I was wondering if its possible to add another bookmark bar under the search bar

**Comment by MrOtherGuy** [comment]
I see. You should be able to use vertical_menubar.css instead of vertical_bookmarks_toolbar.css, unless you need menubar as well of course. It appear vertical_menubar is a bit broken at the moment, but I believe I can fix that later today.

**Comment by Itstatertots** [comment]
ill try it out real quick

**Comment by MrOtherGuy** [comment]
New patch for vertical_menubar.css [daf2d17](https://github.com/MrOtherGuy/firefox-csshacks/commit/daf2d17b3607085d51e30a0da01bf9b713672827) makes it work a bit better. Also, the side is now on left by default. but can be changed to right by setting `userchrome.vertical-menubar.on-right.enabled` to `true` in about:config

**Comment by Itstatertots** [comment]
Thank you so much
