### ISSUE TITLE
autohide_tabstoolbar.css causing page content to move up and down during animation

### ISSUE THREAD

**Issue by FreyrDev** [MrOtherGuy/firefox-csshacks#355]
Updated to Firefox 124 and the page content has now started moving as the tab bar is appearing and disappearing. When the tab bar is fully visible the content is in the right place, it only gets messed up during the animation.

[simplescreenrecorder-2024-04-10_19.02.43 (trimmed).webm](https://github.com/MrOtherGuy/firefox-csshacks/assets/95385132/c497c033-b418-4467-83c5-31add40e551f)

Firefox version 124.0.2 on Linux, using autohide_tabstoolbar, tabs_on_bottom, tab_separator_line, and floating_findbar_on_top.

**Comment by MrOtherGuy** [comment]
Seems that I cannot reproduce this issue with those styles on Firefox 124.0.2 on Fedora.
The issue seen on video sounds a bit confusing because autohide_tabstoolbar.css doesn't add any animation, so I don't really see why you experience an animation in the first place.

**Comment by FreyrDev** [comment]
autohide_tabstoolbar has a couple of transition properties doesn't it? I'm just referring to it sliding in and out rather than suddenly appearing. If I change all the values in milliseconds to zero then the bug doesn't appear (It just results in the tab bar appearing and disappearing instantly instead of smoothly).

How does it look for you with just autohide_tabstoolbar and tabs_on_bottom?

**Comment by MrOtherGuy** [comment]
Yes, you are right - I don't know what I was thinking. There should indeed be an transition and that isn't working. New patch to autohide_tabstoolbar.css should fix that though.

**Comment by FreyrDev** [comment]
Yep confirmed that fixes it. Should've checked !important myself lol.
