### ISSUE TITLE
window_control_placeholder_support.css has no window control buttons

### ISSUE THREAD

**Issue by mia-gamedev** [MrOtherGuy/firefox-csshacks#356]
Since the last update to firefox window controls are missing
![image](https://github.com/MrOtherGuy/firefox-csshacks/assets/25747741/ec6a9138-656b-47fd-95b2-b4c71454094e)

**Comment by mia-gamedev** [comment]
adding 
#nav-bar{
  position: static !important;
}
in nav-bar fixes it; not sure why

**Comment by MrOtherGuy** [comment]
What style do you use along with `window_control_placeholder_support.css`?
Also, what OS do you have?

For reference, I tried with Firefox 124.0.2 with `tabs_on_bottom.css` on Windows 10 and it seems to work correctly.

**Comment by mia-gamedev** [comment]
I use your hide_tabs_toolbar.css running Win 10 124.0.2 (64-bit) as I'm using sideberry.
I was digging through the css and this does fix it. 
`#titlebar {
  z-index: 9999 !important;
}
#nav-bar-customization-target{
  z-index: 9999 !important;
}
#PanelUI-button{
  z-index: 9999 !important;
}`

My guess is that the navbar is above the titlebar so the window controls are hidden. Forcing it to be infront with the z index makes the windowcontrols appear and clickable, but all navbar items unclickable. Pulling nav-bar-customization-target and PanelUI-button also infront makes everything clickable, but its extremly hacky.

**Comment by MrOtherGuy** [comment]
Are you sure your hide_tabs_toolbar.css is up to date? This issue kinda sounds like what would happen before patch df4462f5d98266012569768ed570db5aa080030b - see issue #331

**Comment by mia-gamedev** [comment]
ill try that
