### ISSUE TITLE
window_control_force_linux_system_style.css odd hover behavior

### ISSUE THREAD

**Issue by epic0421** [MrOtherGuy/firefox-csshacks#359]
I made sure I had the latest version of the window_control_force_linux_system_style.css file before testing this. This might have broke after a recent Firefox update (I am using 125.0.1 on KDE Plasma), but now whenever I hover over a button and move onto a different button right next to it, the button stays in its hovered state. It works fine if I hover over a button and then don't hover over any other buttons. It also exits the hover state normally if I am moving off of a button.

Moving from close button to maximize/minimize button to minimize button
![2024-04-16_23 45 06](https://github.com/MrOtherGuy/firefox-csshacks/assets/85042398/ac9e599f-14c2-4b48-acab-b619f8149150)
After moving my cursor off of the minimize button
![2024-04-16_23 43 17](https://github.com/MrOtherGuy/firefox-csshacks/assets/85042398/af7571f2-f059-4605-87eb-ed9f87dcd84f)

Without the CSS modification, this does not happen but noticed that the buttons are slightly more spaced out like shown here.
![2024-04-16_23 36 21](https://github.com/MrOtherGuy/firefox-csshacks/assets/85042398/714b7c0a-6410-40ce-95ea-2771b08317fc)

**Comment by MrOtherGuy** [comment]
I've updated the style to make it work as well as I could, but I think there might be an actual bug somewhere because on my system hover states on native appearance buttons don't show up at on focused windows. This behavior happens with or without that style whenever native-appearance window controls are used.

**Comment by MrOtherGuy** [comment]
Ugh. I messed up in the previous commit. I got two Firefox's and two browser toolboxes open while testing this and copied code from the wrong one...

Latest should update should work nicely though.
