### ISSUE TITLE
button_effect_scale_onclick.css issue

### ISSUE THREAD

**Issue by PleskarjevJanez** [MrOtherGuy/firefox-csshacks#362]
The effect doesn't work for some buttons. The buttons that don't work that I've found so far are: downloads, close tab, shield button (url bar),  padlock (url bar), "show in explorer" in downloads and the options button on the homepage (top right). I tested this css style on a new profile and the results are exactly the same so it shouldn't be a problem on my end. 
Thanks for developing such awesome styles!

**Comment by MrOtherGuy** [comment]
Thanks for report. I've updated that style and also the onhover variant to include most of these and some more.

However, the options button on homepage doesn't get this treatment since userChrome.css does not apply to content documents such as about:home in the first place.

**Comment by PleskarjevJanez** [comment]
I updated the style and tried and found something pretty minor but slightly annoying. I noticed that the "hitbox" (sorry, I don't know how else to call it) in the "close tab" button shrinks together with the icon (unlike most other buttons). This is also an issue with the tab_effect_scale_onclick.css when I try and close the tab, because the tab itself also shrinks creating the same issue. I don't know if there's any easy fix, but I thought I'd atleast make you aware of it.

https://github.com/MrOtherGuy/firefox-csshacks/assets/114862133/67b00166-4a79-44cd-bec2-1c74cba485e9

**Comment by MrOtherGuy** [comment]
Yes, I know and it's unfortunate. That would not be easy to fix but I thought that since the button is so small it probably doesn't matter much. Same happens with extension menu buttons within extensions panel btw, which are bigger but less used so that's also fine I suppose.
