### ISSUE TITLE
Firefox 126: --urlbar-toolbar-height replaced with --urlbar-container-height

### ISSUE THREAD

**Issue by Dupond** [MrOtherGuy/firefox-csshacks#369]
Hello,

I *think* that in Firefox 126 `--urlbar-toolbar-height` has been replaced with `--urlbar-container-height` so that compact_urlbar_megabar.css doesn't work anymore (and maybe some other styles too?)

Thanks for all your amazing hacks!

**Comment by MrOtherGuy** [comment]
Yeah you're right, thanks for reminding me. I've replaced all uses of `--urlbar-toolbar-height` with `--urlbar-container-height`. The two variables aren't exactly the same (and --urlbar-container-height also existed before this) but I think for our purposes the behavior should match.
