### ISSUE TITLE
Firefox 126 broke tabs on bottom again?

### ISSUE THREAD

**Issue by ondono** [MrOtherGuy/firefox-csshacks#370]
Just updated to FF126, tabs on bottom mostly works, but the pop up from the url bar with suggestions now hovers in a weird way extending down, instead of going up. 

I've tried to capture an image but printing the screen hides the pop up.

**Comment by MrOtherGuy** [comment]
As far as I can tell, tabs_on_bottom.css, tabs_below_content.css and toolbars_below_content.css all work as expected. Maybe you have an old version of whichever one you are using?

**Comment by vitaly-zdanevich** [comment]
tabs_on_bottom.css - tabs still on the top.

I used:

```
@import url(tabs_on_bottom.css);
@import url(window_control_placeholder_support.css);
```

**Comment by MrOtherGuy** [comment]
Unfortunately I cannot reproduce the issue. I've tried that setup with Firefox 126 on Windows 10 and Linux (Fedora 40) and it works properly on both of them.

**Comment by ondono** [comment]
Just found some time to experiment and clean up the CSS, everything was up to date so not sure where the issue was coming from.

It wasn't from `tabs_on_bottom.css`, since the issue was on the url bar, but I was confused in thinking the same css file dropped the whole bar.

Sorry for the wasted time and thanks for all your hard work @MrOtherGuy

As for @vitaly-zdanevich's issue, I get the feeling you're not properly loading the css. If you've cloned the git repo inside of the `chrome` folder, your imports should read:

```
@import url(chrome/tabs_on_bottom.css);
@import url(chrome/window_control_placeholder_support.css);
```
