### ISSUE TITLE
Using  iconized_main_menu.css with Firefox-Mod-Blur and Nightly results in black icons

### ISSUE THREAD

**Issue by MorningWood** [MrOtherGuy/firefox-csshacks#377]
Is there a way of inverting the colors of of the app-menu icons and to fix the spacing?  
Using the Firefox-Mod-Blur version or the original both result in black icons on a dark theme.

![image](https://github.com/MrOtherGuy/firefox-csshacks/assets/42712/332b26ef-fbd5-4d48-918c-b563b8b8b1a8)

**Comment by MrOtherGuy** [comment]
Good find! Should be all fixed now
