### ISSUE TITLE
move application menu button with hidden tab bar

### ISSUE THREAD

**Issue by thomas725** [MrOtherGuy/firefox-csshacks#378]
thank you for your amazing work!

I'm using your "hide_tabs_toolbar_osx.css" file (on my Linux plasma desktop) and it works great, though it also hides the window control buttons.

The alternative "hide_tabs_toolbar.css" does not hide the window control buttons, but the application menu button is overlayed by them so it becomes inaccessible. Therefore for now I stick to the "_osx" version.

What I would like best though, is if there was some way to move the application menu button to the left - like I was able to do with all the other buttons (from various extensions) using a placeholder in the "Customize Toolbar"-UI. Is it possible to move that application menu button with css somehow?

**Comment by thomas725** [comment]
update: I just found that "hide_tabs_toolbar_osx.css" messes up my ability to show the menu bar optionally (it just moves the URL-bar + Buttons up a bit outside the window when I try)

Instead using just:
`#TabsToolbar{ visibility: collapse !important }`
works better if I don't mind having no window buttons when the menu bar is hidden.

Still my preferred option would be to use "hide_tabs_toolbar.css" which does show the window buttons but move the application menu button out of the way so it also is still accessible.

**Comment by MrOtherGuy** [comment]
You need to also get window_control_placeholder_support.css for hide_tabs_toolbar.css to work properly.

**Comment by thomas725** [comment]
thank you for your reply! yes I read that comment in the hide_tabs_toolbar.css and tried adding `@import url(window_control_placeholder_support.css);` before `@import url(chrome/hide_tabs_toolbar.css);` but the behaviour doesn't change. Maybe it's Windows specific and doesn't work on Linux?

**Comment by MrOtherGuy** [comment]
Hmm, it should work fine on Linux, although it is totally possible that some distros have customized Firefox versions where it doesn't. I'm not able to test at this moment, but I'll get back to you later.

**Comment by thomas725** [comment]
I haven't seen anything obviously different to Firefox here on Manjaro compared to other distors, though of course I only see the surface ;)

If there's any testing I can do, or any valueable information I can gather to help solve this, I'm willing.

**Comment by MrOtherGuy** [comment]
You should get something like this: ![image](https://github.com/MrOtherGuy/firefox-csshacks/assets/31620503/4502c3fe-25c5-4086-b5a2-e0e85b27fc87)

This is on Fedora 40.

I suppose one easy thing you could test is if it works when you copy the contents of the files straight into userChrome.css instead of using import statements.

**Comment by thomas725** [comment]
yes, that would be nice! sadly, this is what the relevant area of the screen looks like on my machine:
![Screenshot_20240606_230512_crop](https://github.com/MrOtherGuy/firefox-csshacks/assets/68635351/a35981b5-1f1d-429e-9a19-176aaaa5e65c)
I'll try that copy + pasting of the css content next and report back on my results.

**Comment by thomas725** [comment]
well that's strange! copying and pasting the content of those 2 css files into "userChrome.css" instead of using `import url(..);` works perfectly!
![Screenshot_20240606_231146_crop](https://github.com/MrOtherGuy/firefox-csshacks/assets/68635351/2086bcf8-6da9-40ac-becd-c5ba5d49bfb2)

**Comment by thomas725** [comment]
though one strange thing that's also visible on your screenshot: on the top left of the screen, left of the forward & backwards buttons there is a strange empty place unless the window is maximized, then it vanishes and puts the back-button in the left corner where it is supposed to be.

**Comment by MrOtherGuy** [comment]
Yes that empty space is there for you to drag the window. It (and another one next to window controls) mimics the space that is normally there in tabs toolbar.

If you want to disable those, you can set their width to zero by modifying two variables found in window_control_placeholder_support.css (drag-space-width-pre and -post)

Looking back though, I believe the reason why import didn't work is that you missed the `chrome/` prefix on the file name.

**Comment by thomas725** [comment]
oh my, am I really that stupid? gotta retry that
