### ISSUE TITLE
tabs_below_content.css - possibly slight adjustment required on F75

### ISSUE THREAD

**Issue by shaarkys** [MrOtherGuy/firefox-csshacks#38]
Hi @MrOtherGuy , once more let me thank you for those CSS styles. The option having TABs below content is really a must for me.
With F75 seems menu, address bar and favorites are missing slight spacer (like very small space) - can you please take a look on it ?

https://github.com/MrOtherGuy/firefox-csshacks/blob/master/chrome/tabs_below_content.css

![obrazek](https://user-images.githubusercontent.com/14859895/79834483-709ade80-83ad-11ea-8e1c-8953d288986a.png)

**Comment by MrOtherGuy** [comment]
Sorry, but I can't see anything wrong in the screenshot. At any rate, the style does affect menubar but it does nothing to bookmarks toolbar.

**Comment by shaarkys** [comment]
You are right, it happens only when address bar is focused. Sorry for false issue.
