### ISSUE TITLE
Hide urlbar first row not consistently working 

### ISSUE THREAD

**Issue by silverwings15** [MrOtherGuy/firefox-csshacks#382]
Hi, does https://github.com/MrOtherGuy/firefox-csshacks/blob/master/chrome/hide_urlbar_first_row.css need an update? it mostly works for me, although when i type a nonsensical domain into the urlbar the first (two) rows still show up

![image](https://github.com/user-attachments/assets/d4758f65-f35e-43aa-8f58-22a7f997fa31)

**Comment by MrOtherGuy** [comment]
Umm, yeah I so. Latest patch should make it behave close to what it used to. Probably, I can't remember exactly what kind of items it used to hide.

**Comment by silverwings15** [comment]
seems to be working well. tyvm!!
