### ISSUE TITLE
multi-row_tabs.css moving tabs problem

### ISSUE THREAD

**Issue by Jolly-Pirate** [MrOtherGuy/firefox-csshacks#384]
On the latest FF 128, moving the tabs doesn't work properly when multi-rows are in effect. They can't move between the rows. Anything on row 2 only wants to move to row 1. All sorts of weird bugs. Please play around with it you'll see what I mean.

**Comment by MrOtherGuy** [comment]
Yes, tab dragging has always been broken with that style, but it's impossible to fix with CSS. The style actually has a note about this.

I'm closing this because there literally nothing we can do about it.

**Comment by pawlosck** [comment]
Do you know any idea how to fix it? Settings, or any addon?

**Comment by MrOtherGuy** [comment]
Yeah, you can write your desired functionality in [tabs.js](https://searchfox.org/mozilla-central/source/browser/components/tabbrowser/content/tabs.js) and build your custom Firefox from using that.
