### ISSUE TITLE
[Question] Is it possible to imitate microsoft edge autohide sidebar behavior?

### ISSUE THREAD

**Issue by scmanjarrez** [MrOtherGuy/firefox-csshacks#387]
Hi, in microsoft edge, the sidebar only shows if the mouse hovers over it for a certain duration, instead of appearing instantly on hover, is it possible to achieve a similar result in firefox?
![ezgif-3-086e9cef0d](https://github.com/user-attachments/assets/6249f468-4cd5-46c4-ab73-0b257a8f969b)

**Comment by MrOtherGuy** [comment]
Sure, just increase [the delay here](https://github.com/MrOtherGuy/firefox-csshacks/blob/9d891a3f9e93ea711284e9d5a4c8e8af16a11196/chrome/autohide_sidebar.css#L52)

**Comment by scmanjarrez** [comment]
Amazing, thank you so much!!!
