### ISSUE TITLE
Firefox-128.0.2 on Linux: tabs_* patches ineffective?

### ISSUE THREAD

**Issue by sphakka** [MrOtherGuy/firefox-csshacks#389]
It looks like things got screwed a bit with latest Firefox-128.0.2 on Linux, or I am doing something wrong. Here's my `userChrome.css` (it works for other basic tweaks):
```css
@namespace url("http://www.mozilla.org/keymaster/gatekeeper/there.is.only.xul");

/* firefox-csshacks */
@import url("/home/marcoep/projects/firefox-csshacks/chrome/window_control_placeholder_support.css");
@import url("/home/marcoep/projects/firefox-csshacks/chrome/linux_gtk_window_control_patch.css");
@import url("/home/marcoep/projects/firefox-csshacks/chrome/tabs_below_content.css");
```
However, the tabs stay obstinately at the top. Is that above the correct import sequence?

**Comment by MrOtherGuy** [comment]
This cannot possibly work. All import statements have to be before anything else in the file. Right now they are ignored because there's a `@namespace` rule preceding them.

**Comment by sphakka** [comment]
Aah, my bad: i completely disregarded the namespace line! Thanks, it works indeed :-)
