### ISSUE TITLE
Multi row tabs only working when firefox window width is about under 1770pixel

### ISSUE THREAD

**Issue by Swee4T** [MrOtherGuy/firefox-csshacks#39]
Hello,
thank you very much for this nice hack. 
But can somebody help me fix my problem?
The multi row wont show up until i set my firefox window width under ca. 1770pixel. Going wider results in the usual ff behavior, showing all tabs in only row..

![multirowtabs2](https://user-images.githubusercontent.com/64068219/79843453-94185600-83ba-11ea-966a-dbe140253af2.PNG)

![multirowtabs3](https://user-images.githubusercontent.com/64068219/79844109-87483200-83bb-11ea-9f10-37c410a5efee.PNG)

I´m using 
@import url(chrome/multi-row_tabs.css);

Thank you very much.

**Comment by MrOtherGuy** [comment]
Are all those really pinned tabs? Tabs are only flowed to multiple rows if they cannot shrink anymore (as set by their min-width property). So if you are making min-width so small that they all fit on one row then they won't be flowed to another row.

The style by default sets min-width to 100px and your tabs are certainly below that.

**Comment by Swee4T** [comment]
Thank you for your fast reply.
Ah i understand now. Youre totally right. Those tabs were not pinned.

![multirowtabs4](https://user-images.githubusercontent.com/64068219/79955229-c7bcb400-847e-11ea-86c5-48f0db708996.PNG)
