### ISSUE TITLE
Can't click and drag bookmarks using multi-row_bookmarks.css

### ISSUE THREAD

**Issue by yopburner** [MrOtherGuy/firefox-csshacks#392]
I can't click and drag bookmarks to rearrange them after the most recent update.  Cutting and pasting them to rearrange them still works however.

**Comment by MrOtherGuy** [comment]
As far as I can tell, dragging bookmarks inside bookmarks toolbar to rearrange them is working fine - this is on Win10. The dropmarker thingy won't be shown in exactly correct location which is kinda annoying, but minor issue at best.

**Comment by yopburner** [comment]
That fixed it thanks for the help!
