### ISSUE TITLE
newbie tab bar question

### ISSUE THREAD

**Issue by isanynameavailable** [MrOtherGuy/firefox-csshacks#40]
I had my userchrome file set up in FF 75 so that the tab bar would hide if there was only one tab, but remain visible when there were more than one. Now, in FF 76, the css file no longer works -- the tab itself and the text that would appear in the tab are hidden, but the blank tab bar remains visible --  but I don't know why. I see the code for permanently hiding the tab bar, but that's not exactly what I'm looking for. I'm looking for some help with this "problem" -- I would truly appreciate it.

**Comment by MrOtherGuy** [comment]
Please use the latest version of the "hide_tabs_with_one_tab.css". It should work up to Firefox 78 (current Nightly)

**Comment by isanynameavailable** [comment]
Mr Other, Thanks for your email. I tried using that css file, but it did not completely remove the tab bar: I usually have the browser window maximised and what I found is that the blank tab bar, with only one tab open, is a few pixels shorter than default, but is still displayed. When I open a second tab, the tabs appear for both and the tab bar becomes a few pixels taller. Could it be a conflict with an extension that prevents the css from working as it should? I don’t think so, but my knowledge is limited...

Because I do not truly understand what parameters can be used to modify Firefox’s appearance, the userchrome.css I used with FF 75 was a hodgepodge of stuff I had found here and there and cobbled together, but it did what I wanted — until FF 76. Page modification in Firefox using CSS seems to be a dark art and I can’t find a list of all possible parameters anywhere.


Thanks for your help, but I guess I’m still on the hunt to find the modification I need to completely hide the tab bar with only one tab…


Regards, Simon

**Comment by MrOtherGuy** [comment]
Well, any "new" css depends on what is already there so unfortunately the situation is that even if you do find something that works on "out-of-the-box" Firefox, it won't work on your setup because some of your existing rules prevent it from working.

That's really why your specific setup stopped working too. Your "old" rules depended on Firefox's built-in styling but since that has changed they don't work any more.

I can say that the style I linked works on my setups both on Windows10 and Linux (pretty much default Fedora 32)

**Comment by isanynameavailable** [comment]
Thanks again. I agree with what you say, or course; I am running OS X 10.11.6, but that shouldn’t make any difference, should it? My main problem is not being able to go to a page where all these variables/parameters are listed — is there such a site? MDN doesn’t seem to list everything in your CSS, for example.

Anyway, I fiddled around with what you posted on GitHub and what I already had, which worked with FF 75. Eventually I got the tab bar to disappear with only one tab, but when the tab appears on opening another tab, the height is less than I would like and it also has a blue bar at the top of the tab, which I don’t need. Nevertheless, it is workable, so I will live with it until I discover the tweaks I need to get it “exactly” how I would like.

Thanks again for your CSS — without it I couldn’t have got (most of) my old look back.

Cheers! Simon

**Comment by MrOtherGuy** [comment]
> My main problem is not being able to go to a page where all these variables/parameters are listed — is there such a site?

Unfortunately such as "list" doesn't make any sense because it would be infinitely long.

CSS reference in MDN is a good resource to find what each property controls and MDN also links to mozilla CSS extensions (-moz prefixed properties) but since all propeties can have all kinds of values its practically impossible to have a meaningful list of how things behave with all property/value combinations.

**Comment by isanynameavailable** [comment]
Thanks again for helping me understand how this all works. It seems as if I have some serious learning to do if I want to to be a CSS ninja. I’ll start with MDN…

Regards, Simon

**Comment by MrOtherGuy** [comment]
Yeah it takes a bit of learning but I honestly don't think it's too bad.

Still, MDN is a great and vast resource for reference, but I'm not really sure if it's the best to start with if you don't have any background. I mean, it's very technical and tells how different properties interact and how specific values behave, but you will probably first like to have some kind of overview of things.

So, you might be better of by searching for css starter guide. I did write one myself (that I've had to put on hold sadly) that you can [find right here](https://mrotherguy.github.io/ToyfoCSS/) but it doesn't really get into the more "interesting bits". If you have questions or any input regarding that, then I hope you open issues on [its repository](https://github.com/MrOtherGuy/ToyfoCSS/issues).

Have a nice day :)

**Comment by isanynameavailable** [comment]
Thanks, you’ve been a big help!

Simon
