### ISSUE TITLE
autohide_bookmarks_and_main_toolbars.css with compact density has gap between tab and main toolbar

### ISSUE THREAD

**Issue by PavloVinnyk** [MrOtherGuy/firefox-csshacks#400]
When I set Firefox to compact density in the customize menu, there’s a gap between the tab and the main toolbar on startup.
But if bookmark toolbar set to Never Show this gap stays visible until it set to Always Show
Tested with only autohide_bookmarks_and_main_toolbars.css in userChrome.css

https://github.com/user-attachments/assets/20b35cf5-d87a-417b-97d9-ce439ee2ba39

My goal is to auto-hide the main toolbar and keep the bookmark toolbar set to “Never Show.” I want to switch the bookmark toolbar to “Always Show” with a shortcut when needed.

Is there any fix for my use case?

**Comment by MrOtherGuy** [comment]
Hmm, alright I was able to reproduce this, but I can't investigate more just now. But I'll check it out when I can.

**Comment by MrOtherGuy** [comment]
Right, so when bookmarks toolbar is disabled on startup then Firefox won't try to populate it with bookmarks - our layout rules make things work such a way that bookmarks toolbar always has height in layout, but that assumption breaks when no bookmarks are loaded.

So I've now set a height for the container where bookmarks would show up in case where it is empty.

**Comment by PavloVinnyk** [comment]
Thank you, works perfectly.
