### ISSUE TITLE
[Feature Request] Group iconized context buttons horizontally

### ISSUE THREAD

**Issue by Hash6232** [MrOtherGuy/firefox-csshacks#403]
There are certain buttons in the context menus that are pretty much self explanatory and that don't really need text or to take an entire line for them. Is there a way to group together these buttons to save up space? The vertical contextmenu navigation does just that, kinda, but maybe something similar can be achieved by toggling on context menu icons and then placing them on the same line in contextual groups (navigation groups, text editing groups, etc)

![contextual_menu](https://github.com/user-attachments/assets/af823990-409d-40de-bdc2-6fc3bc364b50)

**Comment by MrOtherGuy** [comment]
I think this is a rather neat idea, and it can be done, but it's rather complicated. I have created a style for this, which works alongside iconized_textbox_context_menu.css and iconized_content_context_menu.css (it requires them both to actually show the icons). But it changes the menu layout rather drastically, so there might very well be situations where it's gonna break.

**Comment by MrOtherGuy** [comment]
The style in question: https://github.com/MrOtherGuy/firefox-csshacks/blob/master/chrome/icon_only_context_menu_text_controls.css
