### ISSUE TITLE
Normal Pinned Tabs - title overflow removes right border outline and 'X' to close

### ISSUE THREAD

**Issue by appyface** [MrOtherGuy/firefox-csshacks#404]
Using Firefox Nightly 132.0a1 (2024-09-07) (64-bit).
Using Normal Pinned Tabs css 
Windows 11 Pro 23H2 all patches

I noticed some weeks ago after a Firefox update, the pinned tabs with titles longer than will fit in max length in CSS, are missing their right side tab outline border and close 'X' control is also missing. See attached screenshot - first two tabs are pinned, with second tab exibiting missing outline and close control.

![image](https://github.com/user-attachments/assets/fa64b027-2684-4e92-9120-331bfe292b30)

**Comment by MrOtherGuy** [comment]
This was an easy fix. There's probably going to be a whole bunch of changes in tabs and/or sidebar area pretty soon because of all the vertical tabs + tab grouping work.

**Comment by appyface** [comment]
Works perfectly, thank you so much!
