### ISSUE TITLE
The autohide sidebar stopped working.

### ISSUE THREAD

**Issue by kkhoa312** [MrOtherGuy/firefox-csshacks#408]
After updating to the latest Firefox Nightly. My Sidebery cannot auto-hide anymore. Could anyone fix this?
I use https://github.com/MrOtherGuy/firefox-csshacks/blob/master/chrome/autohide_sidebar.css
**Firefox version**: 132.0a1

![firefox_676wBRNTHw](https://github.com/user-attachments/assets/6ad2add2-dc14-4bee-975d-bb5543e30637)

**Comment by MrOtherGuy** [comment]
I generally wouldn't make much changes yet for sidebar and titlebar related styles because they are in the process of changing quite a lot. But this is a simple addition with no downsides for pre-132 versions so there you go.
