### ISSUE TITLE
multi-row_tabs.css broken in FF76 ?

### ISSUE THREAD

**Issue by RichardGe** [MrOtherGuy/firefox-csshacks#41]
Hi, looks like the multi-row_tabs.css doesn't work correctly with FF76.

I now have a vertical slide bar on the right of my tabs.

![image](https://user-images.githubusercontent.com/2279126/81126370-5c251d00-8f3b-11ea-8d5d-bd529f662183.png)

**Comment by MrOtherGuy** [comment]
Please confirm that you are using the latest version of that style. There were indeed some changes but to tabs area but I made changes to them already. Still, it's very possible that I missed something.

**Comment by thePanz** [comment]
Updating to the latest version of this repository fixed the issue for me (note: I am importing only the `multi-row_tabs.css` file)
My  `userChrome.css` is:
```
@import url(chrome/multi-row_tabs.css);

:root{
    --multirow-n-rows: 2;
    --multirow-tab-min-width: 170px;
}

/**
 * Style the Tab's closing icon
 */
.tabbrowser-tab:not([pinned]) .close-icon {
   fill: #c00 !important;
   border: solid 1px #ccc !important;
   display:-moz-box !important;
}

/**
 * Style the active tab 
 */
.tab-background[selected="true"] {
  background-color: #b6dbe3 !important;
}
```

**Comment by RichardGe** [comment]
I confirm latest multi-row_tabs.css ( ee78d23 ) is working with my FF76.
Thanks !
