### ISSUE TITLE
autohide_sidebar.css doesn't expand on mouse hover in ff v132

### ISSUE THREAD

**Issue by sdsucks** [MrOtherGuy/firefox-csshacks#410]
i updated ff to v132 b1 today and the sidebar doesn't expand on mouse hover.

rolled back to v131, it still works in v131.

**Comment by MrOtherGuy** [comment]
Make sure you have updated the style. As far as I can tell it works fine in Nightly 133, and it worked few days ago in Nightly 132 as well. 132b1 isn't available yet - or at least developer edition doesn't update automatically to it - so I can't really test, but it would be kinda weird IMO if it wouldn't work

**Comment by sdsucks** [comment]
i manually downloaded v132 b1 from their FTP.

what do you mean "update the style"?

**Comment by MrOtherGuy** [comment]
Okay. I mean make sure to just [grab a fresh copy of autohide_sidebar.css](https://github.com/MrOtherGuy/firefox-csshacks/blob/master/chrome/autohide_sidebar.css) in case you tried to use an old local copy of it. But if the latest version isn't working then I need to check what's up with 132b1 - once it is distributed as an update.

**Comment by sdsucks** [comment]
you're right!
latest copy of it have 2 more lines than my local copy!
it works just fine now. thank you.

**Comment by MrOtherGuy** [comment]
Allright cool, good to hear it works.
