### ISSUE TITLE
Firefox newest versio 131.0 the CSS Multi Tab not working.

### ISSUE THREAD

**Issue by andizaa** [MrOtherGuy/firefox-csshacks#415]
https://github.com/MrOtherGuy/firefox-csshacks/blob/master/chrome/multi-row_tabs.css
Hi guys Firefox newest versio 131.0 the CSS Multi Tab not working.
just update firefox to its latest version yesterday, the css multi tab not working. The day before yesteray it still worked.

**Comment by MrOtherGuy** [comment]
Make sure you are using up-to-date version of that style - it should work fine with 131.

**Comment by andizaa** [comment]
Oh, I didnt think of that. Is this https://github.com/MrOtherGuy/firefox-csshacks/blob/master/chrome/multi-row_tabs.css the updated css file?

**Comment by MrOtherGuy** [comment]
Yes, that's the one.

**Comment by rp10007** [comment]
Alas, freshly-downloaded doesn't work here for 131.02 on mac (12.7.6). It produces a single line of tabs. Meanwhile, the version at https://github.com/replete/firefox-userchrome/blob/main/multi-row-tabs.css, which says it's sourced here, gives multiple rows but doesn't respect the maximum rows before scrolling limit.

**Comment by MrOtherGuy** [comment]
Do you use some other styles in addition to multi-row_tabs.css? The latest version should work fine as far as I know. However, if this is an issue specifically affecting mac then I'm afraid I cannot help you much because I don't have access to any mac system to test stuff with.

**Comment by rp10007** [comment]
So very sorry.  Typo in my import. (Your file has an underscore in the name, and the file I was alternating with has all hyphens.) Fixed that and the trouble went away on both linux and Mac.

**Comment by MrOtherGuy** [comment]
No worries, good to hear it works anyway. I'll close this issue.
