### ISSUE TITLE
z-index? problem with autohide_toolbox + autohide_sidebar

### ISSUE THREAD

**Issue by sdsucks** [MrOtherGuy/firefox-csshacks#417]
toolbox should be on top of sidebar on mouse hover but after today's update(not so sure) my nightly looks like this.
![nightly v133](https://github.com/user-attachments/assets/5e06a1ec-75f8-4375-b747-90b95b8e38ec)

while beta v132.b3 looks alright as intended.
![beta v132b3](https://github.com/user-attachments/assets/53cc5b2f-fcb1-4ed4-910f-57849176c8d5)

both beta and nightly have the exact same css and setup.

**Comment by MrOtherGuy** [comment]
I'm not sure if this is how I want to fix that issue, but in the mean time you can just slap this bit at the end of your userChrome.css file:

```css
:root{
  --browser-area-z-index-toolbox: 2 !important;
}
```

**Comment by sdsucks** [comment]
that fixes it!

thank you!
