### ISSUE TITLE
Please, a fix for vertical_popup_menubar.css (broken past 10/03/2024 by Nightly 133.0a1)

### ISSUE THREAD

**Issue by Lepefe** [MrOtherGuy/firefox-csshacks#418]
Hi @MrOtherGuy 

Since past 10/03/2024, Nightly 133.0a1 broke many of your mods. I'm sure you're aware of that, because I can see you're busy fixing and updating your stuff (thank you).

Please, I would like to request you to fix your [vertical_popup_menubar.css](https://github.com/MrOtherGuy/firefox-csshacks/tree/master/chrome/vertical_popup_menubar.css).

I have a medium level CSS knowledge, and I always try to make my own fixes before asking for help. So, as a second request, but it's not a priority, please I would like to understand what happened at Nightly 133.0a1 (10/03/2024) in order to learn by myself how to make the fixes in the future. I took a look here:

https://hg.mozilla.org/mozilla-central/pushloghtml

https://mrotherguy.github.io/fx-nightly-changelog/

but I couldn't identify the CSS changes. So if possible, please it'll be great if you can explain to me how to identify the changes.

Thank you!

**Comment by MrOtherGuy** [comment]
Should be fixed now. If you want to dig into the cause - it's changes from [bug 1899598](https://bugzilla.mozilla.org/show_bug.cgi?id=1899598 ) that mostly affect things.
