### ISSUE TITLE
newtab_background_color.css not working in firefox 77?

### ISSUE THREAD

**Issue by Huhni** [MrOtherGuy/firefox-csshacks#42]
I'm using Firefox Beta (77.0b3) with the Custom New Tab Page Extension and whenever I open a new tab it flashes white at first, it doesn't seem to be related to the extension though, because it happens before the extension is even loaded.
The only thing that helped was to set `browser.display.background_color` to black in about:config, but that breaks all plaintext sites and some websites that don't set a custom background-color.

I already tried a bunch of other userContent.css snippets, but none of them seemed to work.
Examples I tried:
```
@-moz-document url("about:home"),url("about:blank"),url("about:newtab"),url("about:privatebrowsing"){
  body{ background-color: #000 !important }
  html:not(#ublock0-epicker), html:not(#ublock0-epicker) body, #newtab-customize-overlay {
    background: #000 !important;
  }
}
```
```
@-moz-document url(chrome://browser/content/browser.xul) {
   browser[type="content"], browser { background: #000 !important; }
}
```
```
body{ --newtab-background-color: #000000 !important }
```

I'm not sure what to do anymore. The flickering is driving me crazy, but I also don't want to break everything with the `browser.display.background_color` setting.

The blank_page_background.css from here didn't seem to fix it either

**Comment by MrOtherGuy** [comment]
You should bring up this issue to the developers of that extension and/or change the page that you are setting as new tab via that extension.

Styles in this repository modify Firefox built-in pages not any arbitrary page you may stumble upon to.

**Comment by Huhni** [comment]
I did, but they said it's [outside their control and apparently firefox related](https://github.com/MethodGrab/firefox-custom-new-tab-page/issues/3#issuecomment-625896706)?


Do you know if it's possible to set a style to extension pages? I thought it would be either affected by the blank page or newtab page, but since those methods didn't work it seems to be something different?

Modifying my custom website to set background-color to black inline instead of in the external css file didn't work either, so I think it's really just the default firefox background color showing up before the extension and website is even loading.

**Comment by MrOtherGuy** [comment]
I haven't used but looking at the source code of that extension I would assume that you should apply your dark background via userContent.css to both about:blank and whatever address you are setting as you new tab url via the extension options.

**Comment by Huhni** [comment]
Using the dark theme in the extension makes the white flash shorter, but it's still there, even though I've set the about:blank page to black in userContent.css, maybe it's some weird bug, because it's an iframe?
I have an idea though, is it possible to set the about:config option `browser.display.background_color` via userContent or userChrome? Because if so, I could set it to black, but with a quick css transition to white, so that it will initially show up black and avoid the white flashing, but plaintext pages will stay readable after it turns white

**Comment by rediffusion** [comment]
Hi, Y'all! 👋
 Can you tell me how this `chrome/blank_page_background.css` works?
I'm just putting it in this file `userChrome.css`. I can't figure out what gonna be happen.

Cheers!

**Comment by MrOtherGuy** [comment]
It sets background-color for the blank area behind web-content. Typically you won't ever see it but there are some circumstances where you might.

**Comment by MrOtherGuy** [comment]
For example if you are or some web page and then open a link that opens in a new tab and switch to it immediately. Then you might see this blank area before any web content gets drawn.

**Comment by rediffusion** [comment]
@MrOtherGuy 
 Ahahahah, brother, now I see 😄👁️
Do you use it? It helps you to concentrate or don't lose something interesting from your eye.

**Comment by MrOtherGuy** [comment]
Nope, I barely use any of the styles in this repository - apparently 9 of them. And then some additional rules for just coloring stuff, and a handful of random other simple rules.
