### ISSUE TITLE
Auto-hiding Toolbox Not Reappearing When Dragging Tabs in GNOME

### ISSUE THREAD

**Issue by korason7117** [MrOtherGuy/firefox-csshacks#421]
When using autohide_toolbox.css, the toolbox behaves as expected in KDE (remains visible during tab dragging, allowing easy repositioning of tabs), but in GNOME, the toolbox does not reappear when hovering after starting a tab drag. This prevents users from repositioning dragged tabs in GNOME

## Steps to Reproduce:
1. Apply the provided custom CSS for auto-hiding the Firefox toolbox.
2. Maximize the Firefox window or work in a non-fullscreen mode.
3. Attempt to drag a tab in GNOME and reposition it in the tab bar.
4. The toolbar hides and does not reappear when hovering or interacting.

## Expected Behavior:
The toolbar should reappear when the user drags a tab and hovers over the toolbar or tab area, allowing the dragged tab to be repositioned easily.

## Actual Behavior:
In GNOME, the toolbar goes into auto-hide mode when a tab is dragged and does not reappear on hover, preventing tab repositioning. This behavior differs from KDE, where the toolbox remains visible and interactive during tab dragging.

## Environments Affected:
Working as expected: KDE (Wayland) with the same CSS.
Issue present: GNOME (Wayland) environment.

## Potential Cause:
There may be differences in how GNOME handles window focus, hover, and drag events in Firefox, particularly when custom CSS overrides are used. GNOME’s window manager might interfere with Firefox’s ability to trigger hover events during drag operations.

System:
Archlinux GNOME 47 (Wayland) tested with no extensions enabled.

**Comment by MrOtherGuy** [comment]
At first glance this sounds like #275 - which in turn is a more [general bug](https://bugzilla.mozilla.org/show_bug.cgi?id=1818517) about an issue involving drag sessions.

So what you could do is test if setting `widget.gtk.ignore-bogus-leave-notify` to `1` solves that particular issue - but like mentioned in that bug I don't know if doing so would cause some other issues.
