### ISSUE TITLE
Content in URL bar is invisible except on mouse-over.

### ISSUE THREAD

**Issue by vurtomatic** [MrOtherGuy/firefox-csshacks#422]
Firefox 131.0 (aarch64)
MacOS 14.7 (23H124)

Hi there, sorry this might be vague, this only happened after the recent 131.0 (aarch64) update.

The content in the URL bar, including icons and text, is invisible after I updated to 131.

They only appear on mouse over.

First time looking for help here, is there more info I can provide?

This is what I'm using:

@import url(chrome/compact_proton.css);
@import url(chrome/compact_urlbar_megabar.css);
@import url(chrome/custom_menupopup_check_icons.css);
@import url(chrome/autohide_bookmarks_and_main_toolbars.css);
@import url(chrome/combined_favicon_and_tab_close_button.css);
@import url(chrome/floating_findbar_on_top.css);
@import url(chrome/grid_overflow_menu.css);
@import url(chrome/hide_tabs_scrollbuttons.css);
@import url(chrome/hide_urlbar_first_row.css);
@import url(chrome/inline_tab_audio_icons.css);
@import url(chrome/minimal_in-UI_scrollbars.css);
@import url(chrome/minimal_text_fields.css);
@import url(chrome/non_floating_sharp_tabs.css);
@import url(page_action_buttons_on_urlbar_hover.css);
@import url(chrome/tab_loading_progress_bar.css);
@import url(chrome/tabs_fill_available_width.css);
@import url(chrome/change_urlbar_border_focus_color.css);
@import url(chrome/monochrome_addon_icons.css);

**Comment by MrOtherGuy** [comment]
I'm not sure about all the otherstyles, but minimal_text_fields.css apparently caused this kind of behavior. I've patch that style now so update to it and see how it goes.

**Comment by vurtomatic** [comment]
> I'm not sure about all the otherstyles, but minimal_text_fields.css apparently caused this kind of behavior. I've patch that style now so update to it and see how it goes.

I believe that fixed it, thank you!

**Comment by MrOtherGuy** [comment]
Very good. Thanks for reporting!
