### ISSUE TITLE
[Request] Can we build a load progress bar into the Urlbar?

### ISSUE THREAD

**Issue by clifford269** [MrOtherGuy/firefox-csshacks#423]
I'm working on a Firefox theme and this will be a great addition to it!

**Comment by MrOtherGuy** [comment]
Maybe. I think it would basically work like "status_inside_urlbar.css", but in addition we create background-image to statuspanel to fake an appearance of loading progress.

**Comment by clifford269** [comment]
I do not want to fake it. Real one possible? I guess this is a real one alright that does it within the webpage https://github.com/luben/load-progress-bar/issues

**Comment by MrOtherGuy** [comment]
In that case no, it isn't possible. Page loading progress isn't available anywhere for css to use. Only states "connecting", "loading" and "done" are available. Anything between has to be guessed somehow i.e. fake.

**Comment by clifford269** [comment]
I know, and I'm all in for using JS. Here's some code which does it-https://github.com/luben/load-progress-bar.
If we can move it in the Urlbar, then we're golden.

**Comment by MrOtherGuy** [comment]
Okay, if you are doing javascript hackery then you you can really write whatever you want and have it behave pretty much how you like. But I can't help you with that and it is very much out scope for this repository.
