### ISSUE TITLE
window_control_placeholder_support.css: Cannot click on windows control button

### ISSUE THREAD

**Issue by kkhoa312** [MrOtherGuy/firefox-csshacks#425]
Just like the title. I'm using Firefox 133.0a1.

Even though the tooltip is still visible, I cannot click on it. Besides, when I right-click on it, the menu appears, similar to when I click on the toolbar.

![firefox_Ds6RbduVKt](https://github.com/user-attachments/assets/ee5a25bd-2419-448e-826d-8cab9bf7f203)

The script still works properly on 132.0b1.

![firefox_Tn3QvSc7FE](https://github.com/user-attachments/assets/f97605b8-f520-49a3-a515-f470254f2bbb)

**Comment by MrOtherGuy** [comment]
What are you using window_control_placeholder_support.css for? For many purposes that style will be unnecessary with Fx133 - for example hiding tabs toolbar can be done much simpler and better [like this](https://github.com/MrOtherGuy/firefox-csshacks/blob/master/chrome/hide_tabs_toolbar_v2.css). The only reason that style looks complicated is to handle systems where the window control buttons are on other side.

**Comment by kkhoa312** [comment]
It works perfectly, thank you!

**Comment by kkhoa312** [comment]
> What are you using window_control_placeholder_support.css for? For many purposes that style will be unnecessary with Fx133 - for example hiding tabs toolbar can be done much simpler and better [like this](https://github.com/MrOtherGuy/firefox-csshacks/blob/master/chrome/hide_tabs_toolbar_v2.css). The only reason that style looks complicated is to handle systems where the window control buttons are on other side.

Thank you! It works, but now, whenever I watch a fullscreen video, the Windows buttons appear on the top-left of the video.

![firefox_L1cUVJGbEh](https://github.com/user-attachments/assets/1e31c274-698c-4fd9-9406-1b9a5940206d)

**Comment by MrOtherGuy** [comment]
Interesting. I'll fix that later, thanks for heads-up.

**Comment by MrOtherGuy** [comment]
Hmm. Turns out that I am unable to reproduce that issue. To be honest, I think it's kinda weird if that would even have with the rules that style applies. Are you using some other styles as well that might be the cause here?

**Comment by kkhoa312** [comment]
Oh, I've found out that the toggle_tabs_toolbar_with_alt.css is the reason. I turned off that style, and everything worked perfectly. I don't need toggle_tabs_toolbar_with_alt.css anyway. Thank you so much for your help!

**Comment by MrOtherGuy** [comment]
Alright cool.
