### ISSUE TITLE
Window_Control_Placeholder_Support and Tabs_On_Bottom not working for me

### ISSUE THREAD

**Issue by Lepefe** [MrOtherGuy/firefox-csshacks#426]
Hi there!

It seems that at the past two weeks, unfortunately, the new Nighties are breaking many of your great mods.

Today, the latest Nightly broke your combo: [window_control_placeholder_support.css](https://github.com/MrOtherGuy/firefox-csshacks/tree/master/chrome/window_control_placeholder_support.css) & [chrome/tabs_on_bottom.css](https://github.com/MrOtherGuy/firefox-csshacks/tree/master/chrome/tabs_on_bottom.css) ... at least for me, I can't make them work.

Hope you can fix them.

Thanks in advance!

**Comment by MrOtherGuy** [comment]
I'm not going to fix those because 133 allows us to do it much better. I just haven't had time to figure out how to organize new styles.

**Comment by MrOtherGuy** [comment]
I forgot I had already pushed the new version - [tabs_on_bottom_v2.css](https://github.com/MrOtherGuy/firefox-csshacks/blob/master/chrome/tabs_on_bottom_v2.css)

Note, you won't need the placeholder support style anymore.

**Comment by Lepefe** [comment]
@MrOtherGuy thanks a lot!

I have some stuff on the top right corner, so in order to make space for the 3 window buttons I just needed to add your other mod:

#nav-bar{
  border-inline: var(--uc-window-drag-space-pre,0px) solid transparent;
  border-inline-style: solid !important;
  border-right-width: calc(var(--uc-window-control-width,0px) + var(--uc-window-drag-space-post,0px));
  background-clip: border-box !important;
}

Now it works perfectly! It works 100% exactly as it was working before breaking yesterday.

Thank you once again!
