### ISSUE TITLE
is there Chrome version of this? 

### ISSUE THREAD

**Issue by andizaa** [MrOtherGuy/firefox-csshacks#428]
is there Chrome version of this?

**Comment by MrOtherGuy** [comment]
No. Chromium (and thus Chrome aswell) doesn't have any such mechanism to let users configure its UI layout. It's possible that some Chromium fork might have such feature to some extent, but it is a completely different program and as such the actual styling code would be completely different.

In any event, I have zero interest in Chromium browsers so any customization regarding them, possible or not, is out of the scope of this repository.
