### ISSUE TITLE
CSS to disable middle click tab bar

### ISSUE THREAD

**Issue by ZetiX** [MrOtherGuy/firefox-csshacks#43]
I know this isn't really directly related to the repo but I'm trying to learn how to modify the existing CSS I have to work with V76. I tried posting the firefox related forum again but haven't received any replies.

This is what I have now to disable middle clicking on the empty portion of the tab bar to prevent the creation of new tabs. But I'm not sure what I should change. Any help on where I should look for information regarding this would be extremely helpful. 
```
/* Disable Middle Click Tab Bar */
#tabbrowser-tabs :-moz-any(.arrowscrollbox-scrollbox, .tabbrowser-arrowscrollbox) {pointer-events: none}
.tabbrowser-tab, #tabs-newtab-button, .tabs-newtab-button {pointer-events: auto}
.scrollbutton-up, .scrollbutton-down {pointer-events:auto !important}
.new-tab-popup, .new-tab-popup > * {pointer-events: auto}
```
I think it's something to do with the selectors changing in the new FF version but I'm not really great at CSS so I could be wrong.

**Comment by MrOtherGuy** [comment]
I ended up creating a working version for this feature in the repository.
[Find it here](https://github.com/MrOtherGuy/firefox-csshacks/blob/master/chrome/disable_newtab_on_middle_click.css)
