### ISSUE TITLE
The autohide sidebar stopped working.

### ISSUE THREAD

**Issue by kkhoa312** [MrOtherGuy/firefox-csshacks#431]
The problem in #408 happens again in Firefox Nightly.

**Script**: autohide_sidebar.css
**Firefox version**: 133.0a1

![firefox_Wj074E64VK](https://github.com/user-attachments/assets/d72949de-0547-4821-b9fe-40e4d8694501)

**Comment by MrOtherGuy** [comment]
This should work for now, but I'd imagine that there's going to be more changes sooner or later with the new sidebar stuff.
