### ISSUE TITLE
Autohide toolbox / toolbar not showing on hover

### ISSUE THREAD

**Issue by deadcombo** [MrOtherGuy/firefox-csshacks#432]
Hi,

Nightly 133 broke the toolbox autohide, it no longer reveals when I place the mouse at the top of the window. New tab shows the urlbar when typing and afterwards it stays down permanently but not the other toolbox elements.

Thank you for your work.

**Comment by MrOtherGuy** [comment]
So, the deal here is that `#urlbar` is now a popover (to deal with some sidebar related things). That makes styles like autohide_toolbox.css super tricky. I mean, we can totally make the toolbox itself show up and all - but positioning of urlbar will require some rather crafty things.

I've made some changes that make the style kinda work, but it will require more work to have it work well.

I assume other styles that autohide toolbars will be affected as well by urlbar changes.

**Comment by datguypiko** [comment]
> So, the deal here is that `#urlbar` is now a popover (to deal with some sidebar related things). That makes styles like autohide_toolbox.css super tricky. I mean, we can totally make the toolbox itself show up and all - but positioning of urlbar will require some rather crafty things.
> 
> I've made some changes that make the style kinda work, but it will require more work to have it work well.
> 
> I assume other styles that autohide toolbars will be affected as well by urlbar changes.

yeah the bookmarks bar popout stopped working too.

**Comment by deadcombo** [comment]
Cheers for fixing it. Unfortunate, I'm glad they're actually adding some useful features but still can't beat CSS + Sidebery.
