### ISSUE TITLE
any way to hide title bar on `popup` window?

### ISSUE THREAD

**Issue by u-Sir** [MrOtherGuy/firefox-csshacks#435]
![图片](https://github.com/user-attachments/assets/601a4070-d615-4461-a7fe-8590bcd9c997)
any way to hide title bar on `popup` window? 
type of window is `popup`, not `normal`

**Comment by MrOtherGuy** [comment]
The one pictured is OS native titlebar, it is not part of the window document and thus cannot be styled with CSS.
