### ISSUE TITLE
autohide_bookmarks_and_main_toolbars.css : address bar stay after 133.0b1 update

### ISSUE THREAD

**Issue by Stinger10X** [MrOtherGuy/firefox-csshacks#436]
As per title, the address bar did not hide.
![img-2024-10-30-00-19-36](https://github.com/user-attachments/assets/65b005bf-7a4f-4d9b-a27a-31cc635e31ad)

**Comment by MrOtherGuy** [comment]
Yes, there's a few changes in 133 that make styles that hide the area where urlbar is supposed to be have some complications. In this specific style I was able to just apply separate transformation to urlbar to make it work though.

**Comment by zZombieBatman** [comment]
I didn't want to create a new issue since it is pretty much this same one, but is there any way 'autohide_main_toolbar.css' can be updated to also resolve the same issue? thank you.

**Comment by MrOtherGuy** [comment]
I've updated that style as well now.
