### ISSUE TITLE
Icon Only Tabs Overlapping since FF 132.0 (64-bit)

### ISSUE THREAD

**Issue by primewaydesign** [MrOtherGuy/firefox-csshacks#439]
Hi,

I'm using the Icon Only Tabs hacks on latest FF 132.0 (64-bit), but it's overlapping and it's not user-friendly.
This is how it looks:
![Screenshot_1](https://github.com/user-attachments/assets/f780dadc-9848-44f6-9898-b95556baac44)

Note: Pinned tabs are not affected from this issue.

Can someone help please?

**Comment by primewaydesign** [comment]
Upon reviewing the css, I had to modify the min-width slightly and the now it looks good again.
I had to modify line 15 and 17 to:

`.tabbrowser-tab[fadein]{ min-width: calc(32px + 2 * 10px + 8px) !important; }
:root[uidensity="compact"] .tabbrowser-tab[fadein]{
  min-width: calc(32px + 2 * var(--inline-tab-padding,0px) + 8px) !important;
}`

**Comment by MrOtherGuy** [comment]
Hmm, okay so apparently this affects only compact density. Makes sense since apparently that style has density-specific rules - although I can't remember why.

Anyways, this is issue happens because a variable name change `--inline-tab-padding` `->` `--tab-inline-padding` and I've fixed it now.
