### ISSUE TITLE
Both nav-bar and multirow tabs below content broken on FF 76

### ISSUE THREAD

**Issue by nulltab** [MrOtherGuy/firefox-csshacks#44]
Hi. 

This is a continuation of https://github.com/MrOtherGuy/firefox-csshacks/issues/33
My config stopped working since FF 76 update - tabs are not multi-row anymore...

With this (my original config) - https://gist.github.com/nulltab/74a4ffe86b99cfb2932aeb1e78237727 
I see only one row of tabs and a small ugly black square instead of a tab scroll button.

I also tried to grab newest changes from the repo - https://gist.github.com/nulltab/1ccf0f687404f093579910099f41216e - in this case I see just one row of tabs, no scroll buttons.

Could you please help?
Thanks!

**Comment by MrOtherGuy** [comment]
Oh right, I should've given that the same treatment as "normal" multi-row_tabs.css

I've updated it now, but filename got changed - its just multi-row_tabs_below_content.css now.

But what do you mean by "nav-bar" in your title?

**Comment by MrOtherGuy** [comment]
Oh I see what you meant by nav-bar now. Those should also be fixed now (I hope)

**Comment by nulltab** [comment]
Thanks again! 

My resulting file in case if anybody needs same thing - https://gist.github.com/nulltab/61cacf3d207d835bce9a51115962f82a

Looks like this: 

![2020-05-11-125239_1919x1049_scrot](https://user-images.githubusercontent.com/28522111/81548710-5c337b80-9386-11ea-9f4c-92d638961bfc.png)
