### ISSUE TITLE
Sidebar goes on top of the website / website full width behind sidebar. 

### ISSUE THREAD

**Issue by lmndk** [MrOtherGuy/firefox-csshacks#447]
Hi. Since last FF update (132.0.2) the webpage content goes behind the sidebar.

![{6C2C0038-1AD2-4AFE-9765-7C9A0D08CA42}](https://github.com/user-attachments/assets/62561050-6ecc-4ef5-8ef3-c535bb1414b3)

I tried to fix it, but comes up blank.

**Comment by MrOtherGuy** [comment]
Make sure you are using up-to-date version of authohide_sidebar.css - it should work fine.
