### ISSUE TITLE
window_control_placeholder_support.css + hide_tabs_toolbar.css fullscreen causes window controls to snap to the top left

### ISSUE THREAD

**Issue by LilyArlatto** [MrOtherGuy/firefox-csshacks#448]
If I hit F11 on a regular webpage or fullscreen a YouTube video, the window controls will appear in the top left. They stay there permanently on the YouTube video, but stick to the address bar when I move my mouse up to make it appear on webpages.

![image](https://github.com/user-attachments/assets/7a2616e6-f7b8-4b60-b734-fdd73edfd763)

![image](https://github.com/user-attachments/assets/f3e88fbf-d4a2-48da-b9c6-646144ab57f6)

**Comment by MrOtherGuy** [comment]
Can you confirm that you are using latest versions of both files? As far as I can tell this issue doesn't happen on Firefox 132.0.2 - but do note that from Firefox 133 onwards you should just be using [hide_tabs_toolbar_v2.css](https://github.com/MrOtherGuy/firefox-csshacks/blob/master/chrome/hide_tabs_toolbar_v2.css) **without** the support style.

**Comment by LilyArlatto** [comment]
I'm on 132.0.2. If I don't add the extra line to move the Menu button to the left, it ends up overlapping with the close button. And yes, the issue persists with a fresh download of hide_tabs_toolbar.css and window_control_placeholder_support.css.

**Comment by MrOtherGuy** [comment]
How are you using those files?  Are you importing them into userChrome.css or are you pasting the content directly into userChrome.css? If the latter, then doesn't your userChrome.css contain anything else?

**Comment by LilyArlatto** [comment]
I had to make my Chrome\userChrome.css to do this because I just got a different tab manager today, I pasted the hide_tabs_toolbar into the userChrome.css and I have the window_control_placeholder_support.css as an extra file in the Chrome folder. Should I have pasted them one after the other in userChrome.css?

**Comment by MrOtherGuy** [comment]
Oh okay. Yes, you can paste the contents of both files into userChrome.css. Alternatively, you can make userChrome.css *import* one or both of the files:

example import:

```css
@import url("window_control_placeholder_support.css");
@import url("hide_tabs_toolbar.css");

/* Add any other style rule you may wisth to userChrome.css below */

```

**Comment by MrOtherGuy** [comment]
Note that if using imports, the `@import` statements must be placed before anything else in the file.

**Comment by LilyArlatto** [comment]
Yep, that fixed it, thank you! By the way, is there a variable to reduce the distance between the menu button and the window controls? 
![image](https://github.com/user-attachments/assets/e239b444-1322-426f-be5a-6f8606bdbe98)

**Comment by MrOtherGuy** [comment]
Yes, you can decrease the value [on line 16 of window_control_placeholder_support.css](https://github.com/MrOtherGuy/firefox-csshacks/blob/14f2c867e741668270df1b83fd7e4e89c2684186/chrome/window_control_placeholder_support.css#L16)

**Comment by LilyArlatto** [comment]
Hey, sorry to kinda reopen this again, but Firefox finally updated to v133 and broke the old version (as expected), so I moved to hide_tabs_toolbar_v2.css. but I don't see an obvious way to adjust the grab space beside the controls in this version. Is that not possible with the new method used, or is it a future feature that has yet to be added somehow?

**Comment by MrOtherGuy** [comment]
I'm don't really want to add such method because adjusting that width isn't what the style is about. In the old version we had to define custom width there anyway, but now we can just use whatever Firefox is using.

To modify the width you can add this though:

```css
.titlebar-spacer[type="post-tabs"]{ width: 20px !important }
```

**Comment by LilyArlatto** [comment]
Thanks again, I really appreciate it. And sorry to bother you again for something so simple, I don't really know much about css or anything, so your help means a lot. 🙏
