### ISSUE TITLE
Tab separator visible after clicking on firefox-view-button

### ISSUE THREAD

**Issue by Zonnev** [MrOtherGuy/firefox-csshacks#450]
Hello, first many thanks for the tab separator solution. The only thing is I can not figure out a good solution for this problem with a separator showing after clicking on the `#firefox-view-button`, selecting the first tab again and adding another tab and then selecting the first tab again. 

I think it has to do with the state of the firefox-view-button. There is one change that stays when this button is clicked: `aria-controls="panel-1-2"` (when 2 tabs are opened), but I can not find a way to include this in your code for the tab separators.

This is showing:
![Screenshot-2024-11-26-15:17:18](https://github.com/user-attachments/assets/7effe0d8-77d4-441f-95b7-fbfd450227bc)

It's not a big issue, but it would be perfect if it was solved.
Thanks in advance for your help.

**Comment by MrOtherGuy** [comment]
Sorry but, I can't quite figure out what the issue is or how to reproduce it. Can you clarify a bit?

**Comment by Zonnev** [comment]
Follow these steps on Firefox 133:

1. click on the firefox view button (suitcase icon button on the far left of tab bar), it will open the firefox view page.
2. click on the first tab (it will close the firefox view page).
3. make another tab, you have two tabs open now.
4. click on the first tab again and the 'unwanted' separator is visible.

At least, this happens at my side. I hope this helps you further.

**Comment by MrOtherGuy** [comment]
Sweet, yeah I know what's wrong. But fixing it properly is not simple. This essentially happens if you have *any* hidden tabs - not just the one created by firefox-view button. I could add a special case though for the scenrio where there is only one hidden tab after the selected tab which would fix the issue for firefox-view.
