### ISSUE TITLE
non_floating_sharp_tabs.css - Fx133 update

### ISSUE THREAD

**Issue by corobin** [MrOtherGuy/firefox-csshacks#451]
Hello,

Fx133 update broke non_floating_sharp_tabs.css again.

bottom line under the active tab

![Capture](https://github.com/user-attachments/assets/c3c7d92c-d0a5-4e1b-9d7d-ee20fada9c15)

fresh profile with only non_floating_sharp_tabs.css

thanks!

**Comment by MrOtherGuy** [comment]
Yeah, that's a simple fix - thanks for reporting
