### ISSUE TITLE
Firefox 133 broke autohide_bookmarks_and_main_toolbars.css

### ISSUE THREAD

**Issue by Asinin3** [MrOtherGuy/firefox-csshacks#455]
Using https://github.com/MrOtherGuy/firefox-csshacks/blob/master/chrome/autohide_bookmarks_and_main_toolbars.css for a number of years and been happy with it. But FF 133.0 broke the script, I updated to latest and its still not displaying properly:
![image](https://github.com/user-attachments/assets/dcc76a2a-0908-4946-aa54-2f3b274bfb52)
The navigation bar floats ontop of everything and doesn't autohide. And everything thats to the left-right of it e.g the search box, the back/forward buttons, the buttons for browser extensions etc are all missing

**Comment by JffLcrx** [comment]
Hi, had the exact same problem, but resolved it by deleting userChrome.css, opening and closing Firefox and creating a new userChrome.css and copy-pasting this code: https://github.com/MrOtherGuy/firefox-csshacks/tree/master/chrome/autohide_bookmarks_and_main_toolbars.css

Thanks a million @MrOtherGuy for everything.

Now if only I could do the same with the sidebar. But I'm not able to make it auto hide and pop on mouse hover anymore...

**Comment by Asinin3** [comment]
@JffLcrx That didn't change anything for me. Strangely enough even if i delete the userchrome file, disable all addons/extensions and restart FF it still shows up like that. Unless i open FF in safe/troubleshoot mode. Tried going through about:config and removing all the settings i had set but its the same.. :/

**Comment by JffLcrx** [comment]
Sorry, it didn't work. I'm just messing around with stuff I don't fully understand to see what works for me and that did the trick.

Interestingly, the css code for [autohide_sidebar.css](https://github.com/MrOtherGuy/firefox-csshacks/blob/master/chrome/autohide_sidebar.css) does not work for me the way it is (it doesn't hide) but work flawlessly when I move the side bar to the right. But with the scroll bat on that side too, it's problematic not to hover on both at the same time.

**Comment by Asinin3** [comment]
I cleaned out my entire about:config, and its fixed now.. no idea which one caused the problem as i had to restart FF for changes to take affect.
