### ISSUE TITLE
FF 133 broke tabs_on_bottom.css

### ISSUE THREAD

**Issue by CurePindal** [MrOtherGuy/firefox-csshacks#456]
tabs_on_bottom.css is no longer working in FF 133.

edit: sorr, noticed too late its reported here:
https://github.com/MrOtherGuy/firefox-csshacks/issues/438

**Comment by artemlive** [comment]
It's the same to me.

**Comment by madeddy** [comment]
Did you also try _tabs_on_bottom_v2.css_ ?

**Comment by artemlive** [comment]
@madeddy I tried and it doesn't work. 
And there is another [report.](https://github.com/MrOtherGuy/firefox-csshacks/issues/438#issuecomment-2503708490)

**Comment by Laephis** [comment]
Also tried tabs_on_bottom_v2.css, FF 133 on Linux, and not working for me as well.

**Comment by mfrumento** [comment]
Any fix?

**Comment by MrOtherGuy** [comment]
> Any fix?

Yes, use tabs_on_bottom_v2.css instead.

I'm closing this as duplicate of 438.
