### ISSUE TITLE
Autohide_tabstoolbar_v2 compatible issues with oneline theme

### ISSUE THREAD

**Issue by rivers008** [MrOtherGuy/firefox-csshacks#457]
Using [this theme](https://github.com/newmanls/OnelineProton) with firefox 133. I tried all the autohide css, nothing works. = =

**Comment by MrOtherGuy** [comment]
I don't really understand what you would even expect to happen if you have such oneline setup and autohide tabs toolbar.

**Comment by rivers008** [comment]
auto hide the oneline navbar, minimal interface. lol

**Comment by rivers008** [comment]
You're right,  Auto hide works, but the whole tabstoolbar section is gone. Sorry, I'm not a code guy.😂
I changed --uc-toolbox-rotation to  70deg. 
![Screenshot 2024-11-28 113059](https://github.com/user-attachments/assets/4be00b24-3f1c-498b-90c4-974506b1b63c)

**Comment by MrOtherGuy** [comment]
One simple thing that comes to mind that *could* be an issue is [lines 64-68](https://github.com/MrOtherGuy/firefox-csshacks/blob/e23b213d846b582817786f8e09ffc2807f733c37/chrome/autohide_toolbox.css#L64-L68) - chances are that this sets the navigation toolbar to be whole window width (thus covering tabs) - change that to the following and see what happens:

```css
#navigator-toolbox{
  width: 100vw;
  -moz-appearance: none !important;
}
```

Other than that, I have no clue because I don't know what that oneline style does.

**Comment by MrOtherGuy** [comment]
You can also try how [this oneline style](https://github.com/MrOtherGuy/firefox-csshacks/blob/master/chrome/navbar_tabs_oneliner.css) works with autohide_toolbox.css - some comments in autohide_toolbox.css indicate that it should work at least somewhat.

**Comment by rivers008** [comment]
> One simple thing that comes to mind that _could_ be an issue is [lines 64-68](https://github.com/MrOtherGuy/firefox-csshacks/blob/e23b213d846b582817786f8e09ffc2807f733c37/chrome/autohide_toolbox.css#L64-L68) - chances are that this sets the navigation toolbar to be whole window width (thus covering tabs) - change that to the following and see what happens:
> 
> ```css
> #navigator-toolbox{
>   width: 100vw;
>   -moz-appearance: none !important;
> }
> ```
> 
> Other than that, I have no clue because I don't know what that oneline style does.

I tried the codes as you mentioned, It doesn't work. Then I changed these to a static value which I set in the oneline theme:

`/* These two exist for oneliner compatibility */
#nav-bar{ width: var(--uc-navigationbar-width,390px) }
#TabsToolbar{ width: calc(100vw - var(--uc-navigationbar-width,390px)) }`

I don't really know what I'm doing, though It kind of  works. 😀😂
Thank you so much Friend.

**Comment by rivers008** [comment]
https://github.com/user-attachments/assets/895707f0-a4a7-4e70-a0d9-74ad67dc83e0

**Comment by MrOtherGuy** [comment]
Yeah sure, that works too. Good job, trying what happens when you change stuff is a good way to learn - happy hacking :)
