### ISSUE TITLE
FF 76 - no multirow displayed anymore

### ISSUE THREAD

**Issue by Cuervino** [MrOtherGuy/firefox-csshacks#46]
My FF automatically updated from 75 to 76 yesterday evening before shutdown.
When opening FF this morning, bad surprise: only 1 row is displayed instead of 3.
I think this line is no longer valid :
`:root{--multirow-n-rows: 3}`

**Comment by MrOtherGuy** [comment]
Did you try the latest version of the multi-row_tabs.css? It should work.

**Comment by Cuervino** [comment]
Yes, it worked. 
My bad, I had the version from December 2019 (and additional customization for having favicon on folder bookmarks.)
I checked, few discrepencies that I didn't fully understand.
I should have tried the last version before anything else.
Sorry for the request, thanks for this very nice job :-)
