### ISSUE TITLE
Firefox 133, compact_urlbar_megabar.css and non_floating_sharp_tabs.css

### ISSUE THREAD

**Issue by Dupond** [MrOtherGuy/firefox-csshacks#460]
Hello!

I use Firefox 133 with ArchLinux.

I tested with `compact_urlbar_megabar.css` only and nothing else in the `userChrome.css` file. Result: the address bar is in the middle of the browser window, 500 or 600 pixels below the rest of the toolbox... Weird... What's more, it takes up 100% of the screen width, and expands when you focus (so the code to prevent the bar from expanding no longer works for me).

Finally, in `non_floating_sharp_tabs.css`, the code to remove the dividing line between the tabs and the toolbar below no longer works. In other words, there's a bottom border on the active tab. I'm using the "System theme" with a dark theme.

Thank you very much for your help!

**Comment by MrOtherGuy** [comment]
Can't say anything about compact_ulrbar_megabar but I believe I fixed the non floating tabs separator issue yesterday, so make sure you update that style and see how it works.

**Comment by Dupond** [comment]
Not here: https://0x0.st/XRSX.png

It's a screenshot taken with nothing in my `userChrome.css` file, except the 140 lines of code from `non_floating_sharp_tabs.css`.

**Comment by Dupond** [comment]
Indeed! It's perfect now. Thank you very much!

As for the `compact_urlbar_megabar.css` script, I've removed the first few lines:

```
#urlbar[breakout]{
  margin-inline-start: 0px !important;
  width: 100% !important;
  left: 0 !important;
  top: calc((var(--urlbar-container-height) - var(--urlbar-height)) / 2 ) !important;
}
#urlbar[breakout]:not([open]){
  bottom: calc((var(--urlbar-container-height) - var(--urlbar-height)) / 2) !important;
}
```

And I replaced them with:

```
#urlbar[breakout][breakout-extend] {
    margin-left: 0 !important;
    width: var(--urlbar-width) !important;
    margin-top: calc((var(--urlbar-container-height) - var(--urlbar-height)) / 2) !important;
}
```
And everything is back to normal :)

**Comment by MrOtherGuy** [comment]
Yeah, that appears to work pretty well. Thanks! I'll update the style with this change.
