### ISSUE TITLE
Horizontal line on top of window using autohide_bookmarks_and_main_toolbars.css and autohide_tabstoolbar_v2.css

### ISSUE THREAD

**Issue by RedPyramids** [MrOtherGuy/firefox-csshacks#463]
Might be hard to see since it's dark grey but I have outlined it in the picture.
This is after I set --uc-navbar-height: to -32 instead of -40 (under #navigator-toolbox at the top of the code)

When it was using -40, I couldn't get the toolbars to show on hover.
Wondering if this might be a padding issue or something where I'm not able to hover over the right spot because it's moved too high or if there's something else I'm overlooking.

![Top_Horizontal_Line](https://github.com/user-attachments/assets/da7d2193-6857-4600-86e5-02fa08306053)

**Comment by MrOtherGuy** [comment]
Rather than using these two styles together, you should use instead use [autohide_toolbox.css](https://github.com/MrOtherGuy/firefox-csshacks/blob/master/chrome/autohide_toolbox.css).

**Comment by RedPyramids** [comment]
That seems to work!

Thanks for the quick response!
