### ISSUE TITLE
update styles to use customtitlebar attribute

### ISSUE THREAD

**Issue by kkhoa312** [MrOtherGuy/firefox-csshacks#464]
Just like the title. The windows buttons don't appear anymore. I'm using Firefox 135.0a1 btw.

![ảnh](https://github.com/user-attachments/assets/b0f1360a-17ad-4b94-90ce-6e9a58b398b1)

**Comment by MrOtherGuy** [comment]
You should not use window_control_placeholder_support.css for anything past Firefox 133.

Use one of the _v2 variant styles that don't need window_control_placeholder_support.css

**Comment by kkhoa312** [comment]
> You should not use window_control_placeholder_support.css for anything past Firefox 133.
> 
> Use one of the _v2 variant styles that don't need window_control_placeholder_support.css

I'm sorry! I've just checked, and I don't use window_control_placeholder_support anymore. So maybe it's hide_tabs_toolbar_v2's problem.

**Comment by MrOtherGuy** [comment]
Oh right, I missed that this was on nightly. I know what the problem is but I don't have to fix the styles. Essentially, you can replace `[tabsintitlebar]` [on line 26](https://github.com/MrOtherGuy/firefox-csshacks/blob/9e91c324608f479a6c65e56eba262b69a3291aa5/chrome/tabs_on_bottom_v2.css#L26) with `[customtitlebar]` and I'm pretty sure it will just work.

**Comment by kkhoa312** [comment]
> Oh right, I missed that this was on nightly. I know what the problem is but I don't have time to fix the styles right now. Essentially, you can replace `[tabsintitlebar]` [on line 26](https://github.com/MrOtherGuy/firefox-csshacks/blob/9e91c324608f479a6c65e56eba262b69a3291aa5/chrome/tabs_on_bottom_v2.css#L26) with `[customtitlebar]` and I'm pretty sure it will just work.

It works! Thanks!

**Comment by MrOtherGuy** [comment]
Great. Let's leave this issue open until I have time to go through all the styles that need to change.

**Comment by MrOtherGuy** [comment]
This should now be fixed
