### ISSUE TITLE
Firefox 133: "hide_tabs_toolbar" and "windows_control_placeholder_support" Not Displaying Minimize, Maximize, and Close Buttons

### ISSUE THREAD

**Issue by daniBrico** [MrOtherGuy/firefox-csshacks#467]
Hello! Some time ago, I started using the CSS code of `hide_tabs_toolbar` along with `windows_control_placeholder_support`.

`hide_tabs_toolbar` allowed me to hide the tab view, and `windows_control_placeholder_support` made sure the minimize, maximize, and close buttons did not conflict, keeping them in position at the top-right corner and maintaining their usability.

A few days ago, Firefox released an update, version 133. 

![Captura de pantalla 2024-11-29 154932](https://github.com/user-attachments/assets/9634275f-f61d-4d7c-be14-85394290034c)

![Captura de pantalla 2024-11-29 155117](https://github.com/user-attachments/assets/b10b5e5a-0ec0-4955-a643-e7da8ace757a)

`hide_tabs_toolbar` still works as expected, the tab bar disappears, but now the minimize, maximize, and close buttons also disappear. They don’t even overlap; they simply do not appear.

`windows_control_placeholder_support` still leaves the necessary space for the buttons to be positioned there, but apparently, it doesn't know where to find them to bring them into the interface. A CSS selector is likely not working, or something similar.

I'm sharing this in case someone can give me a hint on how to resolve it.

I know CSS, but I’ve never modified any parameters of Firefox's interface.

Any help would be appreciated, thanks!

**Comment by MrOtherGuy** [comment]
hide_tabs_toolbar.css and windows_control_placeholder_support.css are effectively deprecated. Use hide_tabs_toolbar_v2.css instead.
