### ISSUE TITLE
1px shift in hide_tabs_scrollbuttons.css

### ISSUE THREAD

**Issue by Dupond** [MrOtherGuy/firefox-csshacks#471]
I found a huge bug in the `hide_tabs_scrollbuttons.css` script!

When moving the active tab (even without tabs overflow, just with 1 tab opened) the tab content (for example the Firefox icon and the "New Tab" title) shifts 1 pixel to the right!

But WHO gives a damn about 1 pixel?!

I don't... It's just that I've had an overdose of work, I need to relax my nerves, and to calm down I'm playing with my userChrome file :)

Considering how huge this bug is, and how worried everyone is about this 1-pixel shift, feel free to close this topic, because "we don't give a sh..."

I did find the guilty line, though:

```
#scrollbutton-up ~ spacer { visibility: visible !important; }
```

Considering that it only happens when moving a tab, I've tried to change it like this:
```
#tabbrowser-tabs:not([movingtab]) > #scrollbutton-up ~ spacer { visibility: visible !important; }
```

But of course, it didn't work... Why I am not surprised?

Please close this issue, enjoy your life, and have a nice day!

**Comment by MrOtherGuy** [comment]
I might fix this, indeed oh so majestic issue, but alas, the behavior seems truly deliberate and I dare not to touch the arcane spells that keep the kingdom afloat.

**Comment by Dupond** [comment]
Thank you, O [most powerful and Shakespearean King](https://media.tenor.com/mfJimYfYYgsAAAAM/css-king.gif)! Be praised, you and your descendants, for 10 generations at least! May the power of CSS hacks enable you to restyle the whole world to your heart's desires!

**Comment by Dupond** [comment]
Oooops! I thought I had closed this issue, sorry!

I'm off to ask the butcher to give me 10 lashes!
