### ISSUE TITLE
while using autohide_main_toolbar.css, the background still shows

### ISSUE THREAD

**Issue by svban** [MrOtherGuy/firefox-csshacks#473]
The background doesn't autohide with the toolbar
![CleanShot 2024-12-01 at 15 56 31](https://github.com/user-attachments/assets/f992599b-e728-4003-9b90-a28c7dfddf40)

**Comment by MrOtherGuy** [comment]
Works just fine on my system. I find it kinda weird that there also isn't any animation for the hiding in your video. Are you sure you are using latest version?

It could also be that this is something mac specific which I cannot test, but I would still think that even some transitions would animate.

**Comment by svban** [comment]
I am at the latest version - v133.0

**Comment by Storm6543** [comment]
I had the exact same problem. In my case i was separating different css scripts with multiple " ///////// ", and it seems that even just one " / " before the script breaks it.
After removing those it started working normally.

Your case might be the same thing, check your userChrome.css file and see if there are any stand alone " / "  anywhere and remove them.

**Comment by svban** [comment]
I didn't had any comment starting with // but I did have a huge comment block at the start of the file. Removing that fixed the issue and everything is working smoothly now.
Thank You
