### ISSUE TITLE
WIndow controls centering on Firfox 133.0 (macOS Sequoia)

### ISSUE THREAD

**Issue by aayux** [MrOtherGuy/firefox-csshacks#477]
The window controls are centered into the address bar after recently updating to Firefox 133.0. Any idea as to why this would happen? My `userChrome.css` is

```css
@import url(window_control_placeholder_support.css);
@import url(hide_tabs_toolbar_os.css);
```
![Screenshot 2024-12-02 at 16 38 06](https://github.com/user-attachments/assets/ba1f98cc-ff5a-4a14-965f-2cde5c1d03fe)

**Comment by MrOtherGuy** [comment]
Just don't use neither of those styles. Use [hide_tabs_toolbar_v2.css](https://github.com/MrOtherGuy/firefox-csshacks/blob/master/chrome/hide_tabs_toolbar_v2.css) instead.
