### ISSUE TITLE
"privatemode_indicator_as_menu_button.css" no longer hides the private browser logo/text in Firefox 133.0

### ISSUE THREAD

**Issue by DumbIdiot** [MrOtherGuy/firefox-csshacks#478]
Looks like id "#private-browsing-indicator-with-label" was changed to a class as ".private-browsing-indicator-with-label" works and class ".private-browsing-indicator" is no longer used at all.

**Comment by MrOtherGuy** [comment]
Right you are, thanks for reporting!

**Comment by MaximilianKohler** [comment]
It's broken again.

**Comment by DumbIdiot** [comment]
I'm on 133.0.3 and it's still working for me.
