### ISSUE TITLE
How do I control the space *between* bookmark icons?

### ISSUE THREAD

**Issue by ifnullzero** [MrOtherGuy/firefox-csshacks#48]
multi-row_bookmarks.css

Thanks for this CSS. How would I control the space *between* bookmark icons on the toolbar?

I would like to close up the space a little, make it smaller if possible. How would I do that?

![tabbar](https://user-images.githubusercontent.com/25324819/82037835-9c527100-969a-11ea-856d-f991acfb472c.jpg)

Many thanks.

**Comment by ifnullzero** [comment]
I think this can be used to adjust the space:

```
#PlacesToolbarItems > .bookmark-item:not(:hover) {
  padding: 2px !important;
}
```

**Comment by MrOtherGuy** [comment]
#PlacesToolbarItems > .bookmark-item{
      margin-inline: 0px !important;
      padding-inline: 0px !improtant;
    }

Margin is really the space between items. Padding is more like the empty space between around the bookmark icon+text but which but what would still count as space within a bookmark.
