### ISSUE TITLE
'chrome/overlay_fullscreen_toolbars.css' no longer works properly 

### ISSUE THREAD

**Issue by moonfight1** [MrOtherGuy/firefox-csshacks#483]
sometimes it does this 
![image](https://github.com/user-attachments/assets/cfed3a72-08f1-4842-9601-1e4acaeb34a6)
and others it appears in the middle like this and disappears when you push your cursor to the top
![image](https://github.com/user-attachments/assets/664d7579-e9c3-4afa-ad77-010b45b69717)

**Comment by MrOtherGuy** [comment]
Yeah, okay - this is basically same thing as with all other styles that try to move nav-bar around - we just have to move urlbar separately. I'm pretty sure the style works now though after a couple of changes.

**Comment by cwilliams5** [comment]
Was gonna report this myself - and confirmed fixed after updating. As always, you the man MrOtherGuy.

**Comment by moonfight1** [comment]
> Yeah, okay - this is basically same thing as with all other styles that try to move nav-bar around - we just have to move urlbar separately. I'm pretty sure the style works now though after a couple of changes.

the urlbar just appears without looking connected to the rest of the navbar, the way ive fixed this is just setting the animations to 0ms, looks way better than having a disconnected animation where navbar has an animation, and urlbar just pops in
