### ISSUE TITLE
toolbars_below_content vs 133

### ISSUE THREAD

**Issue by e-pirate** [MrOtherGuy/firefox-csshacks#484]
Hi.
I had modified version of toolbars_below_content working fine before 133:
```
#mainPopupSet,
#browser,
#customization-container,
#appMenu-viewCache,
#PersonalToolbar,
#nav-bar{ order: -1 }

#urlbar[breakout][breakout-extend]{
  display: flex !important;
  flex-direction: column-reverse;
  bottom: -2px !important;
  top: auto !important;
}
```
This makes tab-bar at the most bottom position and url-bar just above it. Both at the bottom of window.
After 133 rolled in it kind of work, but the history panel (don't know the right name) now overlaps url-bar completely making it impossible to enter any url.

I've tried latest toolbars_below_content_v2 for the 133, but unfortunately the url-bar is now the bottom most instead of tab-bar as I got used to.

Can you please make your css magic work again: the tab-bar at most bottom, url-bar just above it. Call it toolbars_below_content_v3 maybe?

Thank you!

**Comment by MrOtherGuy** [comment]
You can move tabs as the bottom-most toolbar by simply adding this:
```css
#TabsToolbar{
  order: 3;
}
```

I've added that to the style as an optional feature that you can toggle by setting a pref `userchrome.toolbars-below-content.tabs-at-bottom.enabled`

**Comment by e-pirate** [comment]
This now works like a charm, thank you!
