### ISSUE TITLE
tab_animated_active_border.css not working correctly in dark mode (default firefox teheme)

### ISSUE THREAD

**Issue by wilford-schaffner** [MrOtherGuy/firefox-csshacks#488]
So in light mode, this css woks as intended, and it gives it a glowing colorful stroke. In dark mode, it colors the entire tab not just the border (see attached screenshots). It looks like the tab still has a fill but it's mostly transparent or something. How do I fix this

![Screenshot 2024-12-11 002412](https://github.com/user-attachments/assets/5c63c327-f3d3-40b5-bcb4-e894adb50004)
![Screenshot 2024-12-11 002505](https://github.com/user-attachments/assets/992ad075-cccf-4944-adaf-9e3e0d603321)

**Comment by MrOtherGuy** [comment]
Right, makes sense because of built-in dark themes the background-color of active tabs is not fully opaque so the animation can be seen through. Need to figure out some way to fix this.

**Comment by wilford-schaffner** [comment]
ahh, gotcha. That's what I figured. Maybe just a simple css to override the actual tab color itself. Do you know how I could go about this? Like just manually changing the color of the tab?

**Comment by MrOtherGuy** [comment]
Yes, you can do this:

```css
.tab-background[selected]{
  background-color: #f00 !important;
}
```

But I don't want to change the color because it should be controlled by user's theme.
