### ISSUE TITLE
toolbars_below_content_v2.css causes permission popups to go below the window

### ISSUE THREAD

**Issue by QuantenToast** [MrOtherGuy/firefox-csshacks#493]
- I updated the css file
- Firefox 133.0.3
- Linux

The permission popups go below the window (microphone and enabling extensions) and if the Window takes up the entire screen it goes off screen making it unable to allow those until the window is moved (or on Hyprland getting squished and unclickable).

**Comment by MrOtherGuy** [comment]
That actually seems like a problem with affecting Firefox on Linux more generally. Other panels I tried seem to behave better, but the permissions panel apparently always open downwards on linux (Fedora with gnome) - the issue with the panel becoming inaccessible will also happen without any css if you window is positioned such that only the very top of it is visible.

On Windows 10 the permissions panel knows top open upwards if it cannot fit into the current active screen.

I believe the best I can do to fix this would be to move the notification panel upwards by a a fixed amount on all linux systems. While not great, it would at least make the panel accessible.
