### ISSUE TITLE
what settings in FF for using userChrome.css

### ISSUE THREAD

**Issue by Cuervino** [MrOtherGuy/firefox-csshacks#50]
Hello,
I reinstall my config today, and spent some time on trying to get back previous settings.
Maybe you could notice in the Readme file that the line `toolkit.legacyUserProfileCustomizations.stylesheets` should be set as `True` in `about:config` of FF ?

**Comment by MrOtherGuy** [comment]
I could indeed do that. There's a bunch of changes incoming I've planned to the readme and I'll add this to the list.
Thanks.

**Comment by MrOtherGuy** [comment]
Readme.md now includes this information
