### ISSUE TITLE
Lowering autohide_toolbox.css's "transform: rotateX(86deg)" value does not make the toolbox appear earlier on hover anymore

### ISSUE THREAD

**Issue by Itamiii** [MrOtherGuy/firefox-csshacks#53]
Hello, I just noticed that compared to my old version of your code I'm using, in this new version lowering the "transform: rotateX(86deg)" to like 60 which used to work perfectly for me, now has absolutely no effect.

Sadly now dependent on my windows scale and which monitor I'm using I can't get the toolbox any more at all because it won't detect my mouse hovering close to it.

Thanks for your amazing work on this though! I really appreciate your tools, and they make my every day browsing experience a lot better.

**Comment by MrOtherGuy** [comment]
Hmm. It definitely works for me though. Please note that the part that uses 86deg only affects windowed mode windows. On maximized windows the default is 89.5deg

**Comment by Itamiii** [comment]
Its very odd, on Windows minimized and maximized both only changing the 86deg value did the trick for windowed and maximized windows (did not test fullscreen).

Now with the new version only changing the 86deg alone does nothing windowed or maximized window for me.
However, I just changed both to 60 and 60.5deg and now it works as before for both windowed and maximized for some reason.

I guess that fixes it for me, so thanks for the help!
