### ISSUE TITLE
Urlbar Behind Drop-Down With 'urlbar_full_width.css'

### ISSUE THREAD

**Issue by samuel-first** [MrOtherGuy/firefox-csshacks#56]
I'm pretty sure this is the same problem as #36.  As a temporary work-around, I've manually set .urlbarView's [margin](https://github.com/MrOtherGuy/firefox-csshacks/blob/f8107111636b33d9797477a2ab00deb8473d54db/chrome/urlbar_full_width.css#L23) to 28px, which isn't very portable, but gets the job done.  The only other difference between the current version and the version I have is the license notice at the top of the file.

Here's a diff:
```
< /* Source file https://github.com/MrOtherGuy/firefox-csshacks/tree/master/chrome/urlbar_full_width.css made available under Mozilla Public License v. 2.0
< See the above repository for updates as well as full license text. */
< 
23c20
<   margin: 0 !important;
---
>   margin: 28px !important;
38c35
< #urlbar > #urlbar-input-container::before{ content: ""; display: -moz-box; height: 24px; }
\ No newline at end of file
---
> #urlbar > #urlbar-input-container::before{ content: ""; display: -moz-box; height: 24px; }
```

**Comment by MrOtherGuy** [comment]
Damn. I'm not sure what I've been thinking. I sort of think that I've accidentally deprecated the wrong file `full_width_urlbar_popup.css` whereas I should have deprecated this one.

But I'm not sure. The CSS should be pretty easy to fix and `full_width_urlbar_popup.css` actually seems to work almost perfectly as is.

I'll dig a bit deeper later today, thanks for reporting!

**Comment by MrOtherGuy** [comment]
No, actually this is the currently supported file.

There was just one small detail to fix. It should be working now.
