### ISSUE TITLE
Both nav-bar and multirow tabs below content - broken on FF 77.0.1

### ISSUE THREAD

**Issue by nulltab** [MrOtherGuy/firefox-csshacks#59]
Hi.

This is a continuation of #44
My config stopped working after FF 77.0.1 update.

My current config - https://gist.github.com/nulltab/61cacf3d207d835bce9a51115962f82a

Now it looks like this:

![2020-06-07-154150_1680x458_scrot](https://user-images.githubusercontent.com/28522111/83969121-c5030a80-a8d6-11ea-9dbf-3f7a047faa3a.png)

Could you please help? 
Thanks again.

**Comment by MrOtherGuy** [comment]
Since you seem to want to move both main-toolbar and tabs toolbars to bottom then I would think that you should use toolbars_below_content.css + multi-row_tabs.css instead of whatever you are trying to do currently.

**Comment by nulltab** [comment]
It works. Thanks a lot!
