### ISSUE TITLE
Change default scrollbar color

### ISSUE THREAD

**Issue by rjgotten** [MrOtherGuy/firefox-csshacks#60]
Currently the modification to enable scrolling in the urlbar popup renders the scrollbar thumb using `currentColor` which results in an intense black if you're using a default theme.

https://github.com/MrOtherGuy/firefox-csshacks/blob/89dfae2f88fd30fa17a60c55429a552be2dd1f71/chrome/scrollable_urlbar_popup.css#L12-L13

I'd suggest changing that to `scrollbar-color : Scrollbar transparent`.
While the `Scrollbar` color keyword is deprecated it _does_ still work fine in Firefox and uses the actual platform native scrollbar thumb color.

**Comment by MrOtherGuy** [comment]
I do agree that hard-black is kinda harsh. However, `scrollbar` isn't a good solution since a) it's deprecated (I didin't even know it existed) and b) it only works on Windows. On Linux (and probably on OSX too) it computes to `transparent` which is obviously not good.

**Comment by rjgotten** [comment]
Maybe make it injectible via a CSS variable then? And default to something a little less "hard" than pure black.

**Comment by MrOtherGuy** [comment]
Maybe `var(--urlbar-separator-color)` would be a good fit since it's been used in the popup anyway.

**Comment by rjgotten** [comment]
Hm.. yeah, that'd probably work. 👍

**Comment by MrOtherGuy** [comment]
> Maybe `var(--urlbar-separator-color)` would be a good fit since it's been used in the popup anyway.

This is now the default behavior, so I'm closing this issue
