### ISSUE TITLE
Tabs overlap title in show_window_title_in_menubar.css

### ISSUE THREAD

**Issue by evanswa0606** [MrOtherGuy/firefox-csshacks#62]
Trying to make a title bar as firefox's default title bar for osx is white. show_window_title_in_menubar.css makes the tabs overlap the title. How can I separate?

**Comment by MrOtherGuy** [comment]
Yeah, that's really meant to be used with menubar, but osx doesn't have one so this happens.

You could probably just add `#TabsToolbar{ padding-top: 20px !important; }` to move contents of tabs toolbar downwards though.
