### ISSUE TITLE
Firefox 77 multirow tabs s only first line

### ISSUE THREAD

**Issue by 3DRaven** [MrOtherGuy/firefox-csshacks#64]
Hi! In attached file You can see that in browser showed one line with tabs and scroll bar.

https://imgur.com/a/hoZJ56s

**Comment by 3DRaven** [comment]
I used 
https://github.com/MrOtherGuy/firefox-csshacks/blob/master/chrome/multi-row_tabs.css
https://github.com/MrOtherGuy/firefox-csshacks/blob/master/chrome/multi-row_tabs_Fx66%2B.css

CSS files

**Comment by MrOtherGuy** [comment]
Did you try with just multi-row_tabs.css? The other file you mention should not be used anymore, it is deprecated and only exists as historical reference.

**Comment by 3DRaven** [comment]
Bug is fixed. I don't know why :)
