### ISSUE TITLE
rotateX(70deg) in the autohide toolbox doesnt apply to maximized windows anymore

### ISSUE THREAD

**Issue by Itamiii** [MrOtherGuy/firefox-csshacks#66]
Hello, sadly in the new code, the rotateX(70deg) won't change for maximized windows anymore. 
It works perfectly fine if Firefox is normally windowed though so not taking up the entire screen.

This makes it impossible to work with on my UHD / 4K display since no matter what I set rotateX(70deg) to, I can't open the UI/ toolbox anymore at all.

btw, thanks for your amazing work! It makes my browsing experience much better <3

**Comment by MrOtherGuy** [comment]
I have an idea about what could be going on.

Firefox had some changes to how Windows window "margins" are computed, and this style is unfortunately super picky about what values work properly. I've made some changes to it now, but I don't have a 4K monitor to test (it works with 1440p though on multiple DPI scaling values)

**Comment by Itamiii** [comment]
Thanks for your quick response!

I have tested the new code version. 
It now opens on my 4k monitor. 
However, really oddly the rotateX(70deg) has no effect on the maximized window hover distance. So it only shows the toolbox upon hovering the top most last pixel of the screen.
Surprisingly the old code I have been using doesn't have this issue but other issues with the bookmarks etc.
This behavior is the same on my 1440p monitor.

This is the old code version I have been using, hope it helps:
@media (-moz-os-version: windows-win10){

  :root[tabsintitlebar][sizemode="maximized"]:not([inDOMFullscreen]) > body > box{ margin-top: 10px !important; }
  :root[tabsintitlebar][sizemode="maximized"] #navigator-toolbox{ margin-top: -2px }

  @media screen and (min-resolution: 1.25dppx){
    :root[tabsintitlebar][sizemode="maximized"]:not([inDOMFullscreen]) > body > box{ margin-top: 9px !important; }
  }
  @media screen and (min-resolution: 1.5dppx){
    :root[tabsintitlebar][sizemode="maximized"]:not([inDOMFullscreen]) > body > box{ margin-top: 8px !important; }
    :root[tabsintitlebar][sizemode="maximized"] #navigator-toolbox{ margin-top: -1px }
  }
  @media screen and (min-resolution: 2dppx){
    :root[tabsintitlebar][sizemode="maximized"]:not([inDOMFullscreen]) > body > box{ margin-top: 7px !important; }
  }
}

:root[sizemode="fullscreen"]{ margin-top: 0px !important; }

#navigator-toolbox{
  position: fixed !important;
  display: block;
  background-color: var(--lwt-accent-color,black) !important;
  transition: transform 82ms 33ms linear, opacity 82ms 33ms linear !important;
  transform-origin: top;
  line-height: 0;
  z-index: 1;
  pointer-events: none;
}

#navigator-toolbox > *{ line-height: normal; pointer-events: auto }

#navigator-toolbox,
#navigator-toolbox > *{
  width: 100vw;
  -moz-appearance: none !important;
}

#navigator-toolbox:not(:focus-within):not(:hover){
  transform: rotateX(70deg);
  opacity: 0;
}

:root[sizemode="maximized"] #navigator-toolbox:not(:focus-within):not(:hover){ transform: rotateX(70.5deg) }

/* Don't apply transform before window has been fully created */
:root:not([sessionrestored]) #navigator-toolbox{ transform:none !important }

:root[customizing] #navigator-toolbox{
  position: relative !important;
  transform: none !important;
  opacity: 1 !important;
}

#navigator-toolbox[inFullscreen] > #PersonalToolbar,
#PersonalToolbar[collapsed="true"]{ display: none }

**Comment by MrOtherGuy** [comment]
The line where your old code has `rotateX(70deg);` only affects the size of the area in windowed mode. The line below (your code has 70.5deg there) is the one that affects maximized windows.

> Surprisingly the old code I have been using doesn't have this issue but other issues with the bookmarks etc.

What's wrong with bookmarks? I'm not aware of any issues related to them.

**Comment by Itamiii** [comment]
Ahh I see so both lines need to be changed then.

Bookmarks had an odd glitch in the older code I posted, but this seems to be fixed in your latest code version so all is fine now. 
Thanks a lot for your time and help!
