### ISSUE TITLE
[ISSUE] Dark Additional Windows Are Unreadable

### ISSUE THREAD

**Issue by jruaaa** [MrOtherGuy/firefox-csshacks#67]
![image](https://user-images.githubusercontent.com/32626650/89112538-f56bae80-d418-11ea-853f-4435424a8b55.png)

The program opening link windows like custom bakkesmod:// and shell:// windows are still unreadable. I have no idea how to theme these but thought I'd mention it.

**Comment by MrOtherGuy** [comment]
I'm not sure what's wrong here, see:

![image](https://user-images.githubusercontent.com/31620503/89116929-0f9d9f00-d4a2-11ea-8045-838c81d7624d.png)

That's how it looks like on my system. Do you see the same issue happening on page info window? Right click a page and select "view page info"

**Comment by MrOtherGuy** [comment]
Okay, I found out that the stylesheet does not affect windows that try to open a program associated with some uri scheme - such as `steam://`
After adding a `@-moz-document` query for that it should look like this: 

![image](https://user-images.githubusercontent.com/31620503/89118019-488e4180-d4ab-11ea-8d93-c4f71f03e66b.png)

I still don't have a clue about what causes the problem in you screenshot though.

**Comment by jruaaa** [comment]
I fixed that part the steam link was the main thing

Regards,

Joey Ruan

**Comment by MrOtherGuy** [comment]
Does that mean that there aren't any remaining problems?

**Comment by jruaaa** [comment]
Yep
