### ISSUE TITLE
Dynamic color tabs

### ISSUE THREAD

**Issue by ozzyjr** [MrOtherGuy/firefox-csshacks#71]
Hello

Would it be possible to add this effect to the colors of the tabs just like [Paxmod](https://github.com/numirias/paxmod)?

![image](https://user-images.githubusercontent.com/12512993/92147458-902d2380-edf1-11ea-98fa-19d2e8d10bbd.png)

**Comment by MrOtherGuy** [comment]
What is that color based on? Is it the color of the container (this wouldn't work I think)? Or is it just based on the index of the tab so first is always green-ish, the second orange etc. or is it something else entirely?

**Comment by MrOtherGuy** [comment]
Actually, container-color based works just fine. All you need is `.tab-content{ color: var(--identity-tab-color,inherit) }`

**Comment by ozzyjr** [comment]
According to the documentation

>"Each tab color is generated dynamically from the favicon. A dominant color is extracted from the image and adjusted to an appropriate lightness per the [Lab color space](https://en.wikipedia.org/wiki/Lab_color_space). This ensures that all tab labels are legible. (You can also set lightness thresholds in the settings.)"

I think he uses [this function](https://github.com/numirias/paxmod/blob/master/src/iconcolor.js) for that.

**Comment by MrOtherGuy** [comment]
I see. Well, that's certainly impossible with css. So no, not going to happen in this repository.

**Comment by ozzyjr** [comment]
OK
Thanks
