### ISSUE TITLE
urlbar_popup_full_width.css: how to keep the starting offset like in FF68?

### ISSUE THREAD

**Issue by j1warren** [MrOtherGuy/firefox-csshacks#75]
![ff_width](https://user-images.githubusercontent.com/46167694/93767879-10cc8c00-fc08-11ea-84d4-3afab67e7ca8.png)

Currently the results appear in urlbar right at the left side, under 'back' button.
How can I make them appear under the urlbar start? Like it was in FF68 (see picture).

**Comment by MrOtherGuy** [comment]
I honestly don't know how this should be done and I would've done it if I knew. So, if anyone has an idea how to do this **automatically** then please let me know or create a pull-request.

Luckily you can **manually** do this pretty easily by adding something like `.urlbarView-row{ padding-inline-start: 248px }` but you'll need to adjust the value based on your toolbar layout.

I could add that as a default and the insert a comment for user to modify the value to suit their needs though.

**Comment by j1warren** [comment]
@MrOtherGuy thank you! Works for me.
Maybe add it in a commented out form for those who want to adjust it.

**Comment by MrOtherGuy** [comment]
Yeah, you're right - it needs to be of form `.urlbarView-row-inner{ padding-inline-start: 248px !important; }`

I think I could add it in as defaulting to `6px` which is what Firefox seems to use itself. And then add comment such as `/* increase this value to modify text offset from left edge */`

Sound good?

**Comment by j1warren** [comment]
Sure.

Thanks again!

**Comment by MrOtherGuy** [comment]
Cool. Fixed in 55c03cb1a2960053bbdc49a499928b22cdc44ee5
