### ISSUE TITLE
Typo of menu-iconic-left margin-inline?

### ISSUE THREAD

**Issue by GJRobert** [MrOtherGuy/firefox-csshacks#86]
https://github.com/MrOtherGuy/firefox-csshacks/blob/cf7d1ea23c27efb9643e1a7c07f269fa28bd663d/chrome/custom_menupopup_check_icons.css#L8

Is the `8px` typo of `3px`?

**Comment by MrOtherGuy** [comment]
It is not. The first value is for margin-inline-start (ie usually margin-left) and the second is for margin-inline-end (usually right).

How so?

**Comment by GJRobert** [comment]
Thanks a lot, and pardon for a CSS kindergartener...
