### ISSUE TITLE
autohide_bookmarks_toolbar.css and navbar_tabs_oneliner.css don't work together nicely

### ISSUE THREAD

**Issue by LOuroboros** [MrOtherGuy/firefox-csshacks#91]
Title.

When using these 2 together, a black bar appears in the spot where the bookmarks bar normally is.

https://user-images.githubusercontent.com/4485172/109271673-9fb08680-77ee-11eb-8bbe-8a5a3b4ffca4.mp4

For reference, I use Mozilla Firefox v86 *(32-bit)*.

***Note**: Despite how big the file may look, I'm not using any other snippets than the 3 I show in the video. What's below is purely padding to keep things nice and clean in case I ended up adding other snippets at a later point.*

**EDIT**: While I'm at it; may I receive some pointers on how to reduce a little the padding to the left of the Back arrow, around the top left corner of Firefox's window?
I don't know why it's there, but I personally dislike it and I don't really know how to go about it myself :eyes:

**Comment by MrOtherGuy** [comment]
Just to be sure, are your files up to date?

I tried all three together with Firefox Developer Edition (so 87) and no such empty space appears. As far as I can tell they work fine together.

**Comment by MrOtherGuy** [comment]
> While I'm at it; may I receive some pointers on how to reduce a little the padding to the left of the Back arrow, around the top left corner of Firefox's window?

Yes, its a drag space so you can drag the window. Modify the value [set here](https://github.com/MrOtherGuy/firefox-csshacks/blob/9f30038c9fe893725f644ace425bf59a8a93c64f/chrome/navbar_tabs_oneliner.css#L44)

**Comment by LOuroboros** [comment]
> 
> 
> Just to be sure, are your files up to date?
> 
> I tried all three together with Firefox Developer Edition (so 87) and no such empty space appears. As far as I can tell they work fine together.

Yep, they are. I got them this very morning after all.

Could this be related to my screen resolution? It's 1360x768, just in case.



> 
> 
> > While I'm at it; may I receive some pointers on how to reduce a little the padding to the left of the Back arrow, around the top left corner of Firefox's window?
> 
> Yes, its a drag space so you can drag the window. Modify the value [set here](https://github.com/MrOtherGuy/firefox-csshacks/blob/9f30038c9fe893725f644ace425bf59a8a93c64f/chrome/navbar_tabs_oneliner.css#L44)

I tried to modify the value from 24px to 16px and I didn't notice a difference. Then I lowered all the way down to 0px, and nothing really changed either :/

**Comment by MrOtherGuy** [comment]
> I tried to modify the value from 24px to 16px and I didn't notice a difference. Then I lowered all the way down to 0px, and nothing really changed either :/

Right, I forgot you were using that classic-menu-button style too. The space between menu button and the back-button is controlled [right here](https://github.com/MrOtherGuy/firefox-csshacks/blob/9f30038c9fe893725f644ace425bf59a8a93c64f/chrome/classic_firefox_menu_button.css#L16) - in your case it will use the fallback value 24px, but you may as well just set `:root{ --uc-window-drag-space-width: 0px }` somewhere in your file which should collapse the space to minimal.

But I think I know what the compatibility issue is. You have added those separator lines `-------` between things, but those cause a syntax error and thus the first ruleset of the next "file" will be ignored. So remove your separators and they should work fine. If you still want to use separators then add them like `/***(repeat)***/` - but license block of my files works fine as well.

**Comment by LOuroboros** [comment]
> 
> 
> > I tried to modify the value from 24px to 16px and I didn't notice a difference. Then I lowered all the way down to 0px, and nothing really changed either :/
> 
> Right, I forgot you were using that classic-menu-button style too. The space between menu button and the back-button is controlled [right here](https://github.com/MrOtherGuy/firefox-csshacks/blob/9f30038c9fe893725f644ace425bf59a8a93c64f/chrome/classic_firefox_menu_button.css#L16) - in your case it will use the fallback value 24px, but you may as well just set `:root{ --uc-window-drag-space-width: 0px }` somewhere in your file which should collapse the space to minimal.
> 
> But I think I know what the compatibility issue is. You have added those separator lines `-------` between things, but those cause a syntax error and thus the first ruleset of the next "file" will be ignored. So remove your separators and they should work fine. If you still want to use separators then add them like `/***(repeat)***/` - but license block of my files works fine as well.

Effectively, that was the cause of my troubles!

Commenting out each line break worked nicely. autohide_bookmarks_toolbar.css now works normally, and I was able to get rid of the padding in classic_firefox_button.css too.

Thank you very much!
