### ISSUE TITLE
Changing the value of --uc-toolbar-height in navbar_tabs_oneliner.css doesn't seem to do anything

### ISSUE THREAD

**Issue by LOuroboros** [MrOtherGuy/firefox-csshacks#92]
I'm not sure if I misunderstood something here *(I may; I don't know about CSS at all honestly)*, but modifying the values of the variables presented in **[the navbar_tabs_oneliner.css file](https://github.com/MrOtherGuy/firefox-csshacks/blob/master/chrome/navbar_tabs_oneliner.css)** inside `#navigator-toolbox` should let me tweak the sizes of the elements of the navbar to my liking, yes?
Modifying the value of `--uc-navigationbar-width` does produce a change in the size of things like the URL bar's width.

However, modifying the value of `--uc-toolbar-height` doesn't seem to produce any noticeable changes.
I tried to reduce it all the way from 40px to 10px, but everything looks the same upon rebooting Firefox.

For reference, I'm using Mozilla Firefox v86 *(32-bit)*.
Also, alongside this snippet I'm also using **[classic_firefox_menu_button.css](https://github.com/MrOtherGuy/firefox-csshacks/tree/master/chrome/classic_firefox_menu_button.css)**.

**Comment by MrOtherGuy** [comment]
Eh. It doesn't really work like that. Although I certainly intended it like that originally. It's more like a variable to keep size of tabs toolbar and nav-bar in sync - there's just too many other constraint in toolbars that prevent it from being freely modifiable.

**Comment by LOuroboros** [comment]
> 
> 
> Eh. It doesn't really work like that. Although I certainly intended it like that originally. It's more like a variable to keep size of tabs toolbar and nav-bar in sync - there's just too many other constraint in toolbars that prevent it from being freely modifiable.

Ah, I see. Well, I'll try to look into shrinking the size of the elements in the OneLine'd navbar myself then.

Thank you for the response!
