### ISSUE TITLE
Problems with combined_favicon_and_tab_close_button.css

### ISSUE THREAD

**Issue by Lepefe** [MrOtherGuy/firefox-csshacks#95]
Hello Dev,

I'm having problems with your https://github.com/MrOtherGuy/firefox-csshacks/blob/master/chrome/combined_favicon_and_tab_close_button.css

The close button is not appearing at all.

It seems that .tab-close-button changed to .tab-close-button.close-icon. But even if I make changes, I still have problems with your script (close button partially works if I remove visibility:hidden and if I change z-index: 1 !important, but as collateral effect close image is never hidden).

Hope you can shed some light on my problem.

Cheers

**Comment by MrOtherGuy** [comment]
That style should work fine in Release Firefox. In nightlies it doesn't and it also might not if you use Proton styling.

I'm not making proton specific changes to existing styles at this point in time because they would need to be adjusted daily.

Still, thanks, now I'm aware that this is one of the styles that needs changing.

**Comment by MrOtherGuy** [comment]
Actually based on the way how latest nightly works, it is only possible to make the first of the three behaviors work which is "no favicon - no close-button"

**Comment by Lepefe** [comment]
Thank you for your replay @MrOtherGuy.

I'm using Firefox Nightly, sorry I didn't mention that.
But I'm not using any Proton styling.
And I'm using first option "no favicon - no close-button".

Unfortunately and as I said I still have problems with your script, I tried many changes using the multiprocess browser toolbox, I can make little progress but it's only a partial patch.

If you have a non-Proton solution for Nightly, please it'll be very useful to me and I'll be very grateful.

**Comment by MrOtherGuy** [comment]
Sure, you can make the first option work by replacing `.tab-icon-image:hover` (on line 25) with `.tab-icon-stack:hover`

Works at least currently, but since lots of changes are happening it might not work in a few days. Or it might, who knows.

**Comment by Lepefe** [comment]
Thank you @MrOtherGuy, now works perfectly.
