### ISSUE TITLE
Proton changes list

### ISSUE THREAD

**Issue by MrOtherGuy** [MrOtherGuy/firefox-csshacks#96]
List of styles that need adjusting for Proton. Incomplete.

* ~~autohide_bookmarks_and_main_toolbars.css~~ - OK
* ~~button_effect_scale_onhover.css~~ - OK
* ~~classic_grid_main_menu_popup.css - probably needs complete rewrite since proton appmenu is totally different and doesn't have any icons ~~ OK
* ~~color_variable_template.css - color variable need to be updated once proton variables replace old ones~~ OK
* ~~combined_favicon_and_tab_close_button.css~~ - OK
* ~~compact_urlbar_megabar.css~~ - OK
* ~~curved_tabs.css~~ - OK 
* ~~hide_tabs_toolbar.css (and for osx)~~ - OK
* ~~hide_tabs_with_one_tab.css~~ - OK
* ~~navbar_tabs_oneliner.css~~ - OK
* ~~overlay_menubar.css~~ - OK
* ~~tab_line_loading_indicator.css~~ - OK
* ~~tabs_animated_gradient_border.css - can probably be deprecated because tab shape, I dunno not a priority~~ OK
* ~~vertical_context_navigation.css~~ - OK
* ~~vertical_context_navigation_v2.css~~ - OK

Few styles that could be backwards-compatibly modified have been fixed already. All-in-all it's not that big of a task than I thought it would be.

**Comment by jacksongoode** [comment]
You're a madman! Thanks for all the hard work!

**Comment by MrOtherGuy** [comment]
All the points mentioned above should now be resolved, so I'm closing this.
